monero-project/monero-gui

LICENSE
README.md

Also, structure readme sections consistently with bitmonerod, to make the concise.
Also, moved license so that packages can fetch and install it directly.

readme: section on installing from package

---

monero-core.pro

Distribution packages should link dynamically (static libs for dependencies are not available for most packages), so let's add an option for choosing static build when needed but also allowing dynamic build.
Also, libunwind was needed to link on Arch Linux, so added it.

qmake project: option for static build and libunwind

---

build.sh
get_libwallet_api.sh
monero-core.pro

changes regarding bitmonero->monero renamings + disabled link to libunwind for Linux build (https://github.com/monero-project/monero/issues/1090).

Bitmonero renamings

---

main.qml

Fixes a critical bug that could leave a wallet in broken state after a crash (god forbid).
The bug only affects newly created wallets where wallet is synced, has transactions but isn't closed properly. When opening the crashed wallet the fast sync method will be used which will miss any transactions made from the wallet and therefore leaving it in broken state. 
Consider moving this logic to libwallet in future.
Fixes https://github.com/mbg033/monero-core/issues/59

critical: broken wallet after crash

---

components/PasswordDialog.qml
pages/Settings.qml
wizard/WizardMain.qml

- store pw in session to be able to view seed on settings page immediately after new wallet is created
- empty pw field after form submission
- strict comparison

various password issues fixed

---

MiddlePanel.qml
monero-core.pro

module QtQuick.Controls 2.0 should not be used until Qt 5.7 available in msys2.  Currently it's only 5.6 and it doesn't contain that module.

Fix Windows MSYS2 build

---

pages/Receive.qml

This needs a matching update from monero to not override
invalid payment ids.
NOTE: see https://github.com/monero-project/monero/pull/1228 and https://github.com/monero-project/monero-core/issues/64 that go with this.

Receive: allow integrated addresses from custom payment ids

---

README.md

Added proper indentation in the README markup for the Linux build instructions so that the numbering of the steps will work as intended.
Instances of bitmonero were changed to Monero to follow the updated naming conventions in Wolfram Warptangent.
Also changed some of the wording of the steps.

Fixed markup errors and naming in Linux build instructions

---

README.md
src/libwalletqt/TransactionHistory.cpp

1. `firstDateTime` was set to current date, whereas `lastDateTime` was set to the genesis block. This should be the other way around. [This](https://i.imgur.com/4kwb8Bh.png) is how it looked before the PR. 
2. The GUI connects to mainnet by default. Thus, we should remove the `--rpc-bind-port 38081` (testnet) from the README.

Fix erroneous DateTime & small README change

---

README.md
monero-core.pro

This adds the paths to the openssl and boost libraries (installed with brew) for the MacOS X
build. Furthermore the MacOS X build instructions in the README.md has been improved (formatting).

Adds openssl and boost lib includes for OSX build

---

BasicPanel.qml
MiddlePanel.qml
pages/Transfer.qml

Something like 0.000000000012 was converted to 1.2e-11
by the conversion to double, and that was rejected by
the Cryptonote parser.

Fix small amounts from being conflated with zero

---

main.qml
src/libwalletqt/PendingTransaction.cpp
src/libwalletqt/PendingTransaction.h

Depends on https://github.com/monero-project/monero/pull/1307

Transfer: display number of split tx in transaction confirmation popup

---

pages/Transfer.qml
wizard/WizardFinish.qml

Also, make the second word of "Privacy level" lowercase to follow suit with the rest of the titles.

Call the mnemonic seed 'Seed' instead of 'Words' in the Create Account Wizard

---

main.qml

Fixes https://github.com/monero-project/monero-core/issues/153
Automatic opening of wallet from default location is not needed anymore when we have the wallet picker. (Note: Not to be mistaken of automatic opening of last opened wallet which is still working)

Do not open wallet from default location automatically

---

pages/History.qml

Seems "null" objects in Javascript can either be null, or
be non null but with a type of 'undefined' (as a string).
Whatever.

History: do not dereference a null model

---

MiddlePanel.qml
components/DaemonManagerDialog.qml
components/DaemonProgress.qml
components/HistoryTable.qml
components/PasswordDialog.qml
components/StandardDialog.qml
main.cpp
main.qml
monero-core.pro
pages/Settings.qml
pages/Transfer.qml
qml.qrc
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Start/stop daemon from GUI + random improvements.
Requires a monerod/monerod.exe in same folder as monero-core binary.
All cli arguments are passed to monerod. For example --data-dir
**Win32** 
Includes monerod 0.10.0.0
https://www.dropbox.com/s/ooigmm2kjxaja1t/monero-core-win32-daemon-manager-jaquee.zip?dl=1
**Note:** Sending funds is not is possible with included daemon. 
**OS X**
Includes monerod built from current master `17b6bd6`
https://www.dropbox.com/s/lqs9mpc50k20oq5/monero-core-osx-daemon-manager-jaquee.zip?dl=1
Fixes
https://github.com/monero-project/monero-core/issues/39
https://github.com/monero-project/monero-core/issues/165

Daemon manager

---

MiddlePanel.qml
components/TitleBar.qml
main.qml

Except the yellow layout change one, which is actually useful
In particular, the close button closed without saving the wallet
cache, contrary to what closing using the window manager close
button did. Which isn't nice if you want to keep your tx keys.
Also, the size change buttons don't work.
Also tweak the WM hints to make sure there's a close button
displayed on all platforms.

Remove useless black bar buttons

---

main.cpp
wizard/WizardCreateWallet.qml
wizard/WizardMain.qml
wizard/WizardRecoveryWallet.qml

Until https://github.com/monero-project/monero-core/issues/199 and https://github.com/monero-project/monero/issues/1390 is fixed in Wallet2 we can't allow non-ascii characters i path.

Do not allow non-ascii characters in path on windows. 

---

get_libwallet_api.sh
monero-core.pro

boost on build machine is built with Qt's mingw toolchain

win32: use static boost

---

README.md

This is redundant, at least for now. Dependencies are detailed in each build instruction.

Remove Dependencies section

---

pages/TxKey.qml

This brings the "Check" button on the Verify Payment page into alignment with the rest of the text.

No left margin for button on Verify Payment page

---

components/PrivacyLevelSmall.qml
components/TickDelegate.qml

This was a braino on my part, this is only applicable for the
list based low/high selector.

Remove fee multiplier info from low/high slider

---

main.cpp

It seemed that there was agreement in discussion of #205 that the hyphenated 'monero-project' was to be preferred over camelcase or spacing. This PR puts this clearly very pressing issue to rest :)

Change organisation name to monero-project

---

pages/Transfer.qml

1. "Paste" vs. "Type" in address.
2. Description is not saved to local address book but to local history page.

Improved field descriptions on Send page

---

pages/TxKey.qml

Shortened/simplified some text.
Changed placeholders from the word "transaction" to the shorthand "tx". Since the user already sees the word "transaction" to the left of the field, they understand that they mean the same thing, which is important since the History page, where most will get their tx IDs and tx keys, use "tx" instead of "transaction".
Also the placeholders were changed from "Transaction ID here" to "Paste transaction ID". The text to the left of the field already is an indicator of what the box is for, so the placeholder instead acts as an action for the user to take (paste!).

Improved description of Verify Payments page

---

pages/Sign.qml

fontSize: 18 made text run off page, but 16 fits great.

Reduce fontsize in Sign/Verify for Compact View

---

wizard/WizardOptions.qml

Two fixes: 
(1) Removed first-person text. "I want to create a wallet" becomes "Create a wallet". The first person perspective wasn't helping as much as it was getting in the way of the user. It takes a long time to read the phrase "This is my first time, I want to create a new wallet" vs. the phrase "Create a new wallet". I think the original intent was to make the wizard more friendly for newbies but it really wasn't achieving that effect. New people are just going to click on "Create a new wallet" anyways, and there are plenty of people who will want to create a new wallet, but for whom it won't be their "first time".
(2) Normalized the terminology. The first two options (create / restore from seed) were calling wallets "accounts" while the third option (open file) was calling them …

Simplify text on wizard Option page

---

LeftPanel.qml

Now that we have an Advanced section of the left menu, Verify Payment and Sign/Verify are now next to each other. They sound the same. This PR changes the Verify Payment tab to Check Payment to better differentiate the two, which works well since the button inside Verify Payment is labeled "Check" anyways.

Tab text: change Verify Payment to Check Payment

---

lang/languages.xml

I thought it was agreed some time back that the language names would be adjectives in their own languages, but it does not seem that this has been effected. In the meantime, English adjectives can suffice. What does *not* make sense is a mix of adjectives and nouns. "Choose your language: English, Russia, or Brasil" sounds potato.

Adjectives or nouns for Languages

---

wizard/WizardCreateWallet.qml
wizard/WizardFinish.qml
wizard/WizardManageWalletUI.qml
wizard/WizardMemoTextInput.qml
wizard/WizardOptions.qml
wizard/WizardPassword.qml
wizard/WizardRecoveryWallet.qml

Multiple edits for copy on Create/Restore wallet wizard. Most simplified and shortened the existing text, others clarified what was a bit confusing ("enter your 25 word private key"), while others normalized more terminology (no longer calling wallets "accounts"). 
Probably the biggest change was to the titles of the pages. The previous titles tried to lead the user through the process ("A new wallet has been created for you"), but this often served to detract from the purpose of the page, for example the page "A new wallet has been created for you" was the page where the user was supposed to give their wallet a name. Now all the titles are simple and uniform ("Give your wallet a name" - "Give your wallet a password") and any necessary details were added below the titles.
The main edits …

Improved copy for GUI Wizard

---

build.sh
get_libwallet_api.sh
monero-wallet-gui.pro

fixes https://github.com/monero-project/monero-core/issues/58
@fluffypony @danrmiller
update buildbots from `./build.sh Release `-> `./build.sh release-static` when this is merged.

optional static build on linux/mac

---

wizard/WizardFinish.qml
wizard/WizardManageWalletUI.qml
wizard/WizardPassword.qml

Reduce the number of "balls" in the wizards (creation of wallet and recovery) to be coherent with the hidden steps (3 steps instead of 4). Color green for all.

Reduce the number of "balls" in the wizards

---

wizard/WizardMemoTextInput.qml
wizard/WizardPassword.qml

Removed yelly uppercase letters ("VERY") and added bold instead to both mnemonic seed box ("very") and password page ("Enter a strong password") for better overall emphasis. Changed "Enter a secure password" to "Enter a strong password" since it seems a better descriptor overall - i.e. a strong password makes the wallet secure.

Better use of emphasis in Wizard

---

wizard/WizardMain.qml
wizard/WizardOptions.qml

Settings are only saved on last wizard page. When opening wallet form file the wallet skips the last pages in wizard and therefore misses language, daemon_address and testnet settings. 
Fixes #381
and probably https://github.com/monero-project/monero-core/issues/246 (not tested)
This PR also makes testnet and daemon address settings persistent between wallets.

wizard: store settings before opening from file

---

LeftPanel.qml
MiddlePanel.qml
components/StandardDropdown.qml
main.qml
pages/Mining.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

Wa want to make it easy for people to mine

Add pool mining screen

---

.gitmodules
build.sh
get_libwallet_api.sh

This PR adds monero as a submodule. The submodule is linked to a specific commit and won't pull latest HEAD automatically. This will hopefully make testning easier when PR's are merged into monero that doesn't build on all platforms.
Fixes point 3 of https://github.com/monero-project/monero-core/issues/62

monero submodule

---

pages/Mining.qml

Simplified and clarified some of the terminology on the Mining page. The words "Solo miner" was used three times, when it only needed to be used once.

Improved text on Miner page

---

components/TickDelegate.qml

A mixin of 4 isn't really "low" privacy. If people want a higher mixin, that's great, and the HIGH term does convey that a mixin of 25 is higher privacy than the default setting. But the default setting should not convey that privacy is LOW. In fact, the default mixin is among the most private tx a person can send in all of cryptoland. A better term for default XMR privacy (mixin=4) is something like "normal" / "standard" / "typical" / "average" / "default". Of these "normal" seems the best for the newbie Monero user.

Change slider mixin=4 term from "low" to "normal"

---

components/PrivacyLevel.qml
components/PrivacyLevelSmall.qml

Currently the colors are Low/orange, Medium/yellow, and High/green. I understand orange being low, since it's the default color of Monero. High/dark-green makes sense since green has a feeling of "go", or of safety, good for a high privacy setting. But medium being yellow is awkward, since it looks like an alarming/warning color.
A better color for Medium would be the light green seen in the Receive bullet point (#AAFFBB) vs. the dark green/High color in the Settings bullet point. That way the mixin slider changes from orange to light green ("go/safe") to dark green (very "go/safe"), and the deeper the green the higher the conveyed sense of privacy.

Better medium mixin color

---

LeftPanel.qml

Right now Advanced has the same color bullet points as Receive. This differentiates it to #FFD781, the color already in Advanced > Mining.

Better bullet point color for Advanced tab

---

main.qml

Changed confirmations to confirmation(s) so the tool doesn't say "with 1 confirmations". Also added a period to the end of the sentence.

Clearer results for Verify Payment tool

---

linuxdeploy_helper.sh

Right now if these commands fail, the script still exits with status 0, so automation such as buildbot won't know there is a problem. For example:
https://build.getmonero.org/builders/monero-core-ubuntu-amd64-libc2.19/builds/28/steps/deploy/logs/stdio

exit script with appropriate status if these commands fail

---

linuxdeploy_helper.sh
utils.sh

Depending on the architecture, distribution, and where I installed QT from, these paths are different. Unless someone has a better idea, if we just allow them to be set like this I can make adjustments locally.

Allow some QT lib paths to be set in environment variables

---

build.sh
get_libwallet_api.sh

This adds an option to automatically merge required PR's from monero repo when building gui. 
Add `requires #xxxx` to last commit message. Where xxxx is the monero pull request ID. Repeat for multiple PR's.

Pull required monero PR's automatically

---

pages/Transfer.qml

Mimics the same design as Payment ID. Keep description of field in placeholder rather than above the field as how Description originally was.

Payment Description into placeholder

---

pages/Transfer.qml

The purpose of keeping "OR" in the button was to avoid people accidentally sending their entire account balance, ie. keeping "OR" helps the user realize the button is completely optional and not required for an XMR transaction.
However, "OR ALL" looks awkward as is, and the functionality is still intuitive if simplified to "ALL", so that is the purpose of this PR.

Simplified "OR ALL" button to "ALL"

---

pages/Mining.qml

Was running off the side of the page in compact view.
These `<br>` lines are not ideal. It makes the description halting and awkward. Is there any way we can make it so the text doesn't need one line per sentence, but instead automatically breaks depending on the wallet window width?

Shorter mining description for compact view

---

main.qml
pages/Transfer.qml

As per the discussion here:
https://www.reddit.com/r/Monero/comments/5pmz3f/maybe_a_good_idea_to_rename_mixin_in_the_code_to/
Good point by u/knaccc: "For mass adoption, people should not need to understand what a ring signature is, and then understand the mathematics of using different mixin levels, in order to feel comfortable sending a payment."
This change fits this desire well. The privacy slider is still titled "Privacy level", which even newbies can understand has something to do with increasing the privacy of the tx. But in parentheses the term will say "ring size", which is a more accurate term than the current term "mixin". Best of both worlds.

Terminology change: switch "mixin" with "ring size"

---

components/ProgressBar.qml
main.qml
pages/Settings.qml
pages/Transfer.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h
src/libwalletqt/WalletManager.cpp

Requires https://github.com/monero-project/monero/pull/1655
- Speeds up initial sync (on faster machines where UI was the bottleneck) and reduces the cpu load.
- asynchronous connection check. Should fix https://github.com/monero-project/monero-core/issues/172 and similar timeout stalls and make the GUI more responsive overall.

Init & sync improvements

---

translations/monero-core_de.ts

Error during build:
/usr/bin/lrelease -compress -nounfinished -removeidentical ../translations/monero-core_de.ts -qm /x/monero-core/build/release/bin/translations/monero-core_de.qm
lrelease error: Parse error at ../translations/monero-core_de.ts:500:59: Expected '#' or '[a-zA-Z]', but got '%'.
Appears to be a typo in german translation file. Removing character builds this stage OK

potential fix Parse error monero-core_de.ts:500:59:

---

monero-wallet-gui.pro

Fix for undefined reference including ldl. add -ldl to linux LIBS for Makefile.
/usr/bin/ld: /tmp/ccYIfntN.ltrans11.ltrans.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:388: release/bin/monero-wallet-gui] Error 1

Potential fix for undefined reference 'dlsym' linux

---

main.qml
pages/Transfer.qml

See this discussion: https://github.com/monero-project/monero/issues/1673
Ringsize is being used as a single compound word (instead of "ring size" - two words) which makes sense in the mixin vs. mix in sense of things.

Make "ringsize" one word

---

main.cpp
src/libwalletqt/Wallet.cpp

I've experienced crashes when switching wallets after syncing from scratch. Seems like the asynchronous close is calling the destructor twice on rare occasions. 
+ fixed the undefined builtwithscanner error.

Attempt to fix rare crash when switching wallets

---

src/daemon/DaemonManager.cpp

monerod fails to start with --detach flag on windows.

omit --detach flag on windows

---

monero-wallet-gui.pro

May seem petty, but it's a real political sticking-point in China
We're using the same 'Chinese' (mainland) flag for both traditional and simplified writing systems, so once someone writes a simplified translation file, we need to rename the translation files appropriately, and list them in the menu in their native Chinese names.

Remove reference to Taiwan from the codebase, replace with 'Traditional'

---

README.md
monero-wallet-gui.pro

Added some fixes for building the GUI on windows (through msys2-mingw32), since currently that doesn't work as the guide prescribes. I've added the fixes in a way, which shouldn't mess with build environments already customized and the build-bot.  Also changed the windows build guide in respect to the changes.

Windows-build and guide fixes

---

LeftPanel.qml
MiddlePanel.qml
pages/AddressBook.qml
pages/Receive.qml
pages/Settings.qml
pages/Sign.qml
pages/Transfer.qml
translations/monero-core_ar.ts
translations/monero-core_br.ts
translations/monero-core_de.ts
translations/monero-core_eo.ts
translations/monero-core_es.ts
translations/monero-core_fi.ts
translations/monero-core_fr.ts
translations/monero-core_hr.ts
translations/monero-core_id.ts
translations/monero-core_in.ts
translations/monero-core_it.ts
translations/monero-core_ja.ts
translations/monero-core_nl.ts
translations/monero-core_pl.ts
translations/monero-core_ru.ts
translations/monero-core_zh.ts

Fixes missing translations from LeftPanel.qml and MiddlePanel.qml. More missing translations needed to some files.
Updated the translation files with `lupdate -verbose monero-wallet-gui.pro` (the [log](https://paste.fedoraproject.org/paste/F3w4CBiNDIuzCccVZv5lKl5M1UNdIGYhyRLivL9gydE=))
Also updated the dutch translation.

Fixed missing translations and updated files

---

README.md

I had no problems building on OSX using homebrew using the latest version of Qt (v`5.8`).
Just wanted to update these build notes as brew is much easier than downloading from qt.io
Also added a heading so that it is clear this this the GUI project.

README - Updating Mac OSX Build notes and adding heading.

---

pages/Receive.qml

These changes were requested in #254. This removes the default payment ID value from the receive page. I also added a "clear" button next to the payment ID generate button. Let me know if the button commit should go in its own PR. I'm not familiar with how you guys manage this repo.
Also, I added a new button string which needs translation entries. Are the files updated by hand or with a script?

Remove default payment ID from receive page

---

wizard/WizardPassword.qml

Title was vertically next to "Note:" warning. Now all the lines have (mostly) equal vertical spacing, though at some point it might be good to switch the `<br>` code with a more accurate margin.

Better spacing for Wizard password warning

---

BasicPanel.qml
MiddlePanel.qml
components/AddressBookTable.qml
components/CheckBox.qml
components/DashboardTable.qml
components/DatePicker.qml
components/HistoryTable.qml
components/SearchInput.qml
components/TipItem.qml
components/TitleBar.qml
main.qml

The GUI currently is inconsistent with it's application of negative letter space, and I'm unsure why this styling was chosen. It seems only to only contribute illegibility. Whatever the case, some words currently utilize it and some do not, an inconsistently that leads to a more distracting and confusing design overall. Current state:
This PR removes negative letter spacing, making things look much better. Corrected state:
If we decide to reapply negative letter spacing at some point in the future, it'll be easier, since we can choose which elements can consistently have it, and which don't need it.

Remove negative letter spacing

---

get_libwallet_api.sh

cloning and trying to build without this does not work at least on mac osx

activate 'git submodule update'

---

pages/Transfer.qml

Right now the fees are structured Low (x1 fee), Default (x4 fee), Medium (x20 fee), and High (x166 fee). But this makes it look like the default fee is paying four times the regular fee (or, default is paying 4x the default), which is confusing.
This PR suggest lowering all fee multipliers by a factor of four. So Default is now just x1 fee. Low is x0.25 fee, Medium is x5 fee, and High is x41.5.

Simplify fee structure (divide all by 4)

---

components/AddressBookTable.qml
components/DashboardTable.qml
components/HistoryTable.qml
components/TableDropdown.qml

This is a small improvement to the context menu which is shown for each entry in the `AddressBookTable`.  Currently, there is an option "**Send to same destination**" which is unclear as it suggests some vague notion that the user has already sent XMR to this destination and would like to do so again.
This PR replaces the above message with "**Send to this address**", as the currently selected address will be inserted into the Send view as the recipient address.
Screenshot:
I found several other instances of this string and updated all for consistency.
Changes / suggestions welcome.

Address Book context menu : Send to this address

---

pages/Mining.qml

Adds checkbox for smart/background mining. Doesn't work on mac until https://github.com/monero-project/monero/pull/1936 is merged. 
Fixes #682

Enable smart mining

---

README.md

Mostly cleaned up some formatting for building the GUI, particularly normalized the steps so as each step doesn't end with different symbols (colon vs period vs nothing). Also edited the QT error workaround so its version matched the installation version.

Normalize build Instructions

---

wizard/WizardManageWalletUI.qml

Just adding space and a colon between the sentence "Your wallet is stored in" and the path that follows.  I added the space _outside_ of the translated string so that existing translations would not break.
Here is a screenshot demonstrating the issue:

Restore wallet: Adding space after 'Your wallet is stored in'

---

lang/languages.xml
translations/monero-core_ru.ts

This was copied over directly from #712 where @LvMsterfild had translated, but got stuck with git commands, revisions and squashing.
Only modifications were to revert nonsense translations like "Tip tekst test" that clearly are not real text and should not be "translated".
Note: I do not speak russian, but have reviewed these changes and done a sanity check using Google translate.

Russian translation

---

.gitmodules

When building `monero-core`, a lot of files are generated in the `monero` submodule.
This change prevents those generated files from being considered modified and cluttering up our commits.
Per https://git-scm.com/docs/gitmodules.html#gitmodules-all
> The submodule will never be considered modified (but will nonetheless show up in the output of status and commit when it has been staged).
My git-fu is still not very advanced... feel free to tell me this is a bad idea. :-)

Ignore unstaged files in 'monero' submodule by default.

---

translations/monero-core_pt-br.ts

Just an attempt to help the community. I fixed some typos, removed already translated `type=unfinished` and translated the remaining messages.

pt-br translations: Fixed typos, added translations, removed unfinished types

---

pages/AddressBook.qml
pages/History.qml

Most of these are "Tip tekst test" and unfortunately this is adding noise to all translation files.
I am not sure why these were added, but they are not used in the UI and most are nonsense anyway.

Removing unused tipText strings which clutter up translations.

---

LeftPanel.qml
translations/monero-core.ts
translations/monero-core_ar.ts
translations/monero-core_de.ts
translations/monero-core_eo.ts
translations/monero-core_es.ts
translations/monero-core_fi.ts
translations/monero-core_fr.ts
translations/monero-core_hi.ts
translations/monero-core_hr.ts
translations/monero-core_id.ts
translations/monero-core_it.ts
translations/monero-core_ja.ts
translations/monero-core_nl.ts
translations/monero-core_pl.ts
translations/monero-core_pt-br.ts
translations/monero-core_ru.ts
translations/monero-core_sv.ts
translations/monero-core_zh-cn.ts
translations/monero-core_zh-tw.ts

Following up on #779, this refresh will remove nonsense like _"Tip tekst test"_ from translation files and pick up any new translations needed.
**Updated on 2017-07-13:**
1. The first commit updates all files via `lupdate`.
2. The second commit removes additional nonsense "Test tip" string (pointed out by @ProkhorZ) and uses the `-no-obsolete` parameter to clean out unused translations.

Translations refresh & cleanup

---

translations/monero-core_nl.ts

Updated Dutch translations
Changes:
- Translated some new strings.
- Removed spaces in compound nouns.
- Made the form of address consistently formal (je->u).
- Improved grammar and style in longer text.
- Removed overly formal words like 'gelieve' and 'alstublieft'.
- For the verb Sign, changed 'Signeren' to 'Ondertekenen'.

Farmer's rebase of PR #815

---

pages/Sign.qml

Fixes the positioning of `verifySignatureLine` LineEdit. See screenshot below. Fixes #767

Fix verifySignatureLine positioning

---

pages/History.qml

When collapsing the transaction filter in the transaction history part of the searchbox is still visible. This PR fixes it.

Fix collapsing of transaction filter

---

monero-wallet-gui.pro

Otherwise linking fails with undefined symbols `rl_*` (at least on Arch Linux x86_64).
Probably also needed for iOS case below (near -lepee), but I can't test iOS, so not adding that to this PR.

pro: add libreadline to link line for Linux

---

README.md

The package has recently been accepted into the repository, voidlinux/void-packages@4b6fa3867064d3f10b552392414518b00b6eff92 .

README: Add package installation instructions for Void Linux

---

build.sh

Not every system has bash as default shell. Running this script in zsh environment leads to build failure.

Run get_libwallet_api.sh using its own shebang

---

windeploy_helper.sh

See #900. Wasn't included in v0.11.0 release with no apparent notice or ill-effects. If someone thinks this is still needed, please comment. We seemed to be including this file which is written, licensed and built by another project. No reply from @mbg033 who first included it.
I will open an issue to examine the rest of the $FILES in windeployhelper.sh

don't copy libjasper-1.dll

---

src/libwalletqt/Wallet.cpp

Wallet needs to be stored before closed after change in https://github.com/monero-project/monero/pull/2289

Store cache on exit

---

MiddlePanel.qml
components/MenuButton.qml

Addresses 3 things:
- The menu buttons are quite large in height and font size. I've decreased them to 48px and 16px respectively
- Menu button collapse animation decreased to `200ms` and changed easing to `Easing.OutCubic`
- Added easing to page/panel switching, again `Easing.OutCubic`
Benefits:
- Less height needed to draw the menu
- Less 'in your face' buttons
- Smoother animations for the menu and panel selection
Can provide .gif, but couldnt get `peek` to work

GUI responsiveness / menu clutter

---

MiddlePanel.qml
main.qml
pages/TxKey.qml
src/libwalletqt/Wallet.cpp

Fixed stupid mistype of function names.
Also `getTxProof` handles failure cases with C++ exception instead of additional string arg.

Bugfix with tx proof + update

---

README.md

Recently the GUI repo had its name changed from monero-core to monero-gui. This PR updates the build instructions and elsewhere with the new repo name and link.
This PR also seeks to put the heading capitalization policy inline with the main Monero readme. Capitalizing every single word in a heading begins to feel redundant and cumbersome when headings become long (and many are indeed quite long). A much better practice is capitalizing just the initial word. See: https://github.com/monero-project/monero/pull/2881

Switch Core with GUI in README.md, fix headings

---

components/PasswordDialog.qml

Password input now resets on failed input. Previously it kept the invalid password on failure.
Simple change that fixes #865 as empties the contents of the password dialog on open. 
When the password is invalid it reopens the dialog https://github.com/monero-project/monero-gui/blob/d9d2050f2924322ff6f2895addcb6961a49132f9/main.qml#L351 which at this point it didn't clear the previous contents but now the logic does so opening starts the dialog off fresh for user input.

Password input: reset on failed input

---

LeftPanel.qml

I took a look at the associated issue #887 where the user did not realize they were on a view only wallet and could not spend money directly.
With view only wallets you can create a transaction which you can then sign on a normal wallet and later submit via the view only wallet. It does this so that you can keep your main wallet offline if you want and just use it for signing transactions generated by the view wallet. 
I think the best call here then is just a label like the testnet one that appears if you're on the testnet under the Monero branding on the top left.
The changes were pretty straightforward to add one. I've included photos of the GUI here for mainnet, mainnet view only, testnet, testnet view only to see the changes more easily.
Note: this branch currently fails to build by …

Left panel: add view only wallet label

---

translations/monero-core_eo.ts

This PR follows up on #794
I ran the following command to update line numbers and remove obsolete translations:
lupdate -no-obsolete -pro monero-wallet-gui.pro -ts translations/monero-core_eo.ts
Then I manually fixed a number of placeholder issues, translations marked as `type="unfinished"`, etc.

Esperanto fixes

---

components/HistoryTable.qml
components/HistoryTableMobile.qml

Small change that fixes #898 by showing failed when a transaction in the history has that status. Previously it showed pending in that state.
I was able to reproduce the bug by taking my view only wallet, creating a transaction, signing it on my regular wallet, and then attempting to submit the transaction twice via the view only wallet (if looking to testing it / reproduce the original bug).

History: Properly label failed transactions

---

pages/Receive.qml

Simple change to fix #904 where the QR code was incorrectly updating for invalid payment IDs. Logic just checks whether or not the payment ID is valid prior to including it as part of the QR code now. 
I've attached a few screenshots which show that the QR code only updates now when there is a valid payment id as well.

Receive page: QR code bug fix for invalid payment ids

---

translations/monero-core_nl.ts

Dutch explanation:
https://www.beterspellen.nl/website/index.php?pag=106
has to do with noun and adjective words.
Fixing Dutch translation spelling mistake

Fixing Dutch translation spelling mistake

---

pages/Receive.qml

Pairs with #1014 by adding a graphical notice to the user of their payment id being invalid. A component to fix #904

Update error field of payment id text field

---

main.cpp

Fixes an issue introduced by https://github.com/monero-project/monero/pull/2860

Call Monero::Utils::onStartup in main.cpp (requires #2952)

---

installers/windows/Monero.iss

With the help of the flag `ignoreversion` for `[Files]` section entries in the InnoSetup installer script the Windows installer now **always** replaces existing files with the corresponding files in the installer, regardless of file dates, version info in .exe headers, or file content, when updating / upgrading an existing installation.
This "hard replace" of every file is much more robust than the previous behaviour using flag `comparetimestamp`, and the only small downside seems to be somewhat longer installer execution times when upgrading.
Of course wallet files and any downloaded blockchain are excluded from this replacing, as such files are not part of the installer and are in other directories than the installed files anyway.
Note that `ignoreversion` would be very dangerous to use …

Windows installer: Switch from 'comparetimestamp' to 'ignoreversion'

---

build.sh

This makes `build.sh` work on Fedora 27. Specifically this fixes:
* Fedora uses the binary name `qmake-qt5`
* Not all hosts have an `lsb_release` command
* Disable libunwind on Fedora (like Ubuntu)
With these changes `build.sh` can successfully compile a `monero-wallet-gui` executable. That executable immediately segfaults for me, but that's a pull request for another day.

Make build.sh work on Fedora

---

pages/Receive.qml
pages/Sign.qml
pages/Transfer.qml
translations/monero-core.ts

I have modified several particularly noisy chunks of UI text to remove html/css formatting which was cluttering up translation files.  This should help translators to focus on their job while removing distractions and potential sources of broken html/css UI code.
The PR is broken into 3 commits to simplify review:
1. First commit was just the result from running `lupdate -no-obsolete -pro monero-wallet-gui.pro -ts translations/monero-core.ts` (ie no code changes).
2. Second is is the only code change where I isolate the strings from the html/css code.
3. Ran `lupdate` again to show the cleaned up result.
Notes:
* There is very minor visual changes to fonts based on the simplification I made.  I can provide screen-cap comparison if needed.
* I can squash once someone (@erciccione ?) has …

Cleanup html/css to simplify translation

---

translations/monero-core_nl.ts

Some typos, has to be 'uw' instead of 'u'. Like 'your' instead of 'you'.
First time on github, let me know this is right way to do this ?

Typo fixes gui nl (dutch) translation

---

pages/Settings.qml

Resolves #655  by adding the wallet name to the top of the left panel like so.

add wallet name to left panel

---

translations/monero-core.ts
translations/monero-core_ar.ts
translations/monero-core_cs.ts
translations/monero-core_da.ts
translations/monero-core_de.ts
translations/monero-core_eo.ts
translations/monero-core_es.ts
translations/monero-core_fi.ts
translations/monero-core_fr.ts
translations/monero-core_he.ts
translations/monero-core_hi.ts
translations/monero-core_hr.ts
translations/monero-core_id.ts
translations/monero-core_it.ts
translations/monero-core_ja.ts
translations/monero-core_ko.ts
translations/monero-core_nl.ts
translations/monero-core_pl.ts
translations/monero-core_pt-br.ts
translations/monero-core_ro.ts
translations/monero-core_ru.ts
translations/monero-core_sk.ts
translations/monero-core_sv.ts
translations/monero-core_zh-cn.ts
translations/monero-core_zh-tw.ts

Refresh translations since #981 has been merged.
Command: `lupdate -no-obsolete -pro monero-wallet-gui.pro`
(also picked up a number of additional strings which were added in the last few months)
I added a second commit which contains manual fixes for a few situations where `lupdate` got confused about numbers.
Example:
```
(%1/10 次確認) {1/%2 ?}
```
Translations system was confused that we now have `%1` and `%2` parameters.  So I fixed as:
```
(%1/%2 次確認)
```
@erciccione - Care to have a look?

Refresh translations

---

src/libwalletqt/UnsignedTransaction.h

Since `UnsignedTransaction::Priority` enum has been removed from Monero Core Wallet API, removing it from *monero-gui* as well.
Conflicts with : https://github.com/monero-project/monero-gui/pull/1098

UnsignedTransaction: Removing the Priority enum accordingly to libwalletapi update

---

main.qml
pages/TxKey.qml

> startsWith(searchString [, position ]) // ECMAScript 6: Added in Qt 5.8
http://doc.qt.io/qt-5/qtqml-javascript-functionlist.html
On some Linux systems like Ubuntu and Debian, the installed Qt version is below 5.8 where startsWith is unsupported.

startsWith is unsupported for Qt < 5.8, use indexOf instead

---

wizard/WizardManageWalletUI.qml
wizard/WizardMemoTextInput.qml

This can be useful when restoring from a seed in the old format (EnglishOld without checksum).

Wizard: allow seed without checksum

---

components/HistoryTable.qml
components/TextBlock.qml

This branch provides a workaround for the bug that caused #1003. The bug we're experiencing can be found on QT's bug tracker as [QTBUG-50587](https://bugreports.qt.io/browse/QTBUG-50587). 
The [persistentSelection](http://doc.qt.io/qt-5/qml-qtquick-textedit.html#persistentSelection-prop) property (which is defaulted to false in QT5) is supposed to handle deselecting text upon losing focus of the component but this breaks for `readOnly: true` textEdit components allowing multiple to be selected in tandem. 
The temporary fix (until QT5 fixes the bug on their end) is simply to listen to the `onFocusChanged` event and if the focus has been lost deselect  the component. 
We also use readOnly TextEdit components for the history panel. Originally I considered making a …

TextBlock: Fix multi select bug

---

main.qml

This pull request fixes an issue (fixes #1002) where the left panel incorrectly had the "Settings" section selected when the "Seeds & Keys" section was open.
This issue was caused by the logic that looks for hotkeys for selection of the left panel. During password dialog keydown events it was causing the left panel to select the "Settings" section as the `middlePanel.state` was set to "Settings" while we wait for a password input.
I've adjusted the left panel hotkey logic to ignore input when the leftPanel is disabled as it doesn't make sense to look for hotkeys then which fixes this issue.
This [logic](https://github.com/Timo614/monero-gui/blob/9cdfad35120fd0ae43f2fccf10bc43835c79eceb/main.qml#L88) shows the method in question which is used to handle hot keys for adjusting which left …

Left Panel: seeds and keys not selected when open

---

main.qml
pages/Mining.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

Fixes #939 by using wallet2_api's `isAddressLocal` method which confirms whether the address passed in is a local address or not. It calls `is_local_address` internally which the associated issue was referencing. 
I tested this by connecting to a remote node and confirmed that I saw the mining warnings that are not visible for local nodes. I also confirmed that when using the remote connect logic pointing to `localhost` or `127.0.0.1` it was still treated as a local node from a warning perspective.
(Note: if testing it looks like if you have a node up in the default port 18081 for mainnet or 28082 for testnet the remote node is ignored so I tested the local nodes treated as remote by running them on different ports)

Use wallet2_api isAddressLocal utils method for isDaemonLocal check

---

src/libwalletqt/Wallet.cpp

In MacOS it is not usual to modify anything inside an application. If the user that runs the application doesn't have writing permissions the log will not be saved.
This modifies the path to store them in MacOS' standard location for application logs.

Store wallet log in ~/Library/Logs/ in MacOS

---

monero-wallet-gui.pro

I'm not familiar with these flags, though.

Mac build: relro, now and noexecstack are unsupported for Mac

---

monero-wallet-gui.pro

Seems like the wallet API's dependency on readline was removed by https://github.com/monero-project/monero/pull/2736

build: remove readline from dependencies

---

monero-wallet-gui.pro
wizard/WizardMain.qml

This PR is the second part of a duo of PR's, the Monero GUI one - the one for Monero is [PR #3313](https://github.com/monero-project/monero/pull/3313).
Those 2 PR's fix a long-standing problem with names for files and paths on Windows: Wallets on Windows are not processed properly when either the wallet file names or the names of the containing directories contain any non-ASCII characters. See the following issues: [Monero GUI issue #199](https://github.com/monero-project/monero-gui/issues/199), [Monero GUI issue #1390](https://github.com/monero-project/monero/issues/1390) (late 2016), [Monero issue #938](https://github.com/monero-project/monero/issues/938), and possibly others.
Almost all of the necessary changes are in Monero code. For details and more info about the technical solution …

UTF-8 support for filenames and paths under Windows

---

main.cpp
qml.qrc

use setWindowIcon for linux. AFAIK this isn't needed in mac/win where the app icon is embedded in the application. 
Before:
After:
It is up to your desktop enviroment where those changes are reflected. Targets are: taskbar, window switcher (alt+tab) and window decoration

add window icon for linux

---

translations/monero-core_es.ts

Update non translated strings and remove commonly unneeded expressions in Spanish translations such as `Por favor,` and similar ones.

Update Spanish translations

---

windeploy_helper.sh

The GUI exe for Windows, built with the latest sources, and with a MSYS2 build environment updated to latest versions of all packages, needs some more DLLs than until now: `libssp-0.dll` (for the recently-introduced stack protection), `libpcre2-16-0.dll` (something about regular expressions?), and 5 ICU libraries (a direct consequence of my own [PR #1141](https://github.com/monero-project/monero-gui/pull/1141).
I updated `windeploy_helper.sh` to copy all those files.
Please note: If with these changes the script does not find the ICU libraries your MSYS2 environment is not updated to the latest version of ICU. Background info about the library rename in question is [here](https://github.com/monero-project/monero/pull/3375).

Additional DLLs in 'windeploy_helper.sh': ICU, stack protection, regexp

---

pages/Transfer.qml

While creating/sending a transaction in the GUI, it should warn with a pop-up box about the inability to send a transaction due to insufficient (unlocked) funds.
However, on some of my builds I do not receive these warnings/pop-ups and the GUI just crashes.
This PR could be merged if other people experience this. The fix is to render the 'Send' button inactive on insufficient unlocked balance.

Disable send button on insufficient balance

---

components/PasswordDialog.qml

```
< *> One problem I find when trying to use it, is that the password dialog doesn't display the wallet's file name at the app launch.
< *> This can be confusing, especially if you forget which wallet file you used previously.
```

Bring back wallet name at the password dialog

---

monero-wallet-gui.pro

Don't merge this unless you are prepared to break the old behavior. 
I'm told that people manually building boost libs on windows have the filenames ending in -s. 
This change makes the gui link if using the default boost libs from msys2. 
It might be more ideal to allow either names, if someone wants to do that or tell me how.

link to boost lib filenames from msys2 package

---

monero-wallet-gui.pro

This fixes unresolved dependencies when linking monero-wallet-gui if libwallet_merged was built with HW device support.

Add libpcsclite to link line if libwallet_merged is linked against it

---

main.qml
pages/Settings.qml

Fixes #1207
The GUI reports blockchain size is ~15GB and ~30GB, in reality we're at 50GB.

Fixes blockchain size warnings

---

components/ProgressBar.qml

Previously, `progressLevel` was always set to zero when `currentBlock / targetBlock < 0.5` because `100*(currentBlock / targetBlock).toFixed(0)` is evaluated as `100*((currentBlock / targetBlock).toFixed(0)) = 100*0 = 0`.

ProgressBar: fix conversion to percentage

---

main.cpp
pages/Settings.qml

Display Qt runtime version on settings page to help debug issues like #1223, which can be related to upstream Qt bugs.
In static builds qt runtime version should match qt compile time version, so I think we don't need to include both.
Please review the translation stuff, I'm not sure if the string is well formed.

Add Qt Runtime version to settings page

---

pages/Settings.qml

IMO the current way of using grayed disabled buttons to indicate the selected mode is a bit unintuitive.

Settings: use checkbox instead of button for daemon mode switching

---

components/PrivacyLevel.qml
components/PrivacyLevelSmall.qml
pages/Transfer.qml

Making the privacy level bar go from orange, to light green, to dark green gives the impression (especially to less knowledgable users) that a higher ring size equals better privacy, which isn't always the case. To avoid giving that impression this PR makes the privacy level bar solid orange, regardless of selected ring size, and changes the wording of "privacy level (ring size x)" to just "ring size"
[screenshot](https://imgur.com/AvSir0i)

single colour privacy level bar

---

LeftPanel.qml
components/NetworkStatusItem.qml
components/ProgressBar.qml

Temporary fix to #1288 that works in the new black theme. Since the leftpanel menu doesn't have an explicit height and the status elements are on top of the menu I changed two things:
1. statusbar elements (networkStatus and progressBars) have black background
2. made the flickable region dynamic to let us scroll to the menu items hidden by statusbar

[Release]: Leftpanel overlay fix

---

components/InputMulti.qml
pages/Transfer.qml

The way the labelbutton was being used was stopping the "resolve" button from showing up when an OpenAlias address was used. Once you got it to show up it would end up replacing the "Address Book" label so this PR changes it to it's own standard button. The regex filter also has to allow '.' and '@' characters otherwise the user can't even enter a proper OpenAlias address

fix OpenAlias resolve

---

TranslationManager.cpp
monero-wallet-gui.pro

This PR allows embedding the translation files in the binary instead of fetching them in the *translations* directory.
If a translation file exists in a *translations* directory located in the same directory as the binary, it is used in priority (this can be useful when working on translations as you don't have to recompile the whole program all the time), and if no such file is found the embedded translation file is used.
I have only tested this on GNU/Linux. If someone has a Mac or Windows machine and the time to try this, please test and see if some unexpected issues appear.

Embed the translation files in the monero-wallet-gui binary

---

components/TitleBar.qml

Hi all,
I noticed that the "Help" button in the custom title bar is no longer functional.
This appears to be by design, as the functionality was largely removed in this commit: https://github.com/monero-project/monero-gui/commit/b35d60db2d8b7508127e8d365d22a82d58bd9dc6
Since the button is a legacy item, I presume it is taking up space and should be removed. This commit performs that.

Removing legacy whatis (?) button from titlebar

---

LeftPanel.qml
components/NetworkStatusItem.qml
components/ProgressBar.qml

Temporary fix to #1288 that works in the new black theme. Since the leftpanel menu doesn't have an explicit height and the status elements are on top of the menu I changed two things:
1. statusbar elements (networkStatus and progressBars) have black background
2. made the flickable region dynamic to let us scroll to the menu items hidden by statusbar

Leftpanel overlay fix

---

components/DaemonConsole.qml
components/NewPasswordDialog.qml
components/PasswordDialog.qml
components/TitleBar.qml
js/Utils.js
js/Windows.js
main.qml
pages/Settings.qml
qml.qrc

Fixes #1278 
- Makes the `TitleBar` component more modular
- Move the black overlay (that covers the main window) to `main.qml`, visible when another window is active
- Move Javascript code related to dialogs/windows to `js/Windows.js`
- Dynamically set Window flags based off `persistentSettings.customDecorations` from this file
- Timestamped output (via `Utils.js`)
- Colors

Restyle daemon dialog window

---

pages/AddressBook.qml
pages/Sign.qml
pages/Transfer.qml

Fixes #1332
`4.. / 8..` placeholder for address input fields. Changed on the following pages:
- Transer
- Address Book
- Sign/Verify

Change input address placeholder from '4...' to '4.. / 8..'

---

main.cpp

- refactor some platform dependant code. At least for me is easier to read this way.
- add isDesktop, to differenciate between desktops OSes and mobile OSes. It is useful mainly because android is recognized by qt as linux too.
- add a initial cmdline parser. Move some qDebug  and force style fusion for desktop platforms so don't pollute the output of the parser. It will be useful in the future :smiley: 
- move monero stuff after app constructor + cmdline parser. (We don't want to initialize anything if we're running, for example monero-wallet-gui --version)
- force platform xcb on desktop linux, because on newer systems qt will try to use platform wayland and this isn't supported by our building system yet.
- fixed reported height and width, because it was right only when height > width.

main.cpp misc changes

---

lang/languages.xml

1. Change 'Turkish' to 'Türkçe' in the opening screen. I don't speak Turkish, but the language name is pretty obvious.
2. Change wallet_language for Turkish to English, because there's actually not a mnemonics word list in Turkish at the moment, although it's listed here in the comment above.
3. Update that list of available seed languages. Source: https://github.com/monero-project/monero/blob/master/src/mnemonics/electrum-words.cpp
4. Change wallet_language for Catalan to 'English', because there's no Catalan word list. Personally, I think Spanish as the seed language would be more useful to speakers of Catalan, but that's a political decision which requires discussion.

Name of Turkish language and list of languages

---

pages/Settings.qml
pages/Transfer.qml

After commit #1161 testnet flag was removed and nettype was introduced because of the stagenet flag. This changes the remaining instances of that to nettype.

Fix use of persistentSettings.testnet to nettype

---

share/Info.plist

fixes a typo that makes the file invalid and replaces the toolbar app name (monero-wallet-gui => Monero GUI)

[osx]: fix typo in Info.plist & replace toolbar app name

---

pages/Mining.qml

I think most people know that your node needs to be fully sync'd before you can start mining but if somebody new doesn't know that then they would probably be confused when they open the wallet and try to start mining but just get a non-descript "Error starting mining" message. This PR adds a red label similiar to the "only avaliable for local daemons" label that will be displayed if the wallet is connected to a local daemon but it is not completely sync'd with the network

warning label in mining page when daemon is not fully syncd

---

filter.cpp
filter.h
main.qml

1. Fix ctrl+tab behaviour:
ctrl+tab behaviour is switching between pages in certain order:
`transfer->receive->txKey->sharedRingDB->history->addressBook->sign->settings`
This looks random on the gui because how those pages are placed in leftpanel menu.
I changed 'ctrl+tab behaviour to switch pages in this order: 
`transfer->addressbook->receive->history->mining->txkey->sharedRingDB->sign->settings`
I added mining page to the switchable pages but leave the keys page out because it asks for a password and somewhat breaks the workflow.
2. Fix ctrl+shift+tab behaviour (ctrl+tab reverse order)

[shortcuts]: ctrl+tab switches pages forward | ctrl+shift+tab switch pages backward (same order as leftpanel)

---

translations/monero-core_it.ts

With reference to #1377, I kindly ask @serhack and @erciccione to review my work.
A clue: I did not just translate the "unfinished" strings but also fixed the terminology of the whole file according to the [Italian Glossary](https://taiga.getmonero.org/project/erciccione-monero-localization/wiki/italian-terminology) on Taiga.
See [Taiga task](https://taiga.getmonero.org/project/erciccione-monero-localization/task/267), updated to "Ready for Test".
Arrivederci!
hrumag

[Update] Italian Translation for GUI v0.12.1

---

translations/monero-core_pl.ts

Updated Polish translation for the upcoming v0.12.1 release as mentioned in #1377.
If you want to review the translations, you can start with ctrl+f "blackball". I used "Zablokowany" for "Blackballed" and "Odblokowany" for "Unblackballed". Blackballing probably refers to [this](https://lab.getmonero.org/pubs/MRL-0001.pdf) paper (as mentioned by **xmrscott**). You can ctrl+f "marble" in the paper for more info. Basically blackballing means not allowing an output to be used in ring signature. Maybe someone has a better translation. Imo, even in English blackballing is a bad phrase. I'd just use Block/Unblock or Blacklist/Unblacklist.
Also, I don't feel that my translations with "heights" are optimal. So you can ctrl+f "height" as well. E.g. "restore height", "wallet creation height", etc.

Updated Polish Monero GUI translation for v0.12.1

---

pages/Receive.qml
pages/Transfer.qml

Commas in the amount supplied by the user (eg 1,000.02) will produce an invalid uri which results in a QR code that can not be properly parsed. To fix that this PR introduces a regex filter before the amount is added to the uri used by the QR code. (eg the user gives 1,000.02 but it will go in the uri as 1000.02 to avoid an invalid uri)

filter qr code amount

---

README.md

Add a note about obsolete debian distros (ubuntu 16.04 derivates)
Add a note about how-to build on those distros (linking to qt wiki)
Update qt packages for ubuntu 17.10+
Put the steps in the same order as other platforms
Fixes #1405
Fixes #1420 (see comment)

update instructions for debian based distros

---

monero-wallet-gui.pro

This fixes monero-wallet-gui linking error in MSYS2 since PC/SC hw device support was added to Windows builds

Add libwinscard to link line on Windows

---

main.cpp

Changing the application name caused wallets created prior to v0.12 to "forget" their config file
@dEBRUYNE-1

[Release] Change application name back to monero-core (revert 28fb9fa)

---

main.cpp

Changing the application name caused wallets created prior to v0.12 to "forget" their config file

Change application name back to monero-core (revert 28fb9fa)

---

main.qml
pages/Settings.qml

currently we are checking daemon status each time we go to settings page (when local daemon is selected). This causes a hang of a few seconds (it depends on monerod's workload). 
This is a proposal to remove this check and rely on  "onWalletConnectionStatusChanged", as we do for leftpanel's network status items.
I did check the behaviour of this patch against a local daemon (started both inside and outside the gui) and it seems to work fine for me. More testing would be required and reviews apreciated because this might be some stupid PR.

Fix for frozen settings page

---

components/CheckBox2.qml
wizard/WizardOptions.qml

Most users don't need to worry about  testnet/stagenet so they are moved to an "Advanced Options" tab. Under this tab a "Mainnet" button is also added along side the other nettypes to address #1436

add explicit mainnet button and move nettypes to advanced options

---

wizard/WizardManageWalletUI.qml

Allow restoring a wallet from only the secret spend key by deterministically generating the view key. Requires monero-project/monero#3829

allow restoring from only spendkey

---

pages/Keys.qml

I don't like the current way where the entire text including all the secret/public view/spend keys gets copied to clipboard. Quite often the user only needs to copy the view secret key, which means that the user would need to paste this text somewhere and then make the next selection therein. This pasting operation can be dangerous when e.g. the user pasted it onto an email client and forgot to delete the draft (or even send it to someone).

Keys: allow keys to be copied separately

---

get_libwallet_api.sh

Fixed a bug that is causing constant libwallet rebuilding, even if it already exists.  
This happens because `return` instruction in get_libwallet_api.sh fails to execute and thus doesn't interrupt get_libwallet_api.sh execution.  
Have to use `exit` instead.
```bash
latest libwallet (06b0f9e8) is already built. Remove monero/lib/libwallet_merged.a to force rebuild
./get_libwallet_api.sh: line 78: return: can only `return' from a function or sourced script
Building libwallet release
```

build: use 'exit' instead of 'return' in get_libwallet_api.sh

---

installers/windows/Monero.iss
installers/windows/README.md
installers/windows/ReadMe.htm

Based on the contents of the official download file `monero-gui-win-x64-v0.12.3.0.zip` as released earlier today.
Mostly trivial adjustments to new release number, time passed, and some changes in the files to install.
With the confusion about the application name ("gui" versus "core") caused by 0.12.2.0 behind us, the installer can safely write any special blockchain location to the `monero-core` registry key where the GUI wallet will pick it up.
As an improvement, in the case of an *update* where the user could have modified the blockchain location in the GUI wallet already installed, the installer now picks up that location from the registry (instead of re-using stale data i.e. what the user said in the last installer run).

Windows installer: Updates for 0.12.3.0

---

README.md

`QT_SELECT=5` is still required on Debian 9 and it also doesn't harm on any other Linux system.

Fix build instructions for Linux

---

main.qml

Handle maximizing of the window just like any other application. Currently maximizing shows the wallet in fullscreen which also hides the taskbar.

Correctly maximize window

---

translations/monero-core_uk.ts

Pinging @TheFuzzStone @LvMsterfild for verification
The file was called monero-core_ua.ts and it contained the attribute language="ua_UA", but the language code for Ukrainian is "uk" (UA being the country code). This must have been a typo, am I right?
NB. the file lang/languages.xml was already correct which supports the typo thesis:

Corrected language code for Ukrainian and renamed localized file

---

translations/monero-core_es.ts

Changed the word "mnemotécnica" to "mnemónica" according to the discussion made in [line 39 of _i18n/es/resources/user-guides/restore_account.md - Translation of user-guides to spanish #799](https://github.com/monero-project/monero-site/pull/799/files/883b4f971c333743266153bfe944effa1939494f#diff-cab283037a954bf0715f46d6bbe893c9R39).
Fixed grammatical structure on line 2379 and updated missing translations.

Updated Spanish Translation

---

translations/monero-core_sv.ts

Mining should be translated to Utvinning according to
discussions on tp-sv@listor.tp-sv.se since it is already
an established term used in many Bitcoin projects.
And, if another term should be used Myntning was sugested
but had to stand back for the established term Utvinning.

Fix some swedish translations

---

components/LineEdit.qml
pages/Transfer.qml

[From Reddit](https://www.reddit.com/r/Monero/comments/9ap96g/gui_v01230_cli_v01230_both_with_direct_ledger/e5d40gb/):
> I have a complaint about the GUI xmr client, hope this is an appropriate place to comment this. I just tried to send a smaller amount of monero .2 xmr. When you type in .2 only 2 xmr fills in, the period does not fill in and I almost didn't realize. You have to type zero first to send less then 1, 0.2, the first char has to be a number not a period. Can this be changed to either accept the period first, or if a period is pressed to fill in 0. before it. If I didn't notice I could have sent 2 xmr instead of .2.
I changed the regex to support amounts that begin with a period, however, the actual validation that checks the amount will not let you create a transaction with …

Prevent accidental off-by-one decimal point transfers

---

linuxdeploy_helper.sh

Allows arguments (`-h`, `-l`) to be passed to `start-gui.sh`, otherwise the log file location cannot be specified when using the script.

Allow arguments to be passed to `start-gui.sh`

---

translations/monero-core_es.ts

I've translated the missing lines of the gui file for the Spanish language, and also made a review of the already translated lines, all with Linguist QT. Everything seems to be OK but I haven't compiled the GUI since I read that there has been some problems with that.
Thanks to @lh1008 and @erciccione for the support, if you want to review the commit you're more than welcome, but I took my time checking everything so there won't be many mistakes :)

Translation and corrections of monero-core_es

---

monero-wallet-gui.pro

In preparation of 0.13; linking libsodium, which is required since https://github.com/monero-project/monero/pull/3999
This PR is similiar to #1540 but includes more platforms.
Closes #1540

Linking libsodium

---

pages/Transfer.qml

In preparation of 0.13; Qt 5.7 does not support `startsWith()`, replacing with `indexOf()`.

Replace string.startsWith() with string.indexOf()

---

README.md

Monero repo have added `mingw-w64-x86_64-hidapi` in [MSYS2 Mingw64 build instruction](https://github.com/monero-project/monero/commit/0656050f76c8aa9cd8845b0ddcc1df3f3fa378c0). So update here as well.

README: update MSYS2 dependencies for Ledger

---

monero-wallet-gui.pro
windeploy_helper.sh

Required to compile 0.13 for Windows.

[0.13] Linking crypt32 and libhidapi for Windows builds

---

monero-wallet-gui.pro

If monero-0.13.0.2 is build with smartcard support, monero-gui should be build with hidapi rather than pcsclite.

Fix build with smartcard

---

LeftPanel.qml

fixed: networkStatus overlaps menu, padding

---

components/RemoteNodeEdit.qml

Previously, these were multiline editing (for some reason I'm not sure,
perhaps you can have multiple remote nodes?)
I tried various workarounds, but the simplest was to change them to
simply LineEdit (like username/password) and now my bug is fixed.
Fixes #1688

Fix daemon host/port setting to allow tab switching

---

translations/monero-core_sv.ts

When I audited the GUI i found some Swedish translations that were not optimal. 
* Layout was translated as Layout in Swedish, which is not really optimal but works. However, since it really is not about Layout, I changed the Swedish translation to "Utseende" since that better fits the Swedish language and what the page is really about. 
* Sweep Unmixable is a strange sentence to start with, but it was translated to "Svep upp omixbara" which feels like a word by word translation. I interpret the word "Sweep" here as the metaphor where you are sweeping the floor, so you are basically cleaning up the unmixables. So I have adjusted the swedish translation to better fit this metaphor. 
* Also I have changed a string on the Settings Info page to make it more consistent. 
@freminik @ordtrogen …

Minor adjustments to the Swedish translation

---

wizard/WizardManageWalletUI.qml

Hide the button if we can't scan the code anyway (scanner/camera is disabled)

wizard: optionally hide restore 'From QR Code' btn

---

README.md

Without the qml-module-qtquick-templates2 package after building the binaries and attempting to run them you'll see errors like this. After installing the package I was able to run the GUI just fine. This package appears to be in Ubuntu as well so I'm adding it under there.
```
user@host:~/Wallets/monero$ ./monero-wallet-gui
2018-10-28 16:11:18,023 INFO  [default] Page size: 4096
2018-10-28 16:11:19.064     7536ddfb77c0        WARN    frontend        src/wallet/api/wallet.cpp:367   app startd (log: /home/user/monero-wallet-gui.log)
2018-10-28 16:11:19.065     7536ddfb77c0        WARN    frontend        src/wallet/api/wallet.cpp:367   Qt:5.7.1 | screen: 1600x900 - dpi: 96.063 - ratio:0.750492
2018-10-28 16:11:19.382     7536ddfb77c0        WARN    frontend …
```

Debian 9 dependency

---

installers/windows/Monero.iss
installers/windows/README.md
installers/windows/ReadMe.htm

Some finishing touches in addition to the changes for 0.13.0.4 already merged as commit #1680:
From `monero-blockchain-blackball.exe` to `monero-blockchain-mark-spent-outputs.exe`, and a `--log-file` parameter for the GUI wallet shortcut / icon to force the log file alongside the .exe (which currently is not written there by default because of an unsolved issue in the GUI wallet).

[0.13] Windows Installer: Update for Beryllium Bullet 0.13.0.4, take two

---

translations/monero-core_fi.ts

The original word was translated as "public" instead of "private" (at least according automatic translators).
As reported on reddit: https://www.reddit.com/r/Monero/comments/9ti2on/gui_v01304_beryllium_bullet_released/e8xp6c7/?context=3
@rpinola Could you review this?

Fix word in finnish translation

---

main.cpp

People often post application logs to debug problems and to be able to see their GUI version (without explicitly asking) would be beneficial. 
At runtime, QML is able to read the current GUI version by reading out `version.js` (registered as a resource in `qml.qrc`). We can access `version.js` by retrieving it from the Qt resource system in C++ in `main.cpp` and print it to stdout.
Prints: `Qt:5.7.1 GUI:v0.13.0.3 | screen: 2560x1440 - dpi: 96 - ratio:0.850684`
Fixes #1654

Print GUI version to stdout on application startup

---

monero-wallet-gui.pro

Dunno why not same behavior with -cli

Build: fix static link to hidapi

---

get_libwallet_api.sh

I was getting 'no such file or directory' error from pushd. It turned out that my build was using system libunbound (on Ubuntu 18.04.1 LTS). 
It seems reasonable to check for directory existence before pushd to avoid the error which may be misleading if there are other errors.

Avoid pushd error when system libunbound is used

---

pages/Transfer.qml

@dvsdan's approach https://github.com/monero-project/monero-gui/pull/1553#issuecomment-418468076:
> If a value that starts with a period is invalid why not check if a period is pressed as the first character in the field and just insert the chars "0." before the regex check, instead to make the user's transaction amount valid.
Resolves #1718

transfer: prepend '0' to amount starting with '.' 

---

pages/Transfer.qml

**Bugs fixed**
1. A user can enter any character (`!`, `x`, etc.) as the first character in the amount field  
Ex: amount `!123` passes the validation regexp
2. Multiple dots in the amount field
Ex.: amount `.123.123` passes the validation regexp

transfer: fix amount validation regexp

---

main.qml
pages/settings/SettingsInfo.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h
wizard/WizardCreateWallet.qml
wizard/WizardOptions.qml
wizard/WizardRecoveryWallet.qml

This setting clearly belongs to the advanced ones, so it should be best combined with something like #1452.
**EDIT: #1452 was merged, so the widget is now put under the "Advanced options" section.** 
Since the dependent patch https://github.com/monero-project/monero/pull/4103 is made against the master branch, `get_libwallet_api.sh` is temporarily modified to use the master branch in 887c0eb.

Allow adjusting number of rounds for the key derivation function (requires #4103)

---

pages/settings/SettingsNode.qml

Prevents accidental tabbing and then editing of textArea fields. 😆

SettingsNode: make TextArea readOnly

---

get_libwallet_api.sh

I fail to compile the current master on MSYS2 with this error:
```
C:/msys64/home/stoffu/github/monero-project/monero-gui/monero/external/unbound/validator/val_secalgo.c: In function 'verify_canonrrset':
C:/msys64/home/stoffu/github/monero-project/monero-gui/monero/external/unbound/validator/val_secalgo.c:665:35: error: dereferencing pointer to incomplete type 'EVP_MD_CTX' {aka 'struct evp_md_ctx_st'}
ctx = (EVP_MD_CTX*)malloc(sizeof(*ctx));
^~~~
```
This seems related to the backward incompatibility in OpenSSL transitioning from 1.0.x to 1.1.x (and FWIW, the MSYS latest package uses 1.1.1), but strangely, adding these flags to cmake (borrowed from the CLI Makefile) seems to resolve it. I'm not sure why, and I'm surprised that this hasn't been spotted already AFAIK. Also strange is the …

get_libwallet_api: configure cmake toolchain for msys

---

pages/History.qml

history: fix clipping of text in search box

---

pages/Receive.qml

Fixes:
WARNING frontend    src/wallet/api/wallet.cpp:367   qrc:///pages/Receive.qml:388: Error: Insufficient arguments

Fix Receive.qml:388: Error: Insufficient arguments

---

components/HistoryTable.qml

**Fixes**
WARNING frontend    src/wallet/api/wallet.cpp:367   qrc:///components/HistoryTable.qml:296: ReferenceError: QsTr is not defined
**Before**
**After**

HistoryTable: missing TransactionID text fix

---

share/Info.plist

Fix from https://github.com/bitcoin/bitcoin/pull/14593
Temporary until the GUI handles macOS dark mode properly.
Before:
After:

macOS: fix UI issues with dark mode

---

LeftPanel.qml
components/HistoryTable.qml
components/Style.qml

Improvement wrt #1568 :: "not being able to copy and paste basic stuff like the wallet balance makes things seem amateurish or buggy (even if that's not the case)."

Enable clipboard copy functionality on XMR amounts

---

pages/settings/Settings.qml

Resolves this warning:
WARNING frontend    src/wallet/api/wallet.cpp:367   <Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "preferredHeight"

settings: fix Binding loop detected for property preferredHeight

---

main.qml
pages/Receive.qml

Now behaves consistently to other "advance options" found in wallet by remembering visibility state.

receive: enable advanced option checkbox2 to persist

---

components/StandardButton.qml

1. Fix layout
2. Add hover color animation
3. Remove redundant and unused `icon` property, use `rightIcon` with unset `text` instead
Before:
After:

standard-button: fix layout, add hover color animation

---

pages/Receive.qml
pages/Transfer.qml
wizard/WizardOptions.qml

`TextField.onEditingFinished()` and `string.startsWith()` are not available in Qt 5.7 - it breaks the compile.
Best to use Qt 5.7 as the version whilst developing to ensure compatibility.

Qt 5.7 compatibility

---

MiddlePanel.qml
components/Scroll.qml

Scrollbars without requiring the previously not yet stable QtQuick.Controls 2.0 module.
Improves usability with lower res screens such as https://github.com/monero-project/monero-gui/issues/1580

MiddlePanel: add scrollbars :lipstick:

---

MiddlePanel.qml

As there are problems with #1797 on macOS (see PR for more details), I decided to try out the QtQuick.Control scrollbar again. Seeing it is used in other places (e.g. [here](https://github.com/monero-project/monero-gui/blob/master/components/DaemonConsole.qml#L159)) I think this shouldn’t crash on Windows (#777) anymore.
Are additional changes to components/Scroll.qml required?

MiddlePanel: use QtQuick.Control scrollbar

---

components/StandardDropdown.qml

Qt 5.12
Newer Qt versions don't like the name "column"

StandardDropdown: fix variable name (> Qt 5.7)

---

pages/settings/SettingsNode.qml

settings-node: use StandardButton instead of custom buttons

---

MiddlePanel.qml

#1806 (5)
Corrects: why can scroll this far on the Transfer page?

middlepanel: fix length of scrollable area on Transfer page

---

components/RadioButton.qml

Same as https://github.com/monero-project/monero-gui/pull/1782

RadioButton: remove a gap between rectangle and text, fix layout

---

main.qml

This should be the job of the window manager. It makes sense to disable it if custom decorations aren’t used.

main: disable resize bar if custom decorations are off

---

pages/Keys.qml

For UI completeness + consistency purposes.
Before 
After

keys: add secret spend key text for viewonly wallet

---

components/LineEditMulti.qml

The same way this is handled in `LineEdit` component implementation

LineEditMulti: fix showingHeader and padding (empty label case)

---

components/HistoryTable.qml

HistoryTable: icon for mining reward transactions

---

pages/Mining.qml

fixes
Mining.qml:110:23: Unable to assign [undefined] to int

mining: fix unable to assign to int warning

---

Logger.cpp

Fixes #1691 for Windows logging 
Fixes #1690 for Linux Logging
Previously on Windows with QT 5.11.2, QCoreApplication::applicationDirPath appears broken and does not return expected path.
**Confirmed working on Windows + Linux.** 
- Windows log saved to `"C:/Users/<USER>/AppData/Roaming/monero-wallet-gui/monero-wallet-gui.log"`
- Linux log saved to `"~/.bitmonero/monero-wallet-gui.log"`
Please test on macOS, and maybe iOS/Android if you have them, unsupported of course.
- Expecting macOS log saved to `"~/Library/Logs/monero-wallet-gui.log"`
- Expecting iOS log saved to `"<APPROOT>/Library/Application Support/monero-wallet-gui/monero-wallet-gui.log"`
- Expecting Android log saved to `"<USER>/<APPNAME>/files/monero-wallet-gui.log"`

Logging: fix logging file paths :bug:

---

main.qml
pages/AddressBook.qml
pages/Transfer.qml
pages/settings/SettingsLayout.qml

monero-project/monero#5020
Not sure how this should be implemented, this is just an idea.
Default looks like this: 
Can be re-enabled in settings.

Transfer: disable long payment ids by default

---

get_libwallet_api.sh

Not sure if this is more correct, but I ran into weird caching issues where `git -C $MONERO_DIR checkout master` would checkout deleted local commits.

build: always checkout latest remote master

---

components/AddressBookTable.qml
pages/AddressBook.qml
pages/Transfer.qml

https://github.com/monero-project/monero-gui/issues/1901 (1)

AddressBook: hide 'Add' form when invoked from 'Send' tab

---

main.cpp
pages/History.qml
src/libwalletqt/TransactionHistory.cpp
src/libwalletqt/TransactionHistory.h

Fixes #1897
1. Export CSV button on history page
2. Choose destination folder (defaults to Desktop)
3. CSV written with following columns `blockHeight,epoch,date,direction,amount,atomicAmount,fee,txid,label,subaddrAccount,paymentId`

CSV export for transaction history

---

components/PasswordDialog.qml

PasswordDialog: cancel button text is more descriptive and dynamic

---

components/IconButton.qml

The animation was buggy if the mouse got released mouse outside of the mouse-area or outside of the whole program. Maybe someone has an idea how this can get fixed instead of removing it?

IconButton: fix mousearea and remove animation

---

main.qml
pages/Transfer.qml
pages/settings/SettingsLayout.qml

This was reported by charuto on https://git.pwned.systems/monero-project/monero-gui/issues/1
> If payment ID option is expanded, upon removing the payment ID setting, it will remain on the send page.
> Tested on master branch.
**Edit**: Brought back payment id to the transfer page, albeit collapsed by default, as was decided in the [dev meeting](https://www.reddit.com/r/Monero/comments/akmf5q/logs_of_yesterdays_dev_meeting/).

Bring back paymentID to tranfer page and force hide paymentId on a settings toggle

---

main.cpp
pages/Mining.qml
src/daemon/DaemonManager.cpp

`--max-concurrency` based on 50% of threads available with a max of `6`. ~In addition, `--db-sync-mode` is forced on `safe`. This guards against corruption on unclean shutdowns.~
I'm expecting this PR to solve some of the "my machine is slow while syncing" complaints.

Dynamic --max-concurrency, max 6

---

pages/settings/SettingsNode.qml

I've discovered that the daemon flags never get saved to `persistentSettings`. This PR fixes that. In addition, I've made the input box multiline.

Fix daemon flags

---

pages/Transfer.qml

WARNING	frontend	src/wallet/api/wallet.cpp:367	qrc:/pages/Transfer.qml:271: Error: Cannot assign to non-existent property "cursorPosition"

transfer: fix non-existent property cursorPosition

---

components/WarningBox.qml

warningbox: make text readonly

---

main.qml
pages/Transfer.qml
pages/settings/SettingsLayout.qml

This reverts PR https://github.com/monero-project/monero-gui/pull/1916 commit 02493be6eb7426b2814d356283c5877e779f1aea.
Standalone/long Payment ID must be hidden by default with the next fork.

Re-revert hasty paymentID revert

---

js/Wizard.js
wizard/WizardController.qml
wizard/WizardHome.qml
wizard/WizardRestoreWallet1.qml
wizard/WizardRestoreWallet4.qml

While triaging https://github.com/monero-project/monero-gui/pull/1909#issuecomment-464224316
with the broken restore height functionality when restoring an existing wallet, it seems the whole restore from keys/seed functionality needed fixing. Also fixed some variable naming issues in updateFromQrCode.

wizard: fix restore from key and seed functionality

---

components/TitleBar.qml
main.qml
pages/settings/SettingsLayout.qml
qml.qrc
wizard/WizardHome.qml
wizard/WizardLang.qml
wizard/WizardLanguage.qml

Due to a hard to debug buildbot issue concerning the sidebar on a statically compiled Qt 5.7.0, I concluded the pragmatic solution is to temporarily disable the sidebar for now until we migrate to > Qt 5.9.

Replace language sidebar with dedicated language screen

---

wizard/WizardSummary.qml

wizardsummary: hide restore height when creating new wallet

---

main.qml
wizard/WizardCreateWallet2.qml
wizard/WizardOpenWallet1.qml
wizard/WizardRestoreWallet2.qml

I've noticed on Windows 10, it will show this warning message while connecting to a remote node, regardless if it is (eventually) successful or not. This is bad because users will think something is up, while it's working.
I loosely assume this is due to the Javascript code that does the XHR request to the node aggregator, but I don't know for sure. This behaviour has not happened to me on Linux. sgp observed the same problem.
For now, it's best to replace this message with `console.log()`. We can have decent status messages when xiphon's node magic gets merged for 14.1.

Dont show message on simple mode disconnect/reconnect

---

qml.qrc

Static assets already included in repo, forgot to add to qml.qrc.

Add high-res images for mode selection wizard icons

---

pages/Receive.qml
pages/Sign.qml

```
WARN 	frontend	src/wallet/api/wallet.cpp:367	qrc:/pages/Sign.qml:121: ReferenceError: instructionsRect is not defined
WARN 	frontend	src/wallet/api/wallet.cpp:367	qrc:/pages/Receive.qml:224: ReferenceError: selectAndSend is not defined

sign, receive: fix reference errors

---

wizard/WizardCreateDevice1.qml
wizard/WizardCreateWallet1.qml
wizard/WizardRestoreWallet1.qml
wizard/WizardWalletInput.qml

Fixes:
1. Create a wallet with the name "test"
2. Logout 
3. Create a new wallet with the same name, wizard isn’t complaining. If you close the GUI instead of logout, it will complain if you use the same wallet name.
Found by @selsta

invalidate wallet name after creation

---

pages/Transfer.qml
pages/merchant/Merchant.qml

Changed based on user feedback. A amount field with "0.00" has better affordance.

transfer, merchant: placehodler text for amount

---

wizard/WizardCreateWallet1.qml

This placeholder was marked as translatable, but there isn't really anything to translate. This resulted in a basically empty string that translators had to work on (see [example on Pootle](https://translate.getmonero.org/it/monero-gui/translate/#search=-&sfields=source,target&unit=220533&offset=0))
This PR makes the string untranslatable.

Makes placeholder string untranslatable

---

wizard/WizardCreateDevice1.qml

Recent UI revamps seem to have broken the `Restore height` option in the hardware wallet setup process.
Right now it looks like this:
And with this PR it will look like this:
Cosmetic UI details, but I needed this to work properly.

[Bugfix] Restore height option for hardware wallet restore

---

main.qml

Gracefully fixes wallet opening issues such as #1738 #1730 
Clears wallet cache for common error messages which normally require manual user intervention.
Handles cases involving basic_string::_M_replace_aux and std::bad_alloc error.
Old wallet cache remains and is renamed by walletManager.clearWalletCache.
Before
After

main: automatically fix common wallet cache errors

---

components/PassphraseDialog.qml
components/Style.qml
main.qml
qml.qrc
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h
wizard/WizardController.qml
wizard/WizardCreateDevice1.qml

- Requires https://github.com/monero-project/monero-gui/pull/2019
- Passphrase entry on host added, requires early listener setting https://github.com/monero-project/monero/pull/5355
- Wallet open and create from device shows splash to indicate a possible long process
- Create from a device is async to support passphrase entry
In order to build this PR for testing you need to fetch my original branch
```bash
git clone --recursive https://github.com/monero-project/monero-gui.git
cd monero-gui
git remote add ph4r05 https://github.com/ph4r05/monero-gui.git
git fetch --all
git checkout -b trezor-pass ph4r05/trezor-pass
cd monero
git remote add ph4r05 https://github.com/ph4r05/monero.git
git fetch --all
git checkout -b trezor/api_pass ph4r05/trezor/api_pass
git submodule update --recursive
cd …
```

Async device open and create from device, passphrase entry, requires #5355

---

monero-wallet-gui.pro

This patch finds dependencies required to make Trezor support viable.

Use pkg-config to find libusb and protobuf (Trezor dependencies)

---

components/InlineButton.qml
components/LineEditMulti.qml

```
2019-04-23 22:03:49.972	W qrc:/components/LineEditMulti.qml:199:9: QML InlineButton: Cannot specify top, bottom, and verticalCenter anchors at the same time.
```

InlineButton: fix warning and set font

---

filter.cpp
monero-wallet-gui.pro

Slow down QML animations by a factor of 10 on `F9`/`F10` for debugging purposes.
Requires white-theme https://github.com/monero-project/monero-gui/pull/2060

[Qt 5.9] Debug QML animations

---

pages/History.qml

Hides the sorting, export CSV and pagination buttons when wallet has no transactions yet. No reason to display these options.
Requires #2060

[Qt 5.9] Transaction history, hide certain elements on empty wallet

---

MiddlePanel.qml
js/TxUtils.js
pages/Account.qml
pages/Receive.qml

- Trackpad scrolling
- Scrolling support for large number of accounts
- Monospace font
- Address in blocks
- Larger font size
Requires #2060

[Qt 5.9] Account/Receive: update design

---

pages/settings/SettingsWallet.qml

> You could also look into Settings -> Wallet alignment. It messes up if the window width is small.
Requires #2060

[Qt 5.9] Dynamic height settings wallet

---

wizard/WizardController.qml
wizard/WizardHome.qml
wizard/WizardLanguage.qml
wizard/WizardModeSelection.qml
wizard/WizardNav.qml

Quote from IRC:
> Disco: The fact that *all* screen transitions are swipes from the left is very confusing. Users tend to create a mental map of an apps pages.
This PR changes the transition direction depending on Back/Next in the wizards.
Requires #2060 
Requires #2070

[Qt 5.9] Back transitions for the wizards

---

pages/settings/SettingsLayout.qml

```
2019-04-25 21:40:51.062 W qrc:/pages/settings/SettingsLayout.qml:48: ReferenceError: userInactivitySliderTimer is not defined 
```

SettingsLayout: userInactivitySliderTimer is not defined

---

wizard/WizardController.qml

Bug found by @selsta and @MoneroChan
Might have been present since the new wizards. Reproduce:
1. At the wizards, choose 'Create a new wallet'
2. Go back
3. Open a new wallet
4. Balance does not show up
5. Possibly a crash if you wait long enough (according to #2032)
Fix: Clear `wizard.m_wallet` before doing anything else.
Fixes #2032

Clear m_wallet before opening new wallets

---

wizard/WizardHome.qml

wizard: reset remote node when switching network type

---

filter.cpp
filter.h
main.cpp
main.qml
monero-wallet-gui.pro
pages/Transfer.qml
share/Info.plist
src/qt/ipc.cpp
src/qt/ipc.h
src/qt/mime.cpp
src/qt/mime.h
src/qt/utils.cpp
src/qt/utils.h

Adds support for the `monero://` scheme. allowing the GUI to launch from a (but not limited to) a browser.
Following parameters are supported:
- `monero://<address>`
- `monero://<address>?tx_amount=5.0`
- `monero://<address>?tx_description=foo`
- `monero://<address>?tx_payment_id=foo`
- `monero://<address>?tx_amount=5.0&tx_description=foo&tx_payment_id=foo`
This is also what MyMonero supports; [link](https://github.com/mymonero/mymonero-app-js/blob/fe8028556d4582d1e747e52871e068fd19b886ee/local_modules/MoneroUtils/monero_requestURI_utils.js#L61)
IPC stands for inter process communication. We use [QLocalServer](https://doc.qt.io/qt-5/qlocalserver.html) to communicate URI commands whenever an instance of the GUI is already running in order to avoid starting the GUI each time an user clicks …

IPC and custom protocol handler for monero://

---

pages/Transfer.qml

Replaces PR #2067
Implements @GBKS's suggestions by tightening vertical spacing and tweaking labels.

transfer: change description/pid checkbox

---

components/InputDialog.qml
components/StandardDialog.qml
js/Windows.js

Requires custom decorations turned off.

macOS: enable fullscreen support

---

wizard/WizardController.qml

Error: Cannot assign to non-existent property "backTransition"

wizard: fix non-existent property backTransition

---

main.cpp

Enables to setup logging level from the start so the Wizard logs are visible for better debugging.

logging: initial log level set by ENV var

---

LeftPanel.qml

LeftPanel: don't change font size if balance is hidden

---

main.cpp
monero-wallet-gui.pro
src/qt/KeysFiles.cpp
src/qt/KeysFiles.h
wizard/WizardOpenWallet1.qml

This PR scans for `.keys` files in the Monero accounts directory, displays them in a Listview. 
Old situation was [naively assuming directories](https://github.com/monero-project/monero-gui/blob/d2c47606ca8446e58ef122117f8f84b578691bab/wizard/WizardOpenWallet1.qml#L45-L55) in `~/Monero/wallets/*` were valid wallet paths, this actually checks for the presence of `.keys`. In addition, it can detect what network type a wallet is and the GUI switches to that upon opening the wallet.

Scan .keys files in wizard

---

components/Notifier.qml
main.cpp
main.qml

Fix checking for gui updates

---

wizard/WizardModeBootstrap.qml

Wizard modes -> Bootstrap warning text shows html tag.

Bootstrap warning text should be richtext

---

main.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

Getting rid of the following lag during wallet initialization:

WalletManager: async setDaemonAddress

---

pages/Mining.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

Another blocking call during startup. Also affects Mining tab:

WalletManager: non-blocking mining status updates

---

monero-wallet-gui.pro

Resolves two Windows build errors encountered while building in a msys mingw environment.
- can't find -lprotobuf (first encountered in #2173)
- mingw64/lib\libcrypto.a(b_addr.o):(.text+0xaa): undefined reference to `__imp_getnameinfo'
Credit to these posts for the fix ideas:
https://stackoverflow.com/questions/29920833/eclipse-cant-find-lprotobuf
https://codedump.io/share/RpR9bJHRu3fI/1/mingw-undefined-reference-to-libws232-39getnameinfo39-39getaddrinfo39-

monero-wallet-gui.pro: Fix windows mingw build

---

installers/windows/Monero.iss

After PR #2173 almost everything needed (Qt files, various other runtime DLLs, etc.) is now neatly contained in the single `monero-wallet-gui.exe` file which allows to simplify the InnoSetup script `Monero.iss` quite substantially.

Windows installer: Simplify script thanks to static linking of GUI wallet exe

---

pages/settings/SettingsNode.qml

these two strings weren't marked as translatable and show in English.

Add missed translatable string in SettingsNode.qml

---

main.qml
pages/History.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

- do not display tx key for Trezor-based wallets in the Transaction history by default. It required device roundtrip with confirmation which made browsing the history unusable.  
- async behavior: getTxKey, get tx info, get tx proof
- fixes issue https://github.com/monero-project/monero-gui/issues/2183
- fixes the deadlock issues
- requires https://github.com/monero-project/monero/pull/5662 to work correctly (otherwise, zeros are returned, async nature cannot be tested, proofs don't work, etc...). However, it compiles without it and this PR can be merged before the monero-core PR is merged and submodule updated.

get_tx_key fixes for Trezor

---

components/NetworkStatusItem.qml
main.qml

Fixes a bug where it would display “Connected” instead of “Remote node”.
To reproduce:
- Connect to remote node.
- Exit GUI.
- Start GUI again, it now displays “Connected” instead of “Remote node”.

NetworkStatusItem: correctly display remote node status

---

pages/Transfer.qml

Less is more in simple mode. 
Only the absolute required fields should be visible. Compared to other beginner-friendly wallets, only the essentials remain. Those are amount and address. Currently, transfer page in simple has two extra optional touch points causing undue user thoughts and doubt. Removed transaction priority and description based on some user's feedback. Thoughts?
After
Before

transfer: make simple mode more simple

---

linuxdeploy_helper.sh

Tails users are required to start a terminal and issue `./start-gui.sh` manually. Terminals are scary. People like to double click on applications and they open.
Tails is weird; We can `chmod +x` our `start-gui.sh` (bash) or `monero-wallet-gui` (ELF) all we want, they won't be double-clickable.
I've found that filenames that start with `.AppImage` *are* double clickable. We abuse this to create a `start-tails.AppImage` that internally calls `start-gui.sh`.
Improves UX a ton.

Tails: Launcher

---

installers/windows/Deterministic.md
installers/windows/Monero.iss

As you can read in the file `Deterministic.md` that this part of the PR using 1 Inno Setup script line `TimeStampsInUTC=yes` makes the building of the GUI wallet Windows installer reproducible.
Several people that followed my call for help in [this Reddit post](https://old.reddit.com/r/Monero/comments/cd0snl/help_test_reproducible_windows_gui_installer/) arrived at the same SHA256 hash as I did, which is a nice confirmation that the build process is indeed reproducible when using the script file in this PR.

Windows installer: Achieve reproducible builds

---

main.cpp
main.qml
monero-wallet-gui.pro
src/qt/MoneroSettings.cpp
src/qt/MoneroSettings.h

Currently we write the Monero GUI configuration to:
- The registry on Windows
- XML preferences file on MacOS
- `~/.config/monero-project/monero-core.conf` on Linux
We use `import Qt.labs.settings 1.0` to handle settings for us (called `persistentSettings`). This QML component allows  to specify an arbitrary filepath, except, that this is [not available for our Qt version](https://doc.qt.io/qt-5/qml-qt-labs-settings-settings.html#fileName-prop). This means we cannot write to a location at will.
This PR is a backport of the `Qt.labs.settings` [QML plugin from 5.12.0](https://github.com/qt/qtdeclarative/blob/5.12/src/imports/settings), aliased as `MoneroSettings`. 
The nice thing is that we don't have to change anything in our QML except for:
```qml
Settings {    <== Change this to …
```

QML component: MoneroSettings {}

---

main.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

> @selsta
> 
> When opening the GUI, the trusted daemon flag doesn’t get set properly. Easy fix: set it manually before rescanning.
>
> Reported here: https://monero.stackexchange.com/questions/11512/rescan-ledger-wallet-from-0-in-the-gui

Wallet: explicitly set trusted daemon flag

---

src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

```C++
#include "WalletManager.h"
#include "Wallet.h"
WalletManager *wallet_manager = WalletManager::instance();
Wallet *wallet = wallet_manager->openWallet("/home/foobar/Monero/wallets/foobar/foobar.keys", "passwd", NetworkType::MAINNET);
wallet->setCacheAttribute("foo_key", "bar_value");
qDebug() << wallet->getCacheAttribute("foo_key");
```
Requires https://github.com/monero-project/monero/pull/5534

Expose get/set attrs for wallet cache in libwalletqt

---

components/TitleBar.qml

Requires and to be merged after #2372

TitleBar: change Light Theme icon from 'light bulb' to 'moon'

---

js/Utils.js
main.qml
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h
wizard/WizardController.qml
wizard/WizardCreateWallet2.qml
wizard/WizardModeBootstrap.qml
wizard/WizardModeRemoteNodeWarning.qml
wizard/WizardOpenWallet1.qml
wizard/WizardRestoreWallet2.qml

Split the PR into two commits, suggest to review them separately since the first one is pretty straightforward stripping `https://autonode.xmr.pm/` related code.
Will squash the commits once the PR is approved

SimpleMode: automatic public nodes discovering and switching

---

components/TitleBar.qml
main.qml

Shows the wallet name if a wallet is open, else it will show the current logo + MONERO.
Resolves #2325

TitleBar: show wallet name

---

main.cpp

main: set TERM="goaway"

---

windeploy_helper.sh

Dependency on libcouble-conversion.dll seems to have been introduced here: https://github.com/msys2/MINGW-packages/commit/ec9c7ac1c80476bf386d165c63fec88cba7415d5

windeploy: bump icu version to 64, add libdouble-conversion.dll

---

README.md

We officially switched from Pootle to Weblate: translate.getmonero.org

Change 'Pootle' to 'Weblate' in readme

---

main.qml

To set appropriate `useRemoteNode` and `bootstrapNodeAddress` values for SimpleMode users updating from v0.14.1 to v0.15.

main: apply WalletMode check on start

---

pages/Transfer.qml

See discussion here:   #2410 
For view-only wallets change warning from:
`Wallet is view-only and sends are not possible.`
to:
`Wallet is view-only and sends are not possible. Unless key images are imported,
the balance reflects only incoming but not outgoing  transactions.`

View only wallet -> warning that balance reflects only incoming transactions

---

components/ContextMenu.qml
components/Input.qml
components/InputDialog.qml
components/InputMulti.qml
components/LineEditMulti.qml
components/PasswordDialog.qml
pages/AddressBook.qml
pages/Transfer.qml
pages/merchant/Merchant.qml
qml.qrc
wizard/WizardAskPassword.qml
wizard/WizardRestoreWallet1.qml

Fixes #2359
Partially addresses #2405

ContextMenu: implement 'paste' context menu for all text fields

---

.github/workflows/build.yml

Example build: https://github.com/selsta/monero-gui/commit/f57b2d57cd3ed24601f287931b771a047e30288c/checks
Windows can be added in a later PR.

workflows: add basic ubuntu/macOS build script

---

components/PasswordDialog.qml

Closes https://github.com/monero-project/monero-gui/issues/2492

PasswordDialog: fix text field height changing on input (Windows)

---

src/libwalletqt/TransactionHistory.cpp
src/libwalletqt/TransactionHistory.h

Addresses (to some extent) https://github.com/monero-project/monero-gui/issues/2483 bug

TransactionHistory: guard tx info list against concurrent access

---

pages/History.qml

To be merged after #2614
Shouldn't hide any functionality from a user that just set up a wallet.
A newbie observing Monero GUI wallet for the first time should learn that such a functionality exists and could be used in the future.

History: don't hide 'Export all history' if there ain't any txes

---

components/DatePicker.qml
components/StandardDropdown.qml

Clicking on parent will now properly close dropdown.

fix dropdown closure behavior

---

Makefile

|Target|Default DEV_MODE|
|-|-
|default|OFF|
|debug|ON|
|devmode|ON|
|scanner|ON|
|debug-static-win64|ON|
|debug-static-mac64|ON|
|release-static-win64|OFF|

build: support DEV_MODE env var to override default value

---

src/main/main.cpp

Tested on Ubuntu, someone has to test it on Windows. Requires Qt 5.14.

[Qt 5.14] main: enable high DPI scaling

---

MiddlePanel.qml
components/StandardDialog.qml
pages/settings/SettingsLog.qml
wizard/WizardController.qml

closes #2662
Unfortunately there seems to be no better way to do this.
`ScrollBar.AsNeeded` will autohide and `ScrollBar.AlwaysOn` will always display the scrollbar, even when not needed.

Scrollbar: don't autohide if enabled (except on Mac)

---

src/qt/FutureScheduler.h

The last patch of crash-related fixes, finally closes https://github.com/monero-project/monero-gui/issues/2483

FutureScheduler: drop moveToThread, setParent might silently fail

---

monero-wallet-gui.pro

From `man ld`.
```
-dead_strip
Remove functions and data that are unreachable by the entry point or exported symbols.
```
Before:
After:
From `man ld`.
```
-dead_strip_dylibs
Remove dylibs that are unreachable by the entry point or exported symbols. That is, suppresses the generation of load
command commands for dylibs which supplied no symbols during the link. This option should not be used when linking
against a dylib which is required at runtime for some indirect reason such as the dylib has an important initializer.
```
Before:
```
$ otool -L monero-wallet-gui
/opt/local/lib/libunbound.8.dylib (compatibility version 10.0.0, current version 10.5.0)
/opt/local/lib/libboost_serialization-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
/opt/local/lib/libboost_thread-mt.dylib …
```

Pass -dead_strip and -dead_strip_dylibs on macOS

---

pages/Sign.qml
pages/Transfer.qml

Remove all paste buttons, cleaning UI.
Users can still paste from clipboard by right clicking on text fields.
After:
Before:

Remove paste buttons

---

pages/History.qml

Closes #2743
Case sensitive is only needed when sending a transaction. When you are searching for an address in transaction history, it is better to have a case insensitive filter.

History: address filter case insensitive

---

pages/Keys.qml

Keys: stop displaying hardware device message in view-only wallets

---

wizard/WizardOpenWallet1.qml

```
2019-12-14 02:07:08.800	W qrc:/wizard/WizardOpenWallet1.qml:72: ReferenceError: WalletKeysFilesModel is not defined
2019-12-14 02:07:08.800	W qrc:/wizard/WizardOpenWallet1.qml:48: ReferenceError: WalletKeysFilesModel is not defined
```

WizardOpenWallet1: fix warning

---

components/MenuButton.qml

MenuButton: fix gradient

---

pages/History.qml

Closes #2628
Add filter options in search field placeholder: "Search by Transaction ID, Address, Description, Amount or Blockheight"
Currently only destination address is supported in search, but I decided to use "Address" (see issue #2705 for adding receiving address as search option)

History: add filter options in search field placeholder

---

pages/History.qml
src/libwalletqt/AddressBook.cpp
src/libwalletqt/AddressBook.h
src/libwalletqt/Wallet.h

Closes https://github.com/monero-project/monero-gui/issues/2757

History: display Address Book names for known destination addresses

---

components/NetworkStatusItem.qml
main.qml

I’ve read a few reports of people being confused when switching from simple to advanced mode, as they have to manually remove `auto` from the bootstrap daemon textbox.
E.g. https://www.reddit.com/r/Monero/comments/f4oj9a/advanced_mode_in_gui_but_still_bootstrapping/

Simple mode: don't override bootstrap daemon textbox

---

installers/windows/Monero.iss

```
Warning: Constant "pf" has been renamed. Use "commonpf" instead or consider using its "auto" form.
```

installers: fix warning

---

README.md

Adding [Weblate's widget for translations status](https://translate.getmonero.org/widgets/monero/?component=gui-wallet#horizontal).
Preview: https://github.com/erciccione/monero-core/tree/weblate-stats#translations

README: add weblate's widget for translations status

---

src/QR-Code-scanner/QrScanThread.cpp

QrScanThread: use sizeInBytes to fix warning

---

components/InlineButton.qml
components/LineEditMulti.qml
pages/Transfer.qml

Changes:
- Remove "(Address Book)" link from address field label
- Add address book inline button with icon + adjust right margin of address field
- Add second inline button (scan QR code button)
- Change color of scan QR code button
Address book inline button as single inline button:
With scan QR code button enabled:

Transfer: add Address Book inline button in Address field

---

components/CheckBox.qml
components/Style.qml

Plan to use it to disable input when `--disable-check-updates` flag is set but can be used in other places too.

CheckBox: add enabled property

---

components/AdvancedOptionsItem.qml
pages/Transfer.qml
qml.qrc

Changes:
- Group buttons according to functionality + add labels
- Functionalities are ordered according to instructions in https://monero.stackexchange.com/questions/2868/is-there-any-way-to-construct-a-transaction-manually/2916#2916
- Buttons are always visible
- Buttons are disabled when they aren't intended for use (watch-only vs. spend wallet)
- Add ? buttons which display instruction messages 
- Information message 1 (in orange): it appears when wallet is view-only and the amount and/or address field(s) are empty, which disables the create tx button: "To create a transaction file, please enter amount and address above"
- Information message 2 (in orange): it appears in Key images row, when the wallet is connected to a non-trusted remote node: "Step 2 requires connection to a local …

Transfer: redesign advanced options

---

components/StandardDropdown.qml

StandardDropdown: fix margins, text overlapping

---

wizard/WizardAskPassword.qml

Fixes https://github.com/monero-project/monero-gui/issues/2700
Requires https://github.com/monero-project/monero-gui/pull/2870.

WizardAskPassword: drop custom password fields, use LineEdit

---

components/ProgressBar.qml
main.qml

This finally implements the idea described in my issue #2713 from January: 100% for the daemon sync progress bar in the lower left corner is not current blockchain height anymore, but the total number of blocks to sync, starting from the height at GUI wallet startup, so the progress bar is able to show progress.

Improved daemon sync progress bar

---

js/Wizard.js

This uses a regular expression for the JavaScript method `split` instead of simply `" "` to deal with any multiple blanks in seed input, without any undesirable side effects like it seems this earlier attempt to solve the same problem had: #2771

Filter out multiple blanks in seed input when counting words

---

src/main/main.cpp

Report: https://www.reddit.com/r/Monero/comments/gmhxl6/im_having_trouble_running_monero_gui_wallet_on_my/
We don't need `start-low-graphics-mode.bat` anymore. Could keep it for a while and drop it later though.

OpenGL: Windows - fall back to software renderer if OpenGL < 2.1

---

.github/workflows/build.yml

`eine/setup-msys2@v0` is better maintained.
Disabling qtquickcompiler “solves” the bad address Qt bug.

workflows: fix windows build

---

src/daemon/DaemonManager.cpp

This upper bound limits stronger CPUs while the goal was to make the system less laggy on weaker CPUs.

DaemonManager: remove max-concurrency upper bound

---

.github/workflows/build.yml

Decreases msys2 setup time from ~12 minutes to ~4 minutes.
Will rebase after #2928 is merged.

workflows: update msys2 setup action v0 -> v1

---

main.qml
pages/settings/Navbar.qml

Can useful in simple mode bootstrap to see the sync status and also useful when doing trying to help a user.

simple mode: enable settings log tab

---

src/main/main.cpp

Due to a potential Qt bug qrc:///lang/languages.xml gets
blocked resulting in broken translations.

main: disable NetworkAccessBlockingFactory.h if Qt < 5.12

---

MiddlePanel.qml
components/DatePicker.qml
pages/Account.qml
pages/History.qml
pages/Receive.qml

Untested with Qt 5.9, the `function onFoo() {}` syntax might not be available.

QML: fix some Qt 5.15 warnings

---

pages/History.qml

- Search filter now works when there is a pending transaction (fixes #2703)

history: fix search filter not working when there is a pending tx

---

pages/History.qml

- Amounts like 0.000000000001 are now displayed correctly (fixes #2993)
- Amounts with trailing zeros like 0.000100000000 are displayed as 0.0001

history: fix amount display + remove trailing zeros in amount

---

wizard/WizardWalletInput.qml

Report of "failed to save wallet" because someone added `/` to the end of the wallet name.

WizardWalletInput: disallow (back)slash

---

src/CMakeLists.txt

Only thing not working yet is `monerod` and other CLI executables don’t get copied into the bundle.

cmake: build bundle on macOS

---

pages/settings/SettingsLog.qml

Allow users to navigate with up/down arrows the last commands entered in Settings > Log (during a session).

SettingsLog: add command history

---

README.md

Removed AUR package, since doesn't seem to exist anymore, added Debian package (the CCS-funded one) and updated xbps and guix packages.
We will link to this list from the website: https://github.com/monero-project/monero-site/pull/1135

README: update list of third party monero packages

---

Dockerfile

Seeing that we don’t use 5.9.7 on macOS and Windows, I don’t see a reason to not use the latest release in 5.9 LTS.
Opinions?

docker: update Qt to 5.9.9

---

CMakeLists.txt

Avoids the console getting spammed with warnings like this:
```
CMake Warning (dev) in monero/external/miniupnp/miniupnpc/CMakeLists.txt:
AUTOGEN: No valid Qt version found for target libminiupnpc-static.
AUTOMOC, AUTOUIC and AUTORCC disabled.  Consider adding:
find_package(Qt<QTVERSION> COMPONENTS Widgets)
to your CMakeLists.txt file.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

cmake: move autogen to avoid warnings

---

main.qml
pages/Account.qml

Update total balance and total unlocked balance when a new block is found and account page is open (fixes #2741).

account: update balances of account page when new block is found

---

CMakeLists.txt

Closes https://github.com/monero-project/monero-gui/issues/3093

cmake: support ARCH and BUILD_64 overriding

---

.github/workflows/build.yml

We could upload the resulting bins somewhere but that get added at a later point.

workflows: add static docker build

---

pages/History.qml

Changes:
- removed trailing zeros in Fee
Changes in Received transations:
- added "In" field to the Blockheight field position. This field will display the receiving address index + label (from the receive page) or the truncated address (when the address has no label) (fixes #2987)
- Blockheight field moved to the bottom.
- increased height of collapsed received transactions to the same as sent transactions (320 pixels), in order to display the blockheight. As a side effect, transaction key is also being displayed for received transactions.
Changes in Sent transactions:
- moved "To" field to the Blockheight field position. This field will now display either an address book icon + a destination address label (from the address book) or a truncated destination address (when the destination …

history: add "In" and "To" fields + add address label

---

components/CheckBox.qml
src/main/main.cpp
src/qt/macoshelper.h
src/qt/macoshelper.mm
wizard/WizardLanguage.qml
wizard/WizardMenuItem.qml
wizard/WizardModeSelection.qml

Closes https://github.com/monero-project/monero-gui/issues/3104
Requires https://github.com/monero-project/monero-gui/pull/3023, https://github.com/monero-project/monero-gui/pull/3025
In `Portable mode` it will store settings and wallets in 'storage' folder near monero-wallet-gui executable (based on current working directory).

WizardModeSelection: optional 'Portable mode' feature support

---

.github/workflows/build.yml

Github Actions Mac image gets updated every week -> unnecessary.

workflows: don't brew update

---

main.qml
pages/settings/SettingsInfo.qml
src/main/Logger.cpp
src/main/Logger.h
src/main/main.cpp
src/qt/MoneroSettings.cpp
src/qt/MoneroSettings.h
wizard/WizardModeSelection.qml

* Should't create/write any log file till wallet mode gets selected If a user starts Monero GUI for the first time,
* Portable mode: writes log file to `monero-storage` folder.

Logger: runtime log config, no logs till a user selects wallet mode

---

wizard/WizardRestoreWallet1.qml

You could click "next" even if the wallet name is invalid.

WizardRestoreWallet1: fix "wallet name" check in keys mode

---

src/CMakeLists.txt

Binary should be installed in bin/ relative to CMAKE_INSTALL_PREFIX,
prior to this commit, monero-wallet-gui is installed in usr/ instead of
usr/bin
-- Installing: image/usr/monero-wallet-gui
With this comment, file is installed in the right location:
-- Installing: image/usr/bin/monero-wallet-gui
See: https://cmake.org/cmake/help/latest/command/install.html

cmake: fix install targets

---

pages/settings/SettingsWallet.qml

Ledger doesn't support creating view-only wallet. See #3151 and https://www.reddit.com/r/monerosupport/comments/jcaet1/error_couldnt_open_wallet_file_mywallet_viewonly/

SettingsWallet: disable creating view-only wallet for Ledger

---

components/TxConfirmationDialog.qml
main.qml
qml.qrc

Closes #2467
See previous discussion in #2895 and #3146
**Changes:**
New TxConfirmationDialog component:
- From field: 
- Wallet name ("Ledger", "Trezor" or "My wallet")
- Account # + Account label (if the wallet has more than one account)
- To field:
- Address book icon + name (if address is in address book)
- Destination address
- Added fiat conversion to amount and fee
- Removed extra zeros from the end of amount and fee
- Keyboard can be used to cancel (ESC key) or to confirm dialogs (enter/return keys)
- When the dialog is waiting for user action (hardware wallet button press), a blinking text message will appear
Normal transaction:

Transfer: new TxConfirmationDialog

---

.github/workflows/build.yml

Fixes the warnings, also better maintained.

workflows: bump msys2 action to v2

---

src/main/main.cpp
src/qt/MoneroSettings.cpp
src/qt/MoneroSettings.h

Related https://github.com/monero-project/monero-gui/issues/3241

portable: use portable storage folder to store QML disk cache

---

wizard/WizardRestoreWallet1.qml

Changes:
- If seed field contains a seed <24 or >25 words (word count is done in function `checkSeed(seed)` in `/js/Wizard.js`), a red border is displayed to indicate an invalid seed

Restore: display red border if invalid seed

---

.github/workflows/build.yml

No reason for such a long name now that we remove Travis.

workflows: shorten name

---

pages/Account.qml
pages/Receive.qml

Closes #2572
Closes #3067
Changes:
- selected account in account page now has highlighted background and text label
- selected address in receive page now has highlighted background and text label

Account/receive: highlight background and text of selected item

---

wizard/WizardRestoreWallet1.qml

Restore page can be used to create view-only wallets from address + private view key.
This PR updates the placeholder of private spend key field to inform that it's optional and should be left blank in order to generate a view-only wallet.

Restore: add create view-only wallet option

---

pages/History.qml

Closes #2705
Currently search bar supports searching by Transaction ID, Destination address, Description, Amount, and Blockheight.
This PR adds searching by Receiving address, Receiving address label, and Address book label (Destination address label).

History: search by receiving address, receiving add. label, address book label

---

pages/settings/SettingsLog.qml

Closes https://github.com/monero-project/monero-gui/issues/3228

SettingsLog: disable daemon command input in Remote Node mode 

---

components/DaemonManagerDialog.qml

The white window with black text looks out of place when using the dark theme. Instead use the default colors for the currently selected theme.

DaemonManagerDialog use preferred color scheme

---

translations/monero-core_nb.ts

It seems like the name was incorrect since the Norwegian translation in the program did not function with that file name.
Fixes #3353

Renamed Norwegian translation file to the correct name.

---

.github/workflows/build.yml
CMakeLists.txt
README.md
components/MenuBar.qml
main.qml
qml.qrc
src/main/main.cpp
src/qt/macoshelper.mm

macOS: add basic menubar support

---

wizard/WizardSummary.qml

Both of these summary items only make sense in advanced mode.

WizardSummary: don't display node address in simple mode

---

wizard/WizardHome.qml

Related to #3088
Textbox would always display 1, even if the `persistentSettings.kdfRounds` value is different.

WizardHome: fix kdf textbox displaying incorrect value

---

src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h
wizard/WizardController.qml

Related to #3088
`createWalletFromDeviceAsync()` would ignore the kdf value while `openWalletAsync()` would take it into account, leading to the bug that hardware wallets created with kdf > 1 would fail to open.

WalletManager: support kdf round in device wallet restore

---

MiddlePanel.qml
components/SuccessfulTxDialog.qml
main.qml
pages/History.qml

Closes #2148
Main changes:
- SuccessfulTxDialog: add View progress (secondary) button
- History: auto collapse tx item if there is a single result
- History: clean searchInput + list of collapsed txs when closing page
- History: add FontAwesome icons for txs with Pending and Failed states
- History: Display Pending and Failed states to the right of "Sent" and "Received" labels

SuccessfulTxDialog: add View progress button

---

translations/CMakeLists.txt

Required for debug build on Mac.
```
[360/428] Linking CXX shared library translations/libtranslations.dylib
FAILED: translations/libtranslations.dylib 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -march=x86-64 -fvisibility=default -std=c++11 -fvisibility=default -DGTEST_HAS_TR1_TUPLE=0 -std=c++11  -Werror -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fcf-protection=full -fno-strict-aliasing -fPIC -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -dynamiclib -Wl,-headerpad_max_install_names  -o translations/libtranslations.dylib -install_name @rpath/libtranslations.dylib translations/CMakeFiles/translations.dir/translations_autogen/mocs_compilation.cpp. …
```

cmake: link translations target with Qt5::Core

---

src/main/filter.cpp

This reverts commit baff7f213f07b7ae134062cd54b22c691f48fbe4.
This is broken without private Qt headers. With qmake this was easy to add (`gui-private`), I did not figure out how to do it with cmake so I will revert this instead of having broken debug build.

Revert "Animation slow down for debugging"

---

CMakeLists.txt
src/CMakeLists.txt

Co-authored-by @perfect-daemon
- easylogging
- epee
- EXTRA_LIBRARIES
are used by wallet_api and monero-gui directly so we explicitly link to them.

cmake: link with wallet_api instead of wallet_merged

---

CMakeLists.txt

Compilation fails due to `-Werror` and clang warning about `-fstack-clash-protection` not existing.

cmake: don't add fstack-clash-protection with clang

---

CMakeLists.txt

Fixes #3322 (even just as a workaround), alternatively I could add `-Wno-error=tautological-constant-out-of-range-compare` flag.

cmake: move external subdir before -Werror

---

pages/Transfer.qml

Changes:
- Fix y position of horizontal line dividing recipients
- Fix y position of elements in bottom row, so that 0.00 USD stays vertically aligned with the "0.00" placeholder when a new recipient row is added
Before:
After:

Transfer: fix y position of recipient elements

---

components/InlineButton.qml
pages/Transfer.qml

Changes:
- Display "XMR" unit at the right side of amount field when transaction has a single recipient. This is the most common type of transaction and the "XMR" unit should definitely be displayed somewhere on this page.
- Send all button: moved it next to the Amount label, in a position consistent with the buttons of Address label.
- Send all button: hide tooltip when clicking, so the user can see that amount field was filled with `(all)`.

Transfer: add XMR to amount of transaction with single recipient

---

components/DatePicker.qml

`styleData.valid = true` means the date is between minimum and maximum dates of calendar component. Since we're not setting minimum and maximum dates yet (will be implemented in another PR), `styleData.valid` will always return `true`.

DatePicker: highlight selected date/today; hide invalid days

---

components/DatePicker.qml

Go to previous/next month with mouse wheel (a lot faster than clicking on left/right arrows)

DatePicker: support mouse wheel to navigate months

---

pages/History.qml

This PR fixes this bug: 
1) Open sortAndFilter on a wallet with txCount > 0
2) Close this wallet and return to main menu
3) Open another wallet with txCount = 0
4) sortAndFilter is still being displayed, when it shouldn't

History: close sortAndFilter when exiting Transactions page

---

pages/settings/SettingsLog.qml

Changes:
- Remove command examples from translation string. Many translators have translated the "help" and "status" commands, but they should be in entered in English.
- Better wording

SettingsLog: new placeholder text in command field

---

components/DatePicker.qml

Changes:
- Date input doesn't change width anymore when calendar pop up is open
- Add +50 ms to duration of calendar pop up animation
- Move up calendar rectangle, so that it looks like a dropdown (consistent with StandardDropdown component)

DatePicker: date input with fixed width; longer animation; move up calendar

---

components/Slider.qml

Closes #3242
I tested on Android 11.

Slider: use MoneroComponents.TextPlain instead of Text on label

---

pages/settings/SettingsLog.qml

Closes #3475
Changes:
- Fix text color bug on theme switch (#3475)
- New warning text color (orange darker than previous orange, for better contrast on light theme)
- New green text color (dark green, for better contrast on light theme)

SettingsLog: fix text color bug on theme switch; new warning/green text colors

---

components/LineEdit.qml
components/RemoteNodeEdit.qml
pages/History.qml
pages/Transfer.qml
pages/settings/SettingsLog.qml
wizard/WizardWalletInput.qml

Required for #2637
Currently LineEdit uses an Item{} component while LineEditMulti uses a ColumnLayout{}. 
This PR modifies LineEdit component to use ColumnLayout{}. This is useful because we can set its properties (like margins) with the same values of a neighbor LineEditMulti component.
This modification requires some changes to LineEdit components in Transfer and WizardWalletInput.
Other changes:
- Removing unused inlineIcon
- inputHeight changed to 39 (the same as LineEditMulti)
- Add paste button

LineEdit: use ColumnLayout instead of Item

---

js/Utils.js
pages/settings/SettingsInfo.qml
wizard/WizardCreateDevice1.qml
wizard/WizardRestoreWallet1.qml

Fixes #3207
Probably the best solution is to use two fields, one for date and another for restore height, but let's use this PR as a temporary fix.

SettingsInfo, WizardRestoreWallet1, WizardCreateDevice1: Correct date typed in a wrong format

---

components/StandardDropdown.qml
pages/Transfer.qml
pages/settings/SettingsLayout.qml
wizard/WizardHome.qml

closes #2205
Main changes:
- use ColumnLayout instead of Item (consistent with LineEdit component)
- use same height of LineEdit component (39 pixels)
- include dropdownLabel on StandardDropdown
- set maximum width for dropdowns on WizardHome and SettingsLayout pages

StandardDropdown: use ColumnLayout; include dropdownLabel

---

pages/Transfer.qml

Changes:
Don't overlap inside borders: 
Before:
After: 
Height is the same as Transaction Priority dropdown (42 pixels)

Transfer: don't overlap inside borders; fix margins

---

components/StandardDropdown.qml
pages/Transfer.qml

- use ArrowCursor (default mouse cursor for dropdowns on Windows, Mac, and Linux)
- remove rotation of dropdownIcon (default behavior of dropdown icon on Windows, Mac, and Linux)
- change background color on mouse hover
- smaller text (from 16 to 14)

StandardDropdown: use ArrowCursor; remove rotation of dropdownIcon; change background color on mouse hover; smaller text

---

components/StandardButton.qml

Fixes following warning that shows up during transaction creation password dialog:
```
2021-05-13 17:47:33.234	W qrc:/components/StandardButton.qml:140:9: QML Image: Cannot open: qrc:/components/
```

StandardButton: fix warning with fallbackicon

---

main.qml

The redundant assignment removes the binding from `appWindow.walletMode` which is something we don't want.

main: remove redundant assignment

---

pages/History.qml

Currently it's possible to type on Search text field when Sort & Filter section isn't collapsed.
With this PR, if the user starts typing when "Sort & Filter" section isn't collapsed, it will collapse automatically.

History: collapse "Sort & Filter" when user types

---

components/RemoteNodeList.qml

RemoteNodeList: reduce spacing between icons

---

pages/Transfer.qml

closes #2613
Changes:
- use LineEdit instead of LineEditMulti (fixes #2613)
- decrease fontsize from input and placeholder from 18 to 16
- Add "(only visible to you)" to placeholder

Transfer: UI changes to description field (use LineEdit, decrease font size, new placeholder)

---

components/LanguageSidebar.qml
main.qml

Changes:
- navigate (Up/Down/Tab/Backtab) and select (Enter/Return/Space) languages with the keyboard
- add selected indicator (orange bar on the left side)
- accessible names (screen reader reads language) (tested with NVDA on Windows)
- remember and restore previous item focused

LanguageSidebar: navigate with keyboard; enable accessibility; selected indicator; remember previous item focused

---

components/TxConfirmationDialog.qml

closes #3597
Recipients text is using fontMonoRegular, and for some reason it is not displaying the string "<0.01" because it contains "<".

TxConfirmationDialog: fix displaying of "<" when using fontMonoRegular

---

components/LineEdit.qml
wizard/WizardCreateDevice1.qml
wizard/WizardCreateWallet1.qml
wizard/WizardRestoreWallet1.qml
wizard/WizardWalletInput.qml

Changes:
- Display red border if Wallet name is blank, invalid or already exists
- Display red border if Wallet location is blank
- Verify Wallet name field when Wallet location is updated
- Remove placeholders "-" and "..."
- Smaller font size (from 18 to 16)
- Increase width of Wallet location (usually the path is larger than the text field)
- Use icon for browse button (currently some languages have text larger than the button; using icon is also better for mobile)
- Error messages ("Wallet name is empty", "Wallet name is invalid", "Wallet already exists", "Wallet location is empty")

WizardWalletInput: red border if error; error messages; del placeholders; smaller font; use icon for browse button

---

pages/AddressBook.qml

- Add "Grab QR code" inline button, which will import address and recipient name. This is specially useful for QR codes asking donations (see QR code of https://grapheneos.org/donate).
- Import only address and recipient name when scanning QR code with camera (removed importing tx description).

AddressBook: add Grab QR code inline button

---

pages/Transfer.qml

Currently text cursor is orange when address field is blank, but this color should only be used when there is an invalid input.

Transfer: use defaultFontColor for text cursor when address field is blank

---

pages/AddressBook.qml
src/libwalletqt/AddressBook.cpp
src/libwalletqt/AddressBook.h

Requires https://github.com/monero-project/monero/pull/6828

AddressBook: description edits, remove hack

---

pages/Transfer.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Requires https://github.com/monero-project/monero/pull/7678
Resolves #2816

Transfer: add support for outputs import / export

---

.github/qt_helper.py
.github/workflows/build.yml

Advantages over the currently used script:
- script now automatically retries on download / connection failure (this has happened multiple times in the past now)
- script verifies sha256sum of qt download
Second one is important as we upload the binaries.
I can move the script to an external repo but inside the .github folder it shouldn't annoy anyone.

workflows: replace qt download script for macos-bundle

---

src/CMakeLists.txt

- `common` was introduced in https://github.com/monero-project/monero-gui/pull/2942
- `net` was introduced in https://github.com/monero-project/monero-gui/pull/2799

cmake: explicitly link net and common

---

fonts/FontAwesome/FontAwesome.qml
wizard/WizardAskPassword.qml

Changes:
- Move password strength meter below the password field
- Password strength meter bar changes color from red (low) -> yellow (medium) -> green (high)
- "Password (confirm)" field borders change to red when password doesn't match
- Add "password match/doesn't match" message below the confirmation password field
Success example: the user types a strong password (password strength bar changes color from red -> yellow -> green). Next, the user types a password confirmation that matches. No error is displayed, everything is green, and "Next" button is enabled.
Failed example: the user types a partial password confirmation that doesn't match. When the user types a wrong character, "Password (confirm)" field shows red borders and a red error message is displayed. "Next" button stays …

WizardAskPassword: add colors to password strength meter; add "Passwords match/do not match" message

---

pages/Receive.qml

Receive: remove highlight of QR code menu if no item is hovered

---

README.md

Official GUI releases use monero-wallet-gui from the docker build process documented in the monero-gui README, alongisde the supporting binaries from the deterministic CLI builds. This should be noted for users looking for verify GUI builds against official releases.

Add note about GUI releases to README.md

---

components/LineEdit.qml

LineEdit: fix eye button overlap on password field

---

Makefile
README.md

The `README.md` build instructions for Linux don't work as advertised on ppc64le systems, because `x86-64` is hardcoded in the Makefile target that the instructions say to use.  This PR adds a new target that uses `ppc64le` instead, and amends the build instructions to clarify that the `release` target is specific to `x86-64`.
I can confirm that this fixes the build for me on my Talos II Workstation.
Thanks to whoever maintains the Void PowerPC packages of Monero for helping me figure out what was wrong and how to fix it.

Makefile: Add ppc64le target

---

pages/Mining.qml

Mining: add buttons/mouse scroll to CPU threads; improve button labels; set "Start mining" button as primary

---

main.qml

Steps to reproduce the bug:
- In Settings > Interface, enable "Display wallet name in title bar"
- Close the wallet and open the main menu
- Open a wallet from file
- Enter an incorrect password in password dialog and click on Ok button
- Wallet name will appear on title bar, and it will persist on wizard mode, even if you click on Cancel button

main: hide wallet name in wizard title bar

---

components/PasswordDialog.qml

Steps to reproduce the bug:
- Open the main menu
- Open a wallet from file
- Click on Cancel button in password dialog
- Title bar will change to the wrong state ("default") instead of the correct one ("wizard")

PasswordDialog: display wizard title bar when returning to wizard after canceling password dialog

---

main.qml

hide TitleBar when MerchantTitleBar is visible (while in Merchant mode, the buttons on the left were clickable and opening tooltips)
"visible" property is already set for titleBar component in line 1900 of main.qml

main: hide TitleBar when MerchantTitleBar is visible

---

main.qml

When daemon is started/stopped while the wallet is being closed, the following error appears:
`W qrc:/main.qml:733: TypeError: Cannot call method 'connected' of undefined`

main: check if currentWallet is loaded before calling it

---

components/RemoteNodeList.qml

A reconnect is necessary to apply changes after editing a remote node that is currently connected.

RemoteNodeList: reconnect after editing remote node

---

components/SettingsListItem.qml
pages/settings/SettingsWallet.qml

Monero GUI freezes if "Rescan wallet balance" button is clicked while wallet is being synced.

SettingsWallet, SettingsListItem: disable "Rescan wallet balance" button if wallet is not synced

---

components/RemoteNodeList.qml

```
2021-12-13 03:26:11.850	W qrc:/components/RemoteNodeList.qml:92: TypeError: Cannot read property 'trusted' of undefined
```

RemoteNodeList: fix qml warning

---

wizard/WizardHome.qml

WizardHome: restore binding of networkTypeDropdown.currentIndex when selecting an item; display networkTypeDropdown if stagenet or testnet is selected

---

wizard/WizardController.qml
wizard/WizardCreateWallet4.qml
wizard/WizardRestoreWallet4.qml

If the user double-clicks the "Create wallet" button on the last page of "Restore wallet from keys or mnemonic seed", the wallet is created, but Monero GUI will display an error and the temporary wallet name will be displayed:
An error will also be displayed when double-clicking "Create wallet" button on the last page of "Create new wallet from hardware", but in this case Monero GUI will not display the temporary wallet name.
"Create new wallet" page doesn't have this problem.
This PR disables double-clicking on the "Create wallet" button on WizardRestoreWallet4.qml and WizardCreateWallet4.qml.

WizardRestoreWallet4, WizardCreateWallet4: disable double-click on "Create wallet" button

---

MiddlePanel.qml
js/TxUtils.js
main.qml
pages/TxKey.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Closes #3826 
This change adds the ability to prove and check a reserve proof
to this existing "Prove/check" advanced menu. If the amount line has
a valid amount less than that of the current account index this input
will drive the logic for generating a reserve proof. Checking a reserve
proof is accomplished by validating the address and verifying that
signature.indexOf("ReserveProofV") === 0. The result displays the total
and spent amount of the proof.

Advanced: ReserveProof: Add support for reserve proof

---

wizard/WizardHome.qml

Closes #3818
When changing network type without changing
wallet path the gui will attempt to open the
most recently used wallet path and network type
even if they don't match. This commit forces the
user back to wallet setup under this condition.
As long as network type and wallet path are both
updated before closing the issue will no longer occur.

bug: reset wallet path on network change 

---

main.qml

Closes #3836 
The enter / return key is not bound to the information
popup that appears after a successful password change.
The functionality exists on the previous menu. Make it
possible to use the return key on this popup as well.

settings: bind return key after password change

---

src/qt/updater.cpp

Don't have much knowledge about this error but it seems to have occurred before in [PR #2294](https://github.com/monero-project/monero/pull/2994). Logs show to include winsock2.h and the build fails at the updater.cpp file.
<details>
<summary>
logs
</summary>
<code>
from D:/a/monero-gui/monero-gui/src/qt/updater.cpp:35:
</code>
<br />
<code>
D:/a/_temp/msys64/mingw64/include/winsock2.h:15:2:
</code>
<br />
<code>
warning: #warning Please include winsock2.h before windows.h
</code>
<br />
<code>
[-Wcpp] 15 | #warning Please include winsock2.h before windows.h
</code
</details>

workflows: fix windows build error

---

CMakeLists.txt

Version still updates fine on cmake invocation.

cmake: remove unneeded monero_gui_add_library()

---

CMakeLists.txt

If someone wants verbose make they can set the env var.
This is now in line with monero's behaviour.

cmake: don't print verbose make

---

CMakeLists.txt

There is no `/usr/include/malloc` on macOS and it builds fine without.
Also CMP0042 always exists with out minimum version, no need to check for it explicitly.

cmake: remove including non-existent directory

---

README.md

What I've done is I copied the result of the same experiment from Core: the minimized list of the required boost libraries.
This helps the package maintainers.

Doc: Minimize boost deps in README.md

---

components/SettingsListItem.qml
components/TitleBar.qml
fonts/FontAwesome/FontAwesome.qml
main.qml
pages/settings/SettingsWallet.qml

Closes #3857 
This commit adds the ability to lock the wallet on demand instead
of waiting for the user inactivity time out. It is binded to the
hot keys Ctrl+L. Pressing cancel or the esc key will send the user
back to the wizard home for wallet selection. Incorrect password
returns the error message. Correct password will remove the
PasswordDialog allowing access. Add lock functionality in the
wallet settings section and title bar.

SettingsWallet: lock wallet on demand

---

components/RemoteNodeDialog.qml

Closes #3842
This commit binds the enter / return key on the remote
node dialog. If cursor is in the host, port or password
input fields the keyboard can be used to continue. It is not
bound to the username field because ideally a user would
enter password or port last.

RemoteNodeDialog: bind ok to return key

---

pages/Transfer.qml

Transfer: fix offline signing

---

pages/AddressBook.qml

Closes #3866 
If `currentWallet.addressBook.addRow` was successful the code would go into the edit description branch which is not what we want.

AddressBook: fix adding new entry

---

components/NetworkStatusItem.qml
main.qml
pages/Mining.qml
src/CMakeLists.txt
src/main/main.cpp
src/p2pool/P2PoolManager.cpp
src/p2pool/P2PoolManager.h

Integrates P2Pool and XMRig mining into the mining panel.
Allows for custom launch arguments and side-chain selection.
Closes #3714

Integrate P2Pool

---

components/TitleBar.qml

The lock functionality is shown on the initial welcome screen
and the WizardHome. Remove the lock icon until the wallet is
actually open, similar to the "Close this wallet" logic.
Fixes 346913f: ("SettingsWallet: lock wallet on demand")
I don't open this screen often so just noticed lock icon is there.

TitleBar: Remove lock icon on essentials display

---

pages/Mining.qml

Due to a bug the GUI was constantly checking the mining status every two seconds, no matter if the mining page is open or not.

Mining: only update mining status when page is open

---

components/TxConfirmationDialog.qml

TxConfirmationDialog: warn high fees

---

Makefile

https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html
> Typical values include Debug, **Release**, RelWithDebInfo and MinSizeRel, but custom build types can also be defined.
> Depending on the situation, the value of this variable may be treated **case-sensitively** or case-insensitively.

Makefile: set CMAKE_BUILD_TYPE to debug for debug target

---

wizard/WizardCreateDevice1.qml

Due to API reasons height 0 means to approximate the current block height during hardware device restore. That's not what we want by default. Until this gets changed upstream we will set the default to 1.
https://github.com/monero-project/monero/blob/v0.17.3.2/src/wallet/api/wallet_manager.cpp#L145-L149

WizardCreateDevice1: set default restore height to 1

---

main.qml
pages/History.qml

Closes #3909 
Adding support for reserve proof added an additional
argument to the getProofClicked signal. The payment
proof button on the transaction list from history.qml
does not pass this argument and fails with insufficient
argument error.
Fixes: 0f67580e ("Advanced: ReserveProof: Add support for reserve proof")
Temporary fix: Use Advanced tab on the GUI or use CLI to generate tx proof (`OutProof`)
Edit: tested locally using docker reproducible build against master branch

History: fix payment proof button

---

src/main/main.cpp
src/qt/TailsOS.cpp
src/qt/utils.h

qt: replace QRegExp with QRegularExpression

---

src/p2pool/P2PoolManager.cpp

Currently the GUI attempts to kill p2pool whenever it is closed, even if the instance of p2pool it is trying to kill wasn't started by it.
Changed to only kill it if we started it.

p2pool: Only kill p2pool if we started it

---

fonts/FontAwesome/FontAwesome.qml
pages/settings/SettingsWallet.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Requires https://github.com/monero-project/monero/pull/8356
So far only added the option to scan for a single transaction.

SettingsWallet: add scan transaction option

---

main.qml

closes #3962 , title could use a little work, its for the local daemon running in the background as `./monerod --stagenet`
selsta suggested a better 1 liner instead of a new line: thanks   
```C++
switch (parseInt(networkType))
```
solution # 2 is to change `var` to `int` but the root cause of this problem remains unknown 
https://github.com/monero-project/monero-gui/blob/b26f38d37ed81e84e51199425a633bc517f7bec2/main.qml#L1378

convert nettype to int to return correct rpc port

---

src/qt/KeysFiles.cpp

in #3774 wallet files containing a dot not being visible was reported. @rbrunner7 also mentions that their wallet files contain ".wallet" at the end. 
after i found the relevant place in the source where this is handled, selsta suggested "suffix" rather then "completeSuffix". I then noticed the full filename was still missing in the menu - using "completeBaseName" solved this 
I also tested naming a wallet .keys but this is handled correctly by (assuming) wallet2 somewhere (the .keys is stripped from the cache file)

display wallet files with "." in name

---

.github/workflows/build.yml
Dockerfile.linux

No idea what they did and why `f662e3a93ebdec3d1c9374382dcc070093a42fed` fails to checkout.
https://gitlab.freedesktop.org/xorg/util/xcb-util-m4/-/commit/f662e3a93ebdec3d1c9374382dcc070093a42fed is still reachable.
I manually verified the changes between the two commits.

docker: fix linux build

---

main.qml
pages/settings/SettingsLayout.qml

Closes #3732
Needs good testing as I had issues with settings resetting after running this patch.

Settings: option to skip stop local node screen

---

js/TxUtils.js

Closes #3975
Add parseFloat() checks so that the 'Resolve' button
for OpenAlias remains hidden. Also add a length check
for one character with a dot. IP addresses will not be
respected, but the whole point of domain names and OA is
for facilitating human readable / user friendly information.

TxUtils: don't show resolve for float

---

pages/settings/SettingsInfo.qml

If you accidentally copy and paste a date with a new line character 
```
2022-01-01
```
The gui will restore from 2022. I ran into this problem when helping someone just now, after giving them the correct date to copy and paste so they can restore quicker xD caused some confusion.
the reg exp method used here https://github.com/monero-project/monero-gui/blob/064c145aa8dc68d28ac8b4aa04ae8b4dbad2e2ce/wizard/WizardRestoreWallet1.qml#L277 prevents you from copy and pasting the 'wrong' string which might be annoying - but may be the required 'real' fix for this input too?

trim restore height at info -> change height input

---

main.qml

Should solve issues with monerod taking a while to exit. Simple mode nodes aren't beneficial to the network anyway, so having no incoming connections in some cases should be fine.

main: add --no-igd to simple mode flags

---

src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Works together with the fixes in Monero PR https://github.com/monero-project/monero/pull/8585.
The most significant fix in this PR is that it prevents the GUI from getting stuck in an infinite "Connecting" loop when connecting to a non-existent (or sometimes offline) daemon.
It also fixes some jank (and *some* of the incorrect underlying behavior) when switching nodes. The underlying async behavior still isn't perfect, but it's a move in a better direction. See the demos below.
*Not shown: connecting to `1.2.3.4:18081` takes 20 seconds to time out and display "Disconnected"*
*Not shown: connecting to `1.2.3.4:18081` gets stuck infinite "Connecting"*

Fix behavior when switching nodes

---

Dockerfile.android

this avoids executing downloaded binary without checksum verification

Docker android: avoid gradle auto download

---

components/NetworkStatusItem.qml
main.qml
pages/Mining.qml
pages/settings/SettingsLog.qml
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h

DaemonManager: take dataDir into account when sending cmd

---

.github/verify_p2pool.py
.github/workflows/verify_p2pool.yml

selsta spotted "path" instead of "paths" in the workflow file - i missed this so it would run on every pull/push, and also offered suggestions on extra features (e.g. verify the pgp key fingerprint)

workflows: verify p2pool hashes

---

src/main/oshelper.cpp
src/main/oshelper.h
src/qt/KeysFiles.cpp
wizard/WizardController.qml

closes #4069
at open wallet file menu, if you click "Browse Filesystem" and open a .keys file - you will see an error if the networktype differs to the current one. Opening via the wallet icons adjust the network type automatically before opening.
to confirm: 
- all wallet icons are assigned their correct network type / open correctly as normal @ open wallet file menu.
- any wallet keys file opened via "Browse Filesystem" does not complain about a different network type.
(var networktype breaks things if i try "int" - although parseInt is still not required)
selsta is helping / offering advice for v1..2..- this is v5.0 >_<

open-wallet: set network type when using file browser

---

qml.qrc
qtquickcontrols2.conf

Resolves #3938 
Forces "Desktop" theme for qtquickcontrols.

Override desktop theming

---

main.qml
pages/Mining.qml
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h

Resolves #3911 and may resolve #3935

p2pool: Restart monerod only when needed and with proper args

---

js/Utils.js

Fix issue where the minutes display is shown when delta is 3600 (one hour) and the hour display is shown when delta is 86400 (one day).

Utils: simplify ago func

---

pages/Mining.qml
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h

#4122 for me, 'double clicking' the monero gui binary leads to monerod being launched as a dbus.service. running it from the terminal. i did not notice this on Mint but i would sleep easier if this check was disabled for now until a better method of detecting if monerod is running under systemd or not.

DaemonManager: remove systemd check

---

README.md

monero-gui has been moved from community packages to extras packages. Current Arch Linux package link results in 404. Fixed the link to point to extras package.

Fixing broken link to Arch Linux package repo

---

.github/workflows/flatpak.yml
share/org.getmonero.Monero.desktop
share/org.getmonero.Monero.metainfo.xml
share/org.getmonero.Monero.yaml

A new release will trigger the workflow. It builds the flatpak package in 3 parts (because of slow QEMU), prints hashes and pushes to Flathub via the secret token.

flatpak: Add workflow

---

cmake/Deploy.cmake

Required for self compiled Qt 5.15.9 + ARM macOS.

cmake: add install_name_tool to fix svg rendering

---

cmake/Deploy.cmake

Required for macOS ARM binaries.

cmake: copy missing boost lib, run codesign

---

.github/workflows/build.yml

Avoids a crash when running the .app on Apple Silicon.

workflows: set default arch for macOS bundle

---

main.qml
pages/settings/SettingsWallet.qml

EDIT: also ensures GUI simple mode and bootstrap mode users default to "untrusted" daemon
1. Update balance after calling `scanTransaction` in order to reflect correct balance along with https://github.com/monero-project/monero/pull/8566
2. Display clear error when user is connected to an untrusted daemon and requests to scan a tx that is older than their wallet's most recent tx.

SettingsWallet: Update scan transaction for changes to behavior in monero repo PR 8566

---

.github/workflows/build.yml

Clears up ~9.3 GB of unneeded files. Should mitigate "No space left on disk" errors for Docker runs: https://github.com/monero-project/monero-gui/actions/runs/6388428621
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   64G   20G  77% /
546M	/usr/share/miniconda
1.9G	/usr/share/swift
2.2G	/usr/share/dotnet
4.7G	/usr/local/.ghcup
```

workflows: free up diskspace for docker builds

---

src/daemon/DaemonManager.cpp

Not necessary after https://github.com/tevador/RandomX/pull/281
This reverts commit 6c4a8fb81938b5067e23c819393ad272aaa01537.

Revert "DaemonManager.cpp: disable JIT on macOS ARM"

---

cmake/Deploy.cmake

msys2 package manager doesn't have mingw64 debug DLLs for libicu anymore so I removed them.
https://packages.msys2.org/package/mingw-w64-x86_64-icu-debug-libs

cmake: fix deploy by updating libicu version

---

README.md

Void Linux decided to remove all cryptocurrency related packages including Monero from their official repositories. See https://github.com/void-linux/void-packages/pull/44422
Added instructions for NixOS: https://search.nixos.org/packages?channel=23.11&show=monero-gui&type=packages&query=monero

Remove instructions for Void Linux, add NixOS

---

src/qt/TailsOS.cpp

Tails 6.0 removed the `TAILS_PRODUCT_NAME` variable.

tails: fix detection

---

DEPLOY.md

Having `~` in `CMAKE_PREFIX_PATH` somehow caused Qt to not be found.

DEPLOY: add more dependencies, use full path in prefix

---

wizard/WizardRestoreWallet4.qml

replacement for #4346 
closes #4341 
simpler and functionally better

wizardRestore: blindly (re)enable create wallet button

---

Dockerfile.linux

https://savannah.gnu.org/ apears to be temp offline

Dockerfile.linux: freetype.git mirror

---

.github/workflows/build.yml

for macos-bundle workflow
python version bundled with mac has been messed with (assuming for security reasons) so attempting to create a venv dir fails, there surely is a workaround. 
a quicker option is to use [pyenv](https://realpython.com/intro-to-pyenv/) to provide vanilla python versions
we now get to the [POD error](https://github.com/monero-project/monero-gui/actions/runs/11191661096/job/31114822680?pr=4366#step:6:1119), hooray!

build.yml: pyenv vcs for python

---

Dockerfile.linux

Dockerfile linux: fix boost download url

---

Dockerfile.android

**JIT relocation overflow ?** 
Don't know exactly what's happening (stg like [article](https://maskray.me/blog/2023-05-14-relocation-overflow-and-code-models)), but here's the error without moving librandomx's order in the linker's command :
```
[ 89%] Linking CXX shared library ../android-build/libs/arm64-v8a/libmonero-wallet-gui_arm64-v8a.so
ld: error: /monero-gui/monero/external/randomx/src/jit_compiler_a64_static.S:370:(.text+0x33C4): relocation R_AARCH64_CONDBR19 out of range: 2747184 is not in [-1048576, 1048575]; references randomx_program_aarch64_main_loop
>>> defined in ../monero/external/randomx/librandomx.a(jit_compiler_a64_static.S.o)
```
Moving librandomx to the beginning results in bigger offset, it builds (and runs) fine when put at the end 
(Didn't find a clean/easy cmake …

Docker android: upgrade dependencies

---

src/main/oshelper.cpp

This PR changes the current address check, which currently checks for addresses that start with either the character 9 or B. I believe that the letter A is supposed to be here instead of B. I have not been able to find any information on the proper starting characters for testnet addresses, so this could be incorrect. However, if this is the case, then half of all testnet addresses are unable to be used, as the current code only checks for an address to either be stagenet or testnet before assuming it to be mainnet. This too is a separate object of concern, although I do not know if there are any significant issues with allowing the function to continue past this point with invalid addresses.

Fix the testnet address check

---

cmake/Deploy.cmake

same as https://github.com/monero-project/monero/blob/master/CMakeLists.txt#L1048

Win deploy: Boost Regex is header-only since 1.77

---

CMakeLists.txt

build: set cxx standard to 17 in dev mode

---

.github/workflows/build.yml
CMakeLists.txt
README.md
cmake/Deploy.cmake

- Bump ICU dlls versions
- Fix Boost version detect
- Add [missing](https://github.com/monero-project/monero-gui/actions/runs/13504984377/job/37732379598#step:4:2138) libGLES [dependency](https://packages.msys2.org/packages/mingw-w64-x86_64-angleproject)

ci: fix MSYS2 build

---

.github/workflows/build.yml

Requires #4426 merged first.
`macos-latest` uses ARM which causes compilation issues.

workflows: fix CI bundle build and name spelling

---

main.qml

Updated the blockchain size to better reflect the current size. I wasn't 100% sure of the exact size, so I used https://docs.getmonero.org/technical-specs/#current-blockchain-size (Updated 2025-04-05) as reference and added 5GB to both the pruned and full values to get a rough estimate.

main: Update blockchain size

---

components/PasswordDialog.qml
main.qml
pages/History.qml
pages/settings/SettingsLayout.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Pairs with https://github.com/monero-project/monero/pull/8619
- In a wallet's settings, a user can check "Sync in the background when locked". This setting is not supported for view only or HW wallets.
- When checked and the wallet is locked, the password dialog indicates "Syncing in the background...". The wallet wipes the spend key from memory and continues syncing without it.
- NOTE: without this PR, today's GUI ALREADY syncs in the background when locked. This new setting ensures that the wallet wipes the spend key from memory when syncing when locked. Even if the setting isn't checked, the wallet still syncs in the background. Perhaps there is a cleaner way to portray this feature in the UI than "Sync in the background when locked"
- When the wallet is locked, the spend key ideally …

Feature: sync in the background with just view key when locked
