monero-core.pro
qml.qrc
wizard/WizardCreateWallet.qml
wizard/WizardDonation.qml
wizard/WizardFinish.qml
wizard/WizardMain.qml
wizard/WizardOptions.qml
wizard/WizardPassword.qml
wizard/WizardPasswordInput.qml
wizard/WizardWelcome.qml

Implemented "wizard path 1" with following exceptions:
- settings is not saved to any file actually, only in runtime object
- "password strength" indicator is statically initialized and doesn't depend on actual password
- there's no "disabled" state for "next" button, currently button just hidden if something preventing to go to next page.

Wizard path 1 according specifications

---

pages/Dashboard.qml
pages/History.qml
translations/monero-core_de.ts

Please verify format, QT crashed and i had to edit it via Notepad++.
Note: Data could be cleaned up, still some CSS and HTML in it and a lot of duplicates
P.S.: Seems like it works now, sorry for the inconvenience

German localization & typos

---

build.sh
get_libwallet_api.sh
monero-core.pro
utils.sh

Option to link with libunwind on non-Ubuntu distros

Unwind config option

---

build.sh
get_libwallet_api.sh
main.cpp
main.qml
monero-core.pro
utils.sh
wizard/WizardCreateWallet.qml
wizard/WizardFinish.qml
wizard/WizardMain.qml
wizard/WizardOptions.qml
wizard/WizardWelcome.qml

- daemon address and testnet can be selected in wizard now (might be not 100% right place, but still);
- removed "password logging"

Wizard: Select daemon address

---

build.sh
components/ProcessingSplash.qml
get_libwallet_api.sh
main.cpp
main.qml
monero-core.pro
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h
utils.sh
wizard/WizardCreateWallet.qml
wizard/WizardFinish.qml
wizard/WizardMain.qml
wizard/WizardOptions.qml
wizard/WizardWelcome.qml

Depends on https://github.com/monero-project/monero/pull/1136,
Fixes https://github.com/mbg033/monero-core/issues/56 (https://gyazo.com/1fd20b3d15975eb649adb78892a05c16)

Display BC sync progress in UI

---

README.md

There was a typo in the mac instructions, here's the fix.

Update README.md with fixed typo in path to QT

---

main.qml

Merge conflict broke restore from seed in GUI.

fix variable namings

---

main.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h
wizard/WizardMain.qml
wizard/WizardRecoveryWallet.qml

To be reviewed by @medusadigital before merge.

Continue wallet recover if sync is not finished

---

main.qml

Temporary (?) fix for https://github.com/monero-project/monero-core/issues/28
@mbg033 Should this be handled in the libwallet instead?

validation unlockedBalance

---

src/libwalletqt/TransactionHistory.cpp

TransactionHistory: fix date appearing as NaN

---

pages/Transfer.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

Needs https://github.com/monero-project/monero/pull/1229

Transfer: disable Send button if the payment id is invalid

---

pages/History.qml
pages/Transfer.qml

Minor grammar/formatting changes to Transfer and History

---

main.qml

+  prevent wallet from loosing wallet restore state.

prevent wallet from saving cache before first block is received

---

main.cpp
main.qml
pages/Settings.qml
src/libwalletqt/Wallet.cpp
wizard/WizardCreateWallet.qml
wizard/WizardMain.qml
wizard/WizardManageWalletUI.qml
wizard/WizardOptions.qml
wizard/WizardPassword.qml
wizard/WizardRecoveryWallet.qml
wizard/WizardWelcome.qml

- Added close wallet button on settings page which fires up the wizard
- added "Open from file" option in wizard
- Changed default wallet path to $HOME[/Documents]/Monero/wallets (Documents on windows)
- Changed default account name to system env user account
- various bug fixes and improvements

Wallet picker

---

main.qml
pages/Transfer.qml

Change default mixin to 4 & add mixin # to confirmation window

---

components/PasswordDialog.qml
components/StandardButton.qml
main.qml
pages/Settings.qml

Fixes issue https://github.com/monero-project/monero-core/issues/86

Custom password dialog. fixes issue with standard dialog

---

main.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

To fix following scenario when refreshing against daemon that isn't fully synced
synchronizing block 1 150'000/1 140'000

Use daemon target height in progress ui

---

MiddlePanel.qml
main.qml

Fixes https://github.com/monero-project/monero-core/issues/91

Disable transfer page when daemon isn't connected or fully synced

---

wizard/WizardFinish.qml

I have restyled the wizard's finish page, as I think the labels should be aligned. For this, I used a `<table>` (see screenshot).

Restyles the wizard's finish page

---

components/PasswordDialog.qml
components/StandardButton.qml
main.qml
pages/History.qml
pages/Settings.qml

Sort by date actually sorts by datetime, so transactions sorted properly within single day

Fix sort by date

---

BasicPanel.qml
MiddlePanel.qml
components/HistoryTable.qml
components/StandardDialog.qml
main.qml
pages/Transfer.qml
qml.qrc
src/libwalletqt/PendingTransaction.cpp
src/libwalletqt/PendingTransaction.h
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Will rebase after testing
Requires https://github.com/monero-project/monero/pull/1301

History page: added button+popup with tx details

---

main.qml

Related to errors mentioned in
https://github.com/monero-project/monero-core/pull/117

Prevent listeners from being attached multiple times

---

main.qml

Fixes https://github.com/monero-project/monero-core/issues/126

refresh history after daemon address change

---

LeftPanel.qml
components/NetworkStatusItem.qml
main.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

This will cause various errors confusing to the user, as they stem
for the daemon returning replies with missing information, etc.

Report when the GUI is connected to a daemon with mismatched version

---

pages/History.qml

History: default sorting by timestamp, desc. Fixes https://github.com/monero-project/monero-core/issues/98

History: Fix sort by date

---

components/DatePicker.qml
pages/History.qml

Date & amount filter validation; Payment ID input validated with hexadecimal regex

History: Fix filter validation

---

lang/languages.xml
translations/monero-core_it.ts
wizard/WizardWelcome.qml

Added the italian translation for some labels

Italian Translation

---

main.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

+ show waiting... message when waiting for transaction to finish. 
fixes https://github.com/monero-project/monero-core/issues/130 and https://github.com/monero-project/monero-core/issues/116

asynchronous transaction

---

pages/History.qml
src/libwalletqt/TransactionInfo.cpp
src/libwalletqt/TransactionInfo.h
src/libwalletqt/WalletManager.h
src/model/TransactionHistoryModel.cpp
src/model/TransactionHistoryModel.h

due to floating point operations

Fix sum of selected transactions being slighty off

---

main.qml

Fixes default settings.
related to https://github.com/monero-project/monero-core/issues/151 and also https://github.com/monero-project/monero-core/issues/153

Fix default configuration settings

---

MiddlePanel.qml
main.qml
pages/Transfer.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Needs https://github.com/monero-project/monero/pull/1310 and https://github.com/monero-project/monero-core/pull/129 and https://github.com/monero-project/monero/pull/1307

Add a button to sweep unmixable outputs

---

components/ProcessingSplash.qml
main.qml

- make it possible to close popup and exit program
- ensure correct message is shown in popup

Refresh progress ux

---

LeftPanel.qml

See issue 159: https://github.com/monero-project/monero-core/issues/159

Rename 'Transfer' tab to 'Send'

---

LeftPanel.qml
main.qml

As requested in https://github.com/monero-project/monero-core/issues/141

Title-bar: auto-hide disabled

---

pages/History.qml

This ensures an empty/invalid field does not keep the old bound

History: reset filter before setting new values

---

components/TitleBar.qml

Alternative solution to https://github.com/monero-project/monero-core/pull/188

Clean exit on app close button

---

main.cpp
monero-core.pro
pages/Receive.qml
src/QR-Code-generator/BitBuffer.cpp
src/QR-Code-generator/BitBuffer.hpp
src/QR-Code-generator/QrCode.cpp
src/QR-Code-generator/QrCode.hpp
src/QR-Code-generator/QrSegment.cpp
src/QR-Code-generator/QrSegment.hpp
src/QR-Code-generator/Readme.markdown
src/libwalletqt/QRCodeImageProvider.cpp
src/libwalletqt/QRCodeImageProvider.h

This embeds MIT licenced code from Project Nayuki:
https://www.nayuki.io/page/qr-code-generator-library
The C++ part of the code is embedded in src/QR-Code-generator.
See src/QR-Code-generator/Readme.markdown for more info.

Add QR code display on the receive page

---

main.qml

progress bar showed every 1000th block on refreshing after switching wallets.

Fix sync progress ux issue after switching wallets

---

LeftPanel.qml

https://github.com/monero-project/monero-core/issues/166

tab separator inconsistency 

---

components/DaemonProgress.qml
components/MenuButton.qml
main.qml

redesigned to fit smaller screens. 
https://github.com/monero-project/monero-core/pull/193

Daemon progress bar redesign

---

pages/Settings.qml

Enter default value in port in settings page

Enter default value in port in settings page

---

components/PrivacyLevelSmall.qml
components/TickDelegate.qml
pages/Transfer.qml

Users are unlikely to know the link

Add fee multiplier info to priority levels

---

wizard/WizardConfigure.qml
wizard/WizardMemoTextInput.qml

https://github.com/monero-project/monero-core/issues/213

Wizard: remove msg about confirmation dialog

---

wizard/WizardMain.qml

Wizard: fix wrong wallet loaded in open from file

---

translations/monero-core_in.ts

Hindi translation file.  Some text formatting issues may exist.

Add Hindi translation file monero-core_in.ts

---

components/HistoryTable.qml
monero-core.pro
src/libwalletqt/TransactionHistory.h
src/libwalletqt/TransactionInfo.cpp
src/libwalletqt/TransactionInfo.h
src/libwalletqt/Transfer.h
src/model/TransactionHistoryModel.cpp
src/model/TransactionHistoryModel.h

Fixes #229
Also added Transfer class for later use.

Show destinations in tx details popup

---

translations/monero-core_ja.ts

I tried my best to convey the meanings, but I was confused by this sentence:
Payment ID&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;A unique user name used in&lt;br/&gt;the address book. It is not a&lt;br/&gt;transfer of information sent&lt;br/&gt;during the transfer
I guess the address book feature is yet to be implemented, but I believe Payment ID does get transferred and stored in the blockchain (either with or without encryption). What's the intent of this text?
Another confusing sentence: `Kickstart the Monero blockchain?` - what does it mean to kickstart a blockchain?

added japanese translation

---

MiddlePanel.qml

Tabs: page transition left to right

---

README.md

README-OSX: Add xcode workaround

---

translations/monero-core_de.ts

Updates german translations

---

main.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h
wizard/WizardCreateWallet.qml
wizard/WizardRecoveryWallet.qml

Should fix #230
- added mutex lock on open/close wallet
- Make sure only one wallet can be open at same time
- make sure wallet doesn't get closed multiple times-> crash
- removed commented out code from main.qml

Fix random crashes on wallet close/open

---

pages/Settings.qml

Settings: show error msg on wrong pw input

---

MiddlePanel.qml

Fix basic layout

---

src/libwalletqt/Wallet.cpp

Use daemon height if target height = 0

---

LeftPanel.qml
MiddlePanel.qml
components/AddressBookTable.qml
components/TableDropdown.qml
main.cpp
main.qml
monero-core.pro
pages/AddressBook.qml
pages/Transfer.qml
src/libwalletqt/AddressBook.cpp
src/libwalletqt/AddressBook.h
src/libwalletqt/PendingTransaction.h
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h
src/model/AddressBookModel.cpp
src/model/AddressBookModel.h

Requires https://github.com/monero-project/monero/pull/1434

AddressBook

---

main.qml
src/libwalletqt/Wallet.cpp

Requires https://github.com/monero-project/monero/pull/1452

Attempt to fix rare crash when switching wallets

---

pages/Settings.qml

Simplified (shortened) original seed description, then added emphasis (exclamation point) that users should keep their seed secret. Original seed description didn't communicate this need for privacy.
Also added that the seed has "restore" functionality.

Clarified and broadened Mnemonic Seed description

---

LeftPanel.qml
components/MenuButton.qml

Don't waste too much vertical space on the left menu

---

wizard/WizardMain.qml
wizard/WizardRecoveryWallet.qml

When stepping back from pw page and passwords don't match.

Wizard: Prevent user from getting trapped

---

lang/languages.xml

Just for testing. Do not merge until translations are approved

Enable translations

---

LeftPanel.qml
main.qml

Added/corrected shortcuts:
Ctrl-D : Dashboard (hidden)
Ctrl-S : Transfer (text "Send")
Ctrl-R : Receive
Ctrl-K : txKey
Ctrl-H : History
Ctrl-B : addressBook
Ctrl-M : Mining (hidden)
Ctrl-I : sIgn
Ctrl-E : sEttings
Due to the three names starting with "S", I propose to use the second letter for Sign and Settings.

Updates on shortcuts

---

translations/monero-core_id.ts

This will no doubt be pulled apart by a native speaker, but it's at least a first version which allows us to try to connect to some 300 million potential new users (Bahasa Indonesia + Bahasa Melayu + Bahasa Brunei are almost mutually intelligible)

Translation of Monero GUI into Bahasa Indonesia

---

linuxdeploy_helper.sh
monero-wallet-gui.pro

after build.sh is finished:
```
cd build
make deploy
```
This will copy all dependencies to bin folder and also create a start-gui.sh file

linux deploy scripts

---

build.sh
pages/Settings.qml
qml.qrc
utils.sh

Add git version to the settings page

---

components/DaemonManagerDialog.qml
main.qml
pages/Settings.qml
pages/Transfer.qml
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h

Adds field for startup flags on settings page and daemon manager popup. 
related to https://github.com/monero-project/monero-core/issues/280

Daemon startup flags

---

wizard/WizardWelcome.qml

Smaller fontsize on WizardWelcome

---

lang/languages.xml

Also no more Republic of Pouth Africa, which is admittedly a bit sad.

Change locales to ISO ALPHA-2

---

lang/languages.xml

Actually remove translations (temporary for beta)

---

components/AddressBookTable.qml

Fixes https://github.com/monero-project/monero-core/issues/327

Address book: fix tooltip label and visibility

---

build.sh
get_libwallet_api.sh
monero-wallet-gui.pro

Needs [PR1510](https://github.com/monero-project/monero/pull/1510) first
Here is a (not super clean :) ) [dockerfile](https://github.com/MoroccanMalinois/dockers/blob/master/android/monero-wallet-gui.dockerfile) to reproduce the build
(NB : it takes several hours and at least 11GB of free disk space)

Android build

---

pages/Settings.qml

consistent layout seed textarea

---

LeftPanel.qml

Fixes https://github.com/monero-project/monero-core/issues/355

Make GUI whale friendly

---

LeftPanel.qml
MiddlePanel.qml
main.qml

Should cut down on people wondering why their balance is wrong

Add "(syncing)" after balance when syncing

---

components/HistoryTable.qml
src/model/TransactionHistoryModel.cpp

History: show pending on top

---

components/HistoryTable.qml

Fixes #179 
History page still looks bad in compact mode, but that's another issue.

make history whale friendly

---

LeftPanel.qml

remove double menu separators

---

translations/monero-core_fi.ts

Should be at least somewhat accurate.

Finnish translation for GUI

---

pages/Receive.qml

Dependent field should go second. This also creates better differentiation of the Integrated address from the regular Address (which can sometimes confuse new users).

Moved PaymentID field above Integrated address field

---

LeftPanel.qml
components/HistoryTable.qml
main.qml
pages/AddressBook.qml
src/libwalletqt/TransactionHistory.cpp
src/libwalletqt/TransactionHistory.h
src/libwalletqt/TransactionInfo.cpp
src/libwalletqt/TransactionInfo.h
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h
src/model/TransactionHistoryModel.cpp
src/model/TransactionHistoryModel.h

Requires https://github.com/monero-project/monero/pull/1559
"Fixes" http://monero.stackexchange.com/questions/3318/why-does-it-take-about-5-minutes-for-a-transaction-to-register-on-the-network

History: Show unconfirmed transfers + num of confirmations

---

components/PasswordDialog.qml
components/StandardButton.qml
main.cpp
main.qml
monero-wallet-gui.pro
pages/Settings.qml
pages/Transfer.qml
qml.qrc
src/libwalletqt/PendingTransaction.cpp
src/libwalletqt/PendingTransaction.h
src/libwalletqt/UnsignedTransaction.cpp
src/libwalletqt/UnsignedTransaction.h
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h
wizard/WizardCreateViewOnlyWallet.qml
wizard/WizardMain.qml
wizard/WizardManageWalletUI.qml
wizard/WizardPassword.qml
wizard/WizardPasswordUI.qml
wizard/utils.js

requires https://github.com/monero-project/monero/pull/1541
Still working on the UX, but the main functions should be in place. 
1. Create a view only wallet (settings page)
2. Open view wallet and create a transfer, save with "Save tx" button
3. In original wallet, click "Sign tx" on send page and select the file
4. in view wallet, click "Submit tx" and select the signed tx file
Preferably the main wallet should be installed on an air gapped computer not connected to the internet. The tx files can be transfered on a usb stick or other removable device.

GUI cold signing + view wallet

---

build.sh

Also added version checking before building libwallet.

Update monero submodule to 16b8b66

---

wizard/WizardMain.qml

Wizard: fix recover bug

---

components/DaemonConsole.qml
components/LineEdit.qml
get_libwallet_api.sh
monero-wallet-gui.pro
pages/Settings.qml
qml.qrc
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

+ daemon status button
requires #1618

Send custom commands to daemon

---

pages/Receive.qml
src/libwalletqt/QRCodeImageProvider.cpp
src/libwalletqt/QRCodeImageProvider.h
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

save qrcode to file

---

get_libwallet_api.sh
utils.sh

This way it won't just bail on new platforms.

detect freebsd, build for armv7, configure general build for unkown platforms

---

components/DaemonConsole.qml
components/LineEdit.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h
wizard/WizardCreateViewOnlyWallet.qml
wizard/WizardCreateWallet.qml
wizard/WizardMain.qml
wizard/WizardManageWalletUI.qml
wizard/WizardMemoTextInput.qml
wizard/WizardOptions.qml
wizard/WizardRecoveryWallet.qml

requires #1618 and #1635
Also includes a small redesign of wizard.

Restore wallet from keys

---

LeftPanel.qml
main.qml

fix advanced hotkey + menu separators

---

README.md
build.sh
components/QRCodeScanner.qml
main.cpp
main.qml
monero-wallet-gui.pro
pages/AddressBook.qml
pages/Transfer.qml
qml.qrc
src/QR-Code-scanner/QrCodeScanner.cpp
src/QR-Code-scanner/QrCodeScanner.h
src/QR-Code-scanner/QrScanThread.cpp
src/QR-Code-scanner/QrScanThread.h

(I was not able to reopen the previous #399 because of force push)
Mooo, I still think you were right about the license. Copy/paste + delete lines may be considered as "derivative work" and not "code that uses". Anyway, i changed the code and removed the references.
I also made it optional at build time and only enabled by default for android, but should work on all platforms as long as Qt version >= 5.6 (tested on android and linux for 5.7 and 5.8) and ofc Qt camera works.

add qrcode scanner

---

translations/monero-core_fr.ts

The biggest one was a missing word.

Minor spelling corrections

---

wizard/WizardPassword.qml
wizard/WizardPasswordUI.qml

wizard: set focus to first pw field

---

translations/monero-core_fr.ts

Fixes #452 
ping @davidlatapie

remove &nbsp from french translation

---

wizard/WizardManageWalletUI.qml
wizard/WizardOptions.qml

wizard: field bg color

---

get_libwallet_api.sh
linuxdeploy_helper.sh
monero-wallet-gui.pro
pages/Settings.qml

settings: replace seed box with popup

---

main.cpp

Send all debug output to easylogger

---

monero-wallet-gui.pro

Qt already automatically adds -lGLESv2 for android

do not use -lGL for android

---

components/NetworkStatusItem.qml
components/ProgressBar.qml
main.qml
src/daemon/DaemonManager.cpp
src/libwalletqt/Wallet.cpp

Improved blockchain sync progress ui

---

main.qml
pages/Settings.qml
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

- kill monerod if not shut down after 10 secs
- ux improvements

Daemon manager improvements

---

components/LineEdit.qml
main.qml
pages/Settings.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

requires https://github.com/monero-project/monero/pull/1803

Daemon rpc login support

---

components/StandardButton.qml
main.qml
wizard/WizardCreateViewOnlyWallet.qml
wizard/WizardCreateWallet.qml
wizard/WizardFinish.qml
wizard/WizardMain.qml
wizard/WizardManageWalletUI.qml
wizard/WizardOptions.qml
wizard/WizardPassword.qml
wizard/WizardPasswordInput.qml
wizard/WizardPasswordUI.qml
wizard/WizardRecoveryWallet.qml
wizard/WizardWelcome.qml

Redesign of wizard to make it look good on smaller screens.

Wizard mobile redesign

---

components/PrivacyLevelSmall.qml

Removed negative letter space, removed bold, added mixed case, and increased font size. Much more legible.

Better styling for password meter

---

pages/Mining.qml

Fixes #499 and removes redundant "Manage miner" label

Better styling for Miner

---

translations/monero-core_nl.ts

These additions and fixes should complete the dutch translation. Made sure to have uniform translations and well created sentences (which was lacking).
Would be great if the dutch flag could be added as well!

Many fixes and additions to the dutch translation

---

translations/monero-core_fr.ts

To fix some visual issues like button texts going out of the buttons and overlapping.

Shorten some strings in french translation

---

components/TitleBar.qml
main.qml

fixes #509
+ removed animation when switching. Didn't look to good on some platforms.

Fix switching to basic layout

---

components/PasswordDialog.qml

Seed password not closing

---

src/libwalletqt/WalletManager.cpp

mining: make threads parameter optional

---

LeftPanel.qml
components/MenuButton.qml

Left panel is still dealing with space issues, so hopefully this added space helps.
Before:
After:

More space for LeftPanel

---

main.qml

To fit all flags added in #511

Increase wizard height

---

main.qml

Adjust unlocked balance waiting text

---

pages/Settings.qml

Trim daemon address

---

MainApp.cpp
MainApp.h
components/StandardDialog.qml
main.cpp
main.qml
monero-wallet-gui.pro

works on mac. needs to be tested on windows and linux @medusadigital

Confirm daemon running in background on exit

---

main.cpp
main.qml
pages/Mining.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

requires #1827
Added options for background mining and ignore battery. Options are hidden currently because background mining is not stable stable enough yet.

preparations for background mining

---

wizard/WizardPasswordInput.qml

Better (smaller) fontsize for password in wizard

---

pages/Receive.qml

change payment id description

---

README.md

I needed this on Ubuntu 16.10 x64, so I'm guessing it'll be necessary on 16.04 also.

Update Ubuntu 16.04 x64 dependencies

---

LeftPanel.qml

Adjust top margin when custom decorations are used

---

main.qml

Update history when new block is found

---

monero-wallet-gui.pro

Fixes the buildbot building but also improves host/target detection. Will wait for a buildbot build to see if the fix is sufficient!

Improved windows host/target detection and fixed buildbot building

---

README.md

Fixed compile instructions, or rather where the binaries will be.
I also updated supported / tested linux versions and consistently used x86 / x64 which is also how the beta 1 binaries are named.

Linux compile instructions

---

LeftPanel.qml
components/CheckBox.qml
components/StandardButton.qml
components/StandardDropdown.qml
components/TableDropdown.qml
components/TableHeader.qml
pages/Receive.qml
pages/Settings.qml

Adds some missing translations and fixes/improves some display bugs.

Add missing, fix and improve translations

---

LeftPanel.qml

Shows a label in upper left corner if wallet is a testnet wallet.

Add testnet label

---

translations/monero-core_id.ts

This will no doubt be torn to shreds by a native speaker, but it at least gives us a chance to reach them.

Updated translation for Bahasa Indonesia

---

translations/monero-core_nl.ts

Dutch translation update with help from Obit33

Dutch translation update

---

pages/Mining.qml

Improve text wrap on mining page

---

translations/monero-core_ar.ts
translations/monero-core_br.ts
translations/monero-core_de.ts
translations/monero-core_eo.ts
translations/monero-core_es.ts
translations/monero-core_fi.ts
translations/monero-core_fr.ts
translations/monero-core_hr.ts
translations/monero-core_id.ts
translations/monero-core_in.ts
translations/monero-core_it.ts
translations/monero-core_ja.ts
translations/monero-core_nl.ts
translations/monero-core_pl.ts
translations/monero-core_ru.ts
translations/monero-core_zh.ts

Translation files needed an update after last merged PR's.
Here's the [log](https://paste.fedoraproject.org/paste/aCXlMaQauKHYhLs2FsCFrF5M1UNdIGYhyRLivL9gydE=).

Updated translation files after latest PR merges.

---

pages/Mining.qml

Better copy for mining page

---

pages/Transfer.qml

Capitalize a few lowercase words on buttons

Small button improvements

---

translations/monero-core_ar.ts
translations/monero-core_br.ts
translations/monero-core_de.ts
translations/monero-core_eo.ts
translations/monero-core_es.ts
translations/monero-core_fi.ts
translations/monero-core_fr.ts
translations/monero-core_hr.ts
translations/monero-core_id.ts
translations/monero-core_in.ts
translations/monero-core_it.ts
translations/monero-core_ja.ts
translations/monero-core_nl.ts
translations/monero-core_pl.ts
translations/monero-core_ru.ts
translations/monero-core_zh.ts

Updated translation files for recent code changes.
Also improved dutch translations.
On  a side note, i think it would be wise to add some notes, on updating translations. Because each code change, changes the line numbers inside the files and each string change (might) invalidate previous completed work.
As to make sure translators don't miss the opportunity to add missing translations, a regular update of the files would be a good thing (as opposed to have them PR yet again for minor changes.
@fluffypony and @Jaqueeee  Is it possible to add a hook/integration for his purpose? The command which should run is 'lupdate -verbose monero-wallet-gui.pro' and it includes some logging. Or am i overlooking a issue with this idea?

Updated translation files and improved dutch

---

BasicPanel.qml

BasicPanel.qml Remove negative letter space

---

main.qml

Hide processing splash when transfer fails

---

pages/Settings.qml

Settlings.qml: Change "Save" button to "Connect"

---

translations/monero-core_nl.ts

Updated Dutch translation ahead of PR/596 and PR/597.

Dutch translation already updated for PR/596 and PR/597

---

lang/languages.xml

Lol. dutch =)
legboor ramona coaxiaal strobbe koraal atypisch luijten comfort nijenhuis rits nudorp **kipschnitzel** wijk withaar bemiddeld tiplijn expletief aambeeld appelaar ripdeal ruby zuur censeren doping atypisch

add dutch seed

---

README.md
components/QRCodeScanner.qml
main.cpp
main.qml
monero-wallet-gui.pro
src/QR-Code-scanner/QrCodeScanner.cpp
src/QR-Code-scanner/QrCodeScanner.h

Fix for #611 
Also referencing #524 #474

Make QtMultimedia dependency optional

---

translations/monero-core_zh-cn.ts
translations/monero-core_zh-tw.ts

Update translation including PR/596 ( replace save with connect)

Update zh_tw & zh_cn translations

---

README.md

Intructions for building the GUI with Gentoo Linux

---

src/daemon/DaemonManager.cpp

Fixes #642. Hopefully also #644

Fix issues related to spaces in path

---

lang/languages.xml
translations/monero-core_zh-cn.ts

I am a developer from China
This submission fixes some of the wrong translations, while making the translation more in line with the Chinese mainland's reading habits

translate to chinese zh-CN

---

lang/languages.xml

Needs PR #1983 to be merged in monero first

Activate Simplified Chinese as a wallet language option

---

pages/Settings.qml
src/libwalletqt/Wallet.h

Add option to view view/spend keys

---

components/DaemonConsole.qml
components/DaemonManagerDialog.qml
components/PasswordDialog.qml
components/StandardDialog.qml

Make dialogs draggable

---

pages/Settings.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

Rescan wallet cache

---

wizard/WizardMain.qml

Wizard: clear populated fields when stepping back to page 1

---

get_libwallet_api.sh
monero-wallet-gui.pro

add easylogging

---

main.qml

#658 introduced some weird behavior in desktop version.

Fix borked desktop size

---

lang/languages.xml

Change wallet languages to native names and scripts

---

build.sh
utils.sh

Fixes #701 
Outputs tag + commit hash on settings page:

fix version info

---

pages/Settings.qml

Was added in ios branch (not in beta 2).

Don't output seed to log.

---

pages/Settings.qml
wizard/WizardRecoveryWallet.qml

option to view seed on wallets recovered from keys

---

main.qml
pages/Settings.qml
pages/Transfer.qml

Fixes #635 
Fixes #700 (partly)

UX: move "rescan spent" to settings + rename button

---

main.qml
pages/Settings.qml
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h

Blockchain folder settings (data-dir)

---

translations/monero-core_de.ts

Combined my changes with those from @keledoro in PR #724

German translation fixes

---

translations/monero-core.ts
translations/monero-core_ar.ts
translations/monero-core_de.ts
translations/monero-core_eo.ts
translations/monero-core_es.ts
translations/monero-core_fi.ts
translations/monero-core_fr.ts
translations/monero-core_hi.ts
translations/monero-core_hr.ts
translations/monero-core_id.ts
translations/monero-core_it.ts
translations/monero-core_ja.ts
translations/monero-core_nl.ts
translations/monero-core_pl.ts
translations/monero-core_pt-br.ts
translations/monero-core_sv.ts
translations/monero-core_zh-cn.ts
translations/monero-core_zh-tw.ts

Simply ran `lupdate monero-wallet-gui.pro` to create this PR.

Updating all translation files to pick up new strings

---

translations/monero-core_it.ts

Ok, this time everything should be fine.     
- Typos edited
- updated many "unfinished" lines
- edited plurals and little mistakes (thanks @jonathancross )
I left a couple of "unfinished" lines because i'm not sure about the translation in that specific context

Italian translation updated

---

translations/monero-core_sv.ts

I have updated the swedish translation, with the latest strings in the translation file.

Update swedish translation

---

MiddlePanel.qml
main.cpp

Attempt to fix https://github.com/monero-project/monero-core/issues/761
requires #2101

Disabled update check

---

VULNERABILITY_RESPONSE_PROCESS.md

As discussed in Kovri meetings,IRC, and https://github.com/monero-project/monero/pull/1995: here is a formalized VRP. This VRP will aid us in working with researchers and HackerOne.
RFC, WIP.
**Edit**: Referencing https://github.com/monero-project/monero-site/pull/282 https://github.com/monero-project/meta/issues/39

Repo: add Vulnerability Response Process

---

android/README.md
android/docker/Dockerfile
android/docker/android.mk.patch
android/docker/androiddeployqt.patch

Add dockerfile for android NDK build

---

main.qml

Add window title

---

components/HistoryTable.qml
src/libwalletqt/TransactionHistory.cpp
src/libwalletqt/TransactionInfo.cpp
src/libwalletqt/TransactionInfo.h
src/model/TransactionHistoryModel.cpp
src/model/TransactionHistoryModel.h

History: Support coinbase txs

---

main.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

This ought to fix the black screen on startup some users are experiencing.

check updates async

---

MiddlePanel.qml

fix clipped height

---

translations/monero-core_zh-tw.ts

Update new strings and minor fix.

Update zh-tw translation

---

translations/monero-core_sv.ts

This pull request should provide an updated Swedish translation, with obsoleted translations removed.

Updated Swedish translation

---

translations/monero-core_ja.ts

Would appreciate /r/Monero 'XMR Contributor' flair for /u/xmrscott.

Finished translation for monero-core_ja.ts (until new strings are added)

---

components/TextBlock.qml
pages/Settings.qml
qml.qrc
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Adds wallet creation height and paths to log files on settings page.

settings: debug info

---

pages/Mining.qml

Fix mining status positioning

---

components/IconButton.qml

IconButtons are currently broken thereby the copy-to-clipboard function for most textboxes doesn't work. This PR fixes it.

Fix IconButton

---

translations/monero-core_ko.ts

Some corrections of contextually obvious mistranslations made.

Korean translation audit of monero-core_ko.ts

---

LeftPanel.qml

Add separator below Settings menu button

---

components/PrivacyLevel.qml
components/TickDelegate.qml
pages/Transfer.qml

Alternate fix of #863
(instead of #876) ping @MaxXor

make privacy level slider smoother

---

src/libwalletqt/TransactionHistory.cpp
src/model/TransactionHistoryModel.cpp

set required confirmations default to 10

---

pages/Settings.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

add option to change wallet creation height and rescan wallet cache

---

main.qml

As per @medusadigital 's comment:  https://github.com/monero-project/monero-core/pull/884#issuecomment-338959562

tx confirm password dialog: clear when cancelled

---

get_libwallet_api.sh

static debug build

---

pages/Settings.qml

[LOW priority] [UX misspelling]
Updated misspelling and added period.

[typo fix] Update Settings.qml

---

main.qml

Fix for tx confirm password not showing up

---

components/TickDelegate.qml

With this PR, both tx priority and tx privacy settings will have similar terminology.

Rename tx privacy "Normal" setting to "Default"

---

components/DaemonManagerDialog.qml

Change countdown for connecting to local daemon from 5 to 10 seconds

---

main.cpp
src/libwalletqt/AddressBook.h
src/libwalletqt/PendingTransaction.h
src/libwalletqt/TransactionHistory.cpp
src/libwalletqt/TransactionInfo.h
src/libwalletqt/Transfer.h
src/libwalletqt/UnsignedTransaction.h
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h
src/model/AddressBookModel.cpp

This resolves #979 by changing the file paths from wallet/wallet2_api.h to wallet/api/wallet2_api.h

replace wallet/wallet2_api.h with wallet/api/wallet2_api.h to compile

---

main.qml

This closes #925 and also fixes #979 as a necessity for me to compile. If I need to rewrite a little history and get rid of the commit for #979 I definitely can.

Hide balance when in the receive tab

---

lang/languages.xml

wallet_language value in languages.xml broke proper seed generation

czech translation, seed generation fix

---

translations/monero-core_de.ts

Reviving #1026. Work done by @Schnoffel with a few fixes from myself as noted by @erciccione.

German translations

---

translations/monero-core_fr.ts

Up to date since #1076
~~Line 1156 still needs to be translated~~

Update FR translations

---

translations/monero-core_he.ts

I've updated the Hebrew translation.
Now all fields should be translated. The difficulty in Hebrew is that it is a right-to-left language so in some cases it's difficult to make it look good. I did my best and it seems to be fine now. I compiled and tested myself. Any feedback is welcomed and i'll try to do my best to fix / improve.

Update Hebrew Translation

---

translations/monero-core_sv.ts

Updated Swedish localization after merge #1076

---

translations/monero-core_it.ts

@serhack do you mind giving it a review?

Update Italian translation

---

main.qml
pages/Settings.qml
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h
wizard/WizardDaemonSettings.qml

Bootstrap daemon (requires #3165)

---

pages/Settings.qml
wizard/WizardDaemonSettings.qml

Note: I'm not super familiar with javascript and Qt. Hopefully this is right. It certainly takes care of the errors :)

Fix a few uses of undefined data on startup and exit

---

translations/monero-core_ja.ts

Updated Japanese translation for #1116

Update Japanese translation

---

monero-wallet-gui.pro

Compile with stack protector

---

lang/languages.xml
translations/monero-core_hr.ts

This PR recovers and fix conflicts in #1057 ( made by @TasmaniaKrama ) . I also added changes as suggested in my review ~~and added Croatian in `languages.xml`, so that this language will be available to use once this PR will be merged (even if just partially translated)~~
Edit: ~~since this translation is partial and we have enough languages to fill the page containing the flags i re-removed croatian from languages.xml will add it back as soon as the file get translated more~~
Edit 2: ~~The `monero-core_hr.ts` file is being updated by another contributor, will remove WIP after his changes will be merged to this PR~~
**Edit 3:** PR now ready to be merged

Croatian Localization

---

main.qml
pages/Settings.qml

Related to issue https://github.com/monero-project/monero-gui/issues/1081

[Issue 1081] Fixed undefined variable for password rewrite when changing wallet initial block height

---

translations/monero-core_nl.ts

Plus a few corrections of older translations.
@fridzema already submitted another Dutch translation, so you're able to choose!
Who wants to review both translations and choose the best one, or suggest edits?
@rpcjacobs @potatored @dnaleor @dEBRUYNE-1

Dutch translation of GUI text added in January

---

LeftPanel.qml
components/ProgressBar.qml
main.qml
wizard/WizardDaemonSettings.qml

Separate progress bars for daemon and wallet
Also removed the old "sync local daemon while using a remote node" logic which has become obsolete after #1091

Two progress bars

---

lang/languages.xml

Thanks to reddit user res11 for clarifying

Display Arabic in Arabic (العربية) in menu

---

LeftPanel.qml

Bring back the 'unlocked balance' text for the balance card

---

MiddlePanel.qml

Increase panel height for the settings page

---

pages/Keys.qml

Key reuse warning

---

pages/Settings.qml

Fixes transparent dropdown

---

LeftPanel.qml
components/MenuButton.qml

Fixes misaligned symbols/shortcuts and changes Shared RingDB shortcut to 'A'

---

MiddlePanel.qml
main.qml

Reset scroll view on page change

---

components/ProgressBar.qml

Fixes a bug where progress bars were not 100% filled visually

---

README.md

qml-module-qtquick-controls2
qml-module-qt-labs-folderlistmodel

Updated README.md with new dependencies for Ubuntu 16.04+:

---

main.cpp

show a warning string with qt version, screen resolution, logical dpi and calculated ratio

replace qDebug for qWarning, lean message

---

pages/SharedRingDB.qml

put correct checkmark on SharedRingDB page

---

main.cpp

The name was changed a while back so it would make sense to update this

update ApplicationName to "monero-gui"

---

wizard/WizardFinish.qml

Fixes the second part of #1317

show correct address in wizard if remote node used

---

components/Input.qml
components/InputMulti.qml

Selection color for inputs

---

MiddlePanel.qml
components/LabelSubheader.qml
main.qml
pages/SharedRingDB.qml
pages/TxKey.qml

Fixes #1254
- Rearranged components
- Made the panel responsive (for mobile)

Redesigned shared ringdb panel

---

translations/monero-core_de.ts

Me and @falcongoat have been working on the german translations, as they were partly incorrect, incomplete or inconsistent. We went through the whole file and updated everything to the best stage we could.

Updated and completed german translations

---

components/TextBlock.qml
js/Utils.js
pages/Settings.qml

Reformat Settings->Debug Info

---

translations/monero-core_da.ts

Quick update for the danish translation

Update Danish Translation

---

components/RadioButton.qml
pages/Settings.qml
qml.qrc
wizard/WizardOptions.qml

Radiobuttons

---

monero-wallet-gui.pro
share/Info.plist

Fixes #1301 #829 
Needed to support URI schemes in the future.

add Info.plist template

---

translations/monero-core_ar.ts
translations/monero-core_cat.ts
translations/monero-core_cs.ts
translations/monero-core_da.ts
translations/monero-core_de.ts
translations/monero-core_eo.ts
translations/monero-core_es.ts
translations/monero-core_fi.ts
translations/monero-core_fr.ts
translations/monero-core_he.ts
translations/monero-core_hi.ts
translations/monero-core_hr.ts
translations/monero-core_id.ts
translations/monero-core_it.ts
translations/monero-core_ja.ts
translations/monero-core_ko.ts
translations/monero-core_nl.ts
translations/monero-core_pl.ts
translations/monero-core_pt-br.ts
translations/monero-core_pt-pt.ts
translations/monero-core_ro.ts
translations/monero-core_ru.ts
translations/monero-core_sk.ts
translations/monero-core_sl.ts
translations/monero-core_sr.ts
translations/monero-core_sv.ts
translations/monero-core_tr.ts
translations/monero-core_ua.ts
translations/monero-core_zh-cn.ts
translations/monero-core_zh-tw.ts

In average, there are 150 new strings and 75 were removed because obsolete

[0.12.1] Refresh all language files

---

wizard/WizardDaemonSettings.qml

Addresses the first part of #1338

make some daemon wizard wording more clear

---

README.md

Finally 64 bits and 64 bits only, Boost from MSYS2 package, Qt5 from MSYS2 package, as per release Lithium Luna

ReadMe: Updated Windows/MSYS2 compile instructions

---

wizard/WizardDaemonSettings.qml

Addresses the second part of #1338

use radio buttons for daemon wizard

---

translations/monero-core_ja.ts

Updated Japanese translations for #1377

Update Japanese translations for 0.12.1

---

translations/monero-core_sr.ts

As per issue https://github.com/monero-project/monero-gui/issues/1377

Updating Serbian translation

---

translations/monero-core_nl.ts

Update of the NL translation for release 0.12.1. according to issue #1377. Paging @erciccione.

Dutch translation

---

translations/monero-core_zh-tw.ts

Updated Traditional Chinese translations for #1377

Update Traditional Chinese translation for v0.12.1

---

translations/monero-core_es.ts

Updated spanish GUI translation

---

translations/monero-core_de.ts

Updated all strings for the point release.
Message to reviewers: Everything that's set to `type="unfinished"` currently is intentional as in my opinion the original string should be used for that.

German Translation for v0.12.1.0

---

translations/monero-core_eo.ts

Almost all new items translated here. Would new an esperanto-speaking peer review but it'll do for now.

Esperanto: Translation of new items

---

translations/monero-core_ro.ts

update of romanian translation

update of romanian translation

---

pages/Receive.qml
pages/SharedRingDB.qml

thanks @einsteinsfool for spotting them

[0.12.1] Fix typos in Receive.qml and SharedRingDB.qml

---

translations/monero-core_pt-br.ts

Update Brazilian Portuguese GUI translation for 0.12.1

---

components/DaemonConsole.qml

don't scroll to bottom after appending a new console message

---

translations/monero-core_sv.ts

Updated Swedish translation of GUI strings

---

translations/monero-core_sk.ts

Updates made by @fero-sk (see [#1377 comment](https://github.com/monero-project/monero-gui/issues/1377#issuecomment-389219793))

Update slovak translation

---

pages/Settings.qml

fix restoreHeightEdit is not defined.

fix restoreHeightEdit is not defined.

---

translations/monero-core_fr.ts

This is #1390 + the changes i suggested.
pinging @luigi1111

Recovering #1390

---

monero-wallet-gui.pro

require at least qt 5.7.0 when building the project

---

translations/monero-core_cs.ts

https://taiga.getmonero.org/project/erciccione-monero-localization/task/284

Update Czech translation for 0.12.1

---

translations/monero-core_ru.ts

This is erciccione/monero-core#3
It was opened on my repo by mistake and i saw it only today. It's technically correct and can be merged.

Russian Language GUI Update for v0.12.1

---

main.qml
pages/Settings.qml

same as #1454 , but for release branch

[Release]: Fix for frozen settings page

---

components/CheckBox2.qml
wizard/WizardOptions.qml

#1452 but PRd to the release branch

[Release] Add explicit mainnet button and move nettypes to advanced options

---

pages/Transfer.qml

Change "Default" fee level to "Automatic"

---

windeploy_helper.sh

https://github.com/monero-project/monero-gui/issues/1455

Update outdated libraries for windows build

---

LeftPanel.qml
main.qml

hotkey for "Shared RingDB" changed to CTRL+G instead of CTRL+A

---

pages/Keys.qml

use radio buttons for export wallet qr code

---

translations/monero-core_ua.ts

I am a 99 level noob with GIT, I hope that I did everything right.

Update Ukranian language for GUI 0.12.1

---

translations/monero-core_zh-cn.ts

Recovering #1445

---

components/PasswordDialog.qml

fixed: disable password dialog hotkeys handling when it is hidden

---

translations/monero-core_ru.ts

I've corrected typos @LvMsterfild made in Russian translation (PR #1427)
This PR is replacement of broken #1440

Fixed russian translation

---

translations/monero-core_es.ts

As discussed in monero-ecosystem/monero-translations issue 16
@lh1008  @BlackLotus64

Spanish: Consistent translation of term 'mining'

---

translations/monero-core_de.ts

Added unfinished translations; Reworked parts of existing translation, trying to make it easier to understand / nicer to read.

(180806  german translation)  monero core de.ts

---

monero-wallet-gui.pro

as per https://github.com/monero-project/monero/pull/4290

pro: disable -fstack-protector* on windows

---

LeftPanel.qml
js/Utils.js
main.qml

1. Add missing CTRY+Y hotkey handler
1. Don't change selected menu item on cancel
1. Hover "Keys" menu item and display "Keys" page on success

fixed "Keys" CTRL+Y hotkey

---

translations/monero-core_zh-tw.ts

@erciccione @0140454 Would you like to give a review?

update zh-tw translation for v0.13

---

translations/monero-core_pl.ts

Polish translation update partially solving issue #1582.

Polish translation update for 0.13

---

translations/monero-core_sk.ts

sk lang. for 0.13
reference to (#1582)

Slovak Update monero-core_sk.ts

---

translations/monero-core_it.ts

ping @erciccione @hrumag @faudi @lancillotto 
reference to (#1582)

Update Italian Translations

---

translations/monero-core_fr.ts

This is French part for #1582.
I am actually resolving my msys2 dependencies to build and test, but it could be reviewed by French speakers @erciccione.

French translations for 0.13

---

translations/monero-core_de.ts

update german translation for 0.13

---

translations/monero-core_pt-br.ts

update pt-br for #1582

---

translations/monero-core_ar.ts

edit arabic localization

---

translations/monero-core_pt-pt.ts

#1582 request - updated pt_PT translation

#1582 request - updated pt_PT translation for 0.13

---

translations/monero-core_ja.ts

Updated Japanese translations for 0.13

---

translations/monero-core_zh-cn.ts

i18n: update zh-cn

---

translations/monero-core_he.ts

Translated whatever I could and also reviewed some of the already translated lines.
I didn't build the GUI, but Im confident that my translations are good.

Translation and corrections for Hebrew #1582

---

translations/monero-core_sr.ts

Updating Serbian language

---

translations/monero-core_sl.ts

* status: ready, will finish the checklist in a separate PR 
#1582

update slovenian translation:

---

translations/monero-core_sv.ts

Rebased Swedish translation. see #1609

Rebasing #1609 for 0.13

---

README.md

In preparation of 0.13; added libsodium install instructions for Debian/Gentoo.

Added libsodium to install instructions

---

get_libwallet_api.sh

In preparation of 0.13; bumping monero submodule tag to 0.13.
Fixes #1619

Bumping monero submodule tag to 0.13

---

translations/monero-core_sv.ts

I took the liberty to incorporate the changes suggested to the swedish translation in the review comments to PR #1609

Update Swedish translation with changes in PR #1609

---

translations/monero-core_id.ts

fix some malaysian language to Indonesian.

fix bad Indonesian translations.

---

windeploy_helper.sh

Update for latest msys2 build dll files

Dll update

---

translations/monero-core_bg.ts

The tag issue in Bulgarian translation file breaks build.

Fix tags in Bulgarian translation

---

windeploy_helper.sh

[0.13] Update outdated icu files

---

pages/Receive.qml
src/libwalletqt/QRCodeImageProvider.cpp

[0.13] Add border to generated QR codes

---

monero-wallet-gui.pro

[0.13] Fix build with smartcard

---

pages/Receive.qml
src/libwalletqt/QRCodeImageProvider.cpp

Add border to generated QR codes

---

pages/Receive.qml

fixed: UI is unresponsive while tracking incoming txes

---

translations/monero-core_uk.ts

Ukrainian translation for GUI 0.13 -- done
Ping @LvMsterfild @v1docq47 @erciccione 
---
ref [#1582](https://github.com/monero-project/monero-gui/issues/1582)

Ukrainian translation. GUI 0.13

---

pages/settings/SettingsInfo.qml

`parseInt` is more than enough here

settings: don't call parseFloat, isFinite to parse height 

---

translations/monero-core_id.ts

Update Indonesian Translation

---

components/PasswordDialog.qml
components/Style.qml
js/Utils.js
main.qml

password dialog: show error in place

---

LeftPanel.qml

left-panel: use consistent font size

---

translations/monero-core_cat.ts

Update Catalan translation

---

components/LineEdit.qml
components/RemoteNodeEdit.qml
pages/settings/SettingsNode.qml

settings: fix Remote Node 'Connect' button, validate port number range

---

pages/Receive.qml

receive: add Payment URL

---

pages/Receive.qml

- paymentURL field is now fully visible
- refactored makeQRCodeString
to align with transfer.qml changes,
- RegExpValidator updated 
- handles amounts starting with .

receive: qrcode, amountToReceiveLine validator, paymentURL improvements

---

pages/Keys.qml

- updated to follow wallet definition URI specification at https://github.com/monero-project/monero/wiki/URI-Formatting
- fixed incorrect currentwallet.address lookup
- fixed currentWallet.walletCreationHeight variable

keys.qml: bug fixes and updates to correct wallet definition URI scheme

---

MiddlePanel.qml
pages/Keys.qml

keys: dynamic panel height and qrcode is no longer clipped

---

components/TitleBar.qml

titlebar: hide titlebarLogo when mobile

---

pages/Sign.qml

sign: fix "signature" label layout for better UI consistency

---

clipboardAdapter.cpp
clipboardAdapter.h
components/LineEditMulti.qml
pages/Transfer.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

transfer: paste Payment URL to fill the payment form fields

---

wizard/WizardWelcome.qml

wizard: fix flags hovering, cursor, layout

---

components/CheckBox.qml

checkbox: remove a gap between rectangle and text, fix layout

---

components/Label.qml

Use Text.PlainText as default for Text

---

main.qml
pages/settings/SettingsLayout.qml

Hide balance setting

---

MiddlePanel.qml

MiddlePanel: fix color stripe z value

---

pages/settings/SettingsWallet.qml

settings-wallet: use StandardButton instead of custom buttons

---

components/LineEdit.qml

Transfer: fix amount label boldness

---

components/TitleBar.qml
main.qml

wizard: add close button by enabling titlebar

---

main.qml

main: hide Unlock time when switching wallets

---

components/CheckBox2.qml
components/LineEditMulti.qml
components/NetworkStatusItem.qml
components/PasswordDialog.qml
pages/Transfer.qml
pages/TxKey.qml
pages/settings/SettingsNode.qml
pages/settings/SettingsWallet.qml
wizard/WizardMain.qml

Going to fix all the warnings we have at the moment. Will split the fixes into multiple PRs, this is the first one.

fix various QML warnings

---

MiddlePanel.qml
main.cpp
pages/Mining.qml

mining: display max cpu thread count and warn about impact

---

MiddlePanel.qml

Package import requires a version number

---

components/StandardButton.qml

#1806 (1), https://github.com/monero-project/monero-gui/pull/1791#issuecomment-446353979

standard-button: handle changing text/icon at runtime

---

components/DaemonConsole.qml
pages/settings/SettingsLog.qml

SettingsLog: fix TextArea layout, border, scrollbar

---

MiddlePanel.qml

MiddlePanel: fix scrollbar margin top/bottom

---

components/InputMulti.qml
js/TxUtils.js
pages/Transfer.qml

openalias: handle address validation correctly

---

pages/Receive.qml

Receive: fix subaddress alignment

---

MiddlePanel.qml
pages/Sign.qml

Sign: redesign page with message/file toggle

---

main.qml

main: use custom daemon settings goes directly to settings>node page

---

components/CheckBox.qml

* Property to control icon alignment (left/right)
* Optional `uncheckedIcon` support (different icons for checked and unchecked states)
* Option to hide checkbox border

CheckBox: iconOnTheLeft property, optional uncheckedIcon and border, rich text format

---

src/model/TransactionHistorySortFilterModel.cpp

history: enable search by recipient address

---

pages/Keys.qml

Keys: add clipboard warning :speech_balloon:

---

pages/Transfer.qml

Also remove unnecessary row layout.
Before:
After:
Label and dropdown alignment is pixel perfect now :)

Receive: fix priority dropdown alignment

---

components/WarningBox.qml
wizard/WizardManageWalletUI.qml

Resolves #1550
Extends on #1821

wizard: add copying seed to clipboard warning

---

pages/Transfer.qml

Transfer: remove ability to transfer with detached short payment ids

---

components/HistoryTable.qml

HistoryTable: show address and address label in tx details

---

main.qml
wizard/WizardCreateWalletFromDevice.qml

requires monero-project/monero#5034

Wizard/Device: set estimated restore height if none is provided

---

components/NewPasswordDialog.qml
pages/settings/SettingsWallet.qml

SettingsWallet: readd change password button

---

components/HistoryTable.qml
components/HistoryTableInnerColumn.qml
pages/History.qml

history: enable set_tx_note

---

components/WarningBox.qml
pages/Keys.qml

- Use warningbox from MoneroComponents
- Make warningbox contents selectable

Use MoneroComponents for keys page

---

pages/History.qml

History: omit redundant 'Cancel' button in confirmation dialog

---

components/StandardDialog.qml

StandardDialog: make scrollable + close button

---

pages/merchant/MerchantCheckbox.qml

Merchant: fix checkbox

---

pages/Mining.qml
pages/SharedRingDB.qml
pages/Sign.qml
pages/TxKey.qml

This cleans up the pages under Advanced.
- Made sure they are uniform in terms of font-sizes and page layout.
- Refactored some layouts.
- Use `MoneroComponents.` where applicable.

Cleanup advanced pages

---

components/InputMulti.qml
pages/AddressBook.qml
pages/Transfer.qml

openalias: usability improvements on addressbook/transfer page

---

main.qml
pages/settings/SettingsNode.qml

settingsnode: enable trusted daemon option

---

main.qml
pages/settings/SettingsNode.qml
wizard/WizardDaemonSettings.qml

Fixes https://github.com/monero-project/monero-gui/issues/1940

Fix default daemon/remote node RPC port based on the network type

---

pages/Transfer.qml

Address input field indicative text based on nettype

---

wizard/WizardDaemonSettings.qml

Fix color for daemon settings radiobutton

---

main.qml

Main: fix changing language from settings

---

pages/AddressBook.qml

addressbook: fix placeholder text for stagenet/testnet

---

wizard/WizardController.qml
wizard/WizardCreateWallet2.qml
wizard/WizardRestoreWallet2.qml

Caught by @selsta and [reddit](https://old.reddit.com/r/Monero/comments/aubuma/gui_v01400_prerelease_test_binaries_buildbot/eh7xavz/)

Save password on wallet write

---

wizard/WizardController.qml

wizardController: cleanup restart variables

---

components/LineEditMulti.qml

Fixes https://github.com/monero-project/monero-gui/issues/1967

LineEditMulti: fix binding loop

---

pages/settings/SettingsWallet.qml

SettingsWallet: hide creating a view wallet for viewOnly wallets

---

js/Wizard.js
pages/settings/SettingsWallet.qml

#1964 
~~Getting `Imported outputs omit more outputs that we know of` that’s why it’s marked as do not merge.~~ Seems to be unrelated to this PR.

Settings: fix create view only wallet button

---

main.qml

Removing HTTPs for Windows

---

wizard/WizardCreateDevice1.qml
wizard/WizardSummary.qml

wizard: allow restore height when creating wallet from device

---

main.qml
wizard/WizardCreateWallet2.qml
wizard/WizardOpenWallet1.qml
wizard/WizardRestoreWallet2.qml

This reverts commit 632423da07a16b3131fd5427aa19d2608538c683, Windows simple mode should be fixed with #1980.

Revert "Dont show message on simple mode disconnect/reconnect"

---

pages/settings/SettingsLayout.qml

settingslayout: fix change language button does not change language

---

wizard/WizardController.qml
wizard/WizardCreateDevice1.qml
wizard/WizardSummary.qml

wizard: improve restore from device ui/ux

---

pages/Transfer.qml

transfer: messaging for disabled send button

---

pages/settings/SettingsInfo.qml

SettingsInfo: allow a date for restore height

---

pages/settings/SettingsNode.qml

settingsnode: fix trusted node flag

---

pages/Mining.qml

- Fixes layout issues with long text
- Fixes error with starting mining when daemon is not yet ready
- Changed soloSyncedLabel to MoneroComponents.WarningBox for more consistent look and feel.
before
after

mining: fix layout issues

---

components/HistoryTable.qml

historytable: fix blockheight copying

---

main.qml

Possibly helps with #2004
before
after

main: fix refreshing of language fields

---

js/Windows.js

Fix double titlebar

---

get_libwallet_api.sh

Preparation for v0.14.1.0
Requires monero-project/monero#5390

build: set monero submodule to master

---

components/PasswordDialog.qml
js/Utils.js

Fixes #881 
Improving user experience / usability.

PasswordDialog: add CAPSLOCK checking

---

wizard/WizardCreateDevice1.qml

Fixes overlap issue: https://user-images.githubusercontent.com/7697454/55501042-e10f7a00-5649-11e9-94b2-91bffd3df0ca.png

wizard: small UI fix

---

js/Utils.js
qml.qrc

Removes missing/unused image `dropdownDel.png` and fixes master by including PR 5355 for `get_libwallet_api.sh`

Fix master, remove unused image, requires #5355

---

wizard/WizardRestoreWallet1.qml
wizard/WizardWalletInput.qml

Fixes #2053 
Fixes viewName variable name wizardRestoreWallet1
Now clears sensitive fields at end of wizard restore workflow.

wizard: fix clearing of restore wallet fields

---

wizard/WizardController.qml
wizard/WizardDaemonSettings.qml

Scrolling like in `middlePanel.qml`
Fixes #2048

flickable for wizardController

---

components/NewPasswordDialog.qml
components/PassphraseDialog.qml
components/PasswordDialog.qml

Seems to fix #2054
Please test.
Let inactivity timer expire. Minimize window. Window stays minimized after timer is reached.

PasswordDialog: don't always show()

---

README.md

Done also in  monero-project/monero#5412

readme: update link to pootle and add guide for translators

---

README.md

Update README; Add Fedora instructions

---

pages/Transfer.qml

Transfer: warn if description is a valid PID

---

main.qml
wizard/WizardController.qml

device: fix hardware wallet creation / restore height

---

wizard/WizardController.qml

wizardhome: fix network dropdown

---

src/daemon/DaemonManager.cpp

support user defined max-concurrency

---

wizard/WizardRestoreWallet1.qml

wizard: allow viewonly wallet restores

---

pages/History.qml

IMO it‘s more useful this way.

History: improve human readable time format

---

components/NewPasswordDialog.qml
components/PassphraseDialog.qml
components/PasswordDialog.qml

components: hide password on dialog opening

---

lang/languages.xml

60% of the strings translated on Pootle. We will probably get some more for the 'call for translators' for the release

Activate Hindi language

---

wizard/WizardAskPassword.qml

Almost all icons are high DPI now.

wizard: replace icon with Font Awesome version

---

pages/settings/SettingsLayout.qml

[Qt 5.9] Use Slider.onMoved for inactivity slider, remove Timer

---

wizard/WizardCreateDevice1.qml

Else it will look like this in combination with white theme PR.
@ph4r05 Does this look correct? Is it getting hidden in a different place?

 wizard/device: hide splash screen

---

pages/settings/Navbar.qml

> Disco: I don't think "Layout" is a good descriptor of it's page. To me "Interface" sounds more like what it's settings affect.
Requires #2060

[Qt 5.9] Change settings navbar text: Layout -> Interface

---

installers/windows/Monero.iss

Together with the code for the GUI wallet itself from PR #2029 this implements custom URI schemes on Windows: The installer will register "monero:" and "moneroseed:" with Windows by writing corresponding registry entries.
As an advantage of letting the installer do this the two URI schemes will be deleted when uninstalling.

Windows installer: Set up 'monero:' and 'moneroseed:' custom URI schemes

---

components/NewPasswordDialog.qml
components/PassphraseDialog.qml
components/PasswordDialog.qml

components: remove show() from password dialogs

---

pages/Sign.qml

Updated based on user feedback.

sign: use radiobuttons to change modes

---

main.qml

Merchant: fix title bar with custom decorations turned off

---

pages/Transfer.qml

Transfer: warn when sending to a known long PID service

---

wizard/WizardCreateDevice1.qml

wizardcreatedevice: cleanup layout

---

components/NewPasswordDialog.qml
components/PassphraseDialog.qml

dialogs: fix titlebar disabledness

---

components/LabelSubheader.qml

labelSubHeader: fix width bug

---

main.qml

Else it errors here:
https://github.com/xmrdsc/monero-core/blob/dbe5b00ae5acf65c6c497014337c71ae98430f27/main.qml#L597

Check before disconnecting wallet

---

README.md

readme: add svg module

---

main.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Addresses #2123, reduces UI freezing on long-lasting operation, improves Trezor experience

transaction: async commit

---

README.md
windeploy_helper.sh

msys2: fix windows build with trezor

---

pages/Keys.qml

Localize and hide elements where applicable.

keys: ux improvements for hardware device wallet

---

main.qml

https://github.com/monero-project/monero/issues/5515

wallet: fix deadlock, omit invoking 'refresh' from callback

---

MiddlePanel.qml
pages/AddressBook.qml
pages/Mining.qml
pages/Sign.qml
pages/Transfer.qml
pages/TxKey.qml

MiddlePanel: dynamic content height

---

installers/windows/Monero.iss
installers/windows/README.md
installers/windows/ReadMe.htm

Small textual updates for the installer-related files to switch the version number from `0.14.0.0` to `0.14.1.0` for the upcoming point release

Windows installer: Update for Boron Butterfly 0.14.1.0

---

js/Wizard.js
pages/settings/SettingsInfo.qml
wizard/WizardCreateDevice1.qml
wizard/WizardRestoreWallet1.qml

wizard: Fix restore height when using stagenet/testnet

---

src/qt/KeysFiles.cpp

Affected Windows build
before
after

KeysFiles: fix file path

---

main.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Wallet: async fetching wallet, daemon and target height

---

js/Utils.js
pages/Keys.qml
pages/settings/SettingsInfo.qml
wizard/WizardCreateWallet1.qml

Restore height visibility enhancements

---

LeftPanel.qml
main.qml
pages/Keys.qml

This is now redundant since a "show seed" button has been added to the settings page which opens the keys page.

Remove Seed & Keys subtab in left panel

---

wizard/WizardHome.qml

wizardhome: add change network label

---

src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

Found by @MaxXor 
https://github.com/monero-project/monero-gui/pull/2180#pullrequestreview-245601691

WalletManager: remove unused functions

---

installers/windows/Monero.iss

To make the installed GUI package contain **all** the exe files from the CLI package as well, install 3 new exe files that were added between 0.14.0.2 und 0.14.1.0.

Windows installer: Add 3 new exe files (pruning, stats)

---

main.qml

main: fix UI freeze on close in remote node mode

---

MainApp.cpp

MainApp: send unhandled events to base class

---

pages/History.qml

History: allow to search for tx_note

---

pages/History.qml

History: dynamic number of tx rows

---

pages/History.qml

https://www.reddit.com/r/Monero/comments/c8eg6k/gui_v01410_boron_butterfly_with_ledger_nano_x_and/esptt3q/

History: don't reset date filtering when switching page

---

src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

txid list was empty when emitted

Fixes #2275, transactionCommited txid list

---

main.qml

Fixes https://github.com/monero-project/monero-gui/pull/2247#issuecomment-511543363

main: fix password dialog overlay

---

main.qml

main: don't lock on inactivity if passwordDialog is visible

---

src/qt/MoneroSettings.cpp
src/qt/MoneroSettings.h

Reverts changes made to MoneroSettings after testing.

Fix segfault on Tails

---

components/PasswordDialog.qml

[Dialog] button mod from Change wallet/Continue to Cancel/Ok

---

wizard/WizardAskPassword.qml

WizardAskPassword: improve label

---

pages/Account.qml

Account: fix theme switch label color

---

pages/Receive.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

- Fixes #2184 
- Requires https://github.com/monero-project/monero/pull/5594 to be merged to monero-core and monero submodule update

device: show address on device display

---

wizard/WizardController.qml
wizard/WizardCreateDevice1.qml
wizard/WizardCreateWallet1.qml
wizard/WizardCreateWallet2.qml
wizard/WizardCreateWallet3.qml
wizard/WizardCreateWallet4.qml
wizard/WizardHome.qml
wizard/WizardLanguage.qml
wizard/WizardModeBootstrap.qml
wizard/WizardModeRemoteNodeWarning.qml
wizard/WizardModeSelection.qml
wizard/WizardOpenWallet1.qml
wizard/WizardRestoreWallet1.qml
wizard/WizardRestoreWallet2.qml
wizard/WizardRestoreWallet3.qml
wizard/WizardRestoreWallet4.qml

Fixes:
- Setting `contentHeight = childrenRect.height` was resulting in a binding loop.
- Wrong transition on mode selection page.
- `<i>` tag in plaintext string.

wizard: bug fixes

---

pages/settings/SettingsNode.qml

SettingsNode: make button text more consistent

---

wizard/WizardRestoreWallet1.qml

WizardRestoreWallet1: use RadioButtons instead of buttons

---

main.qml

Fixes `E Trying to close non existing wallet  QObject(0x0)` error message (thanks to @selsta for reporting the issue).

main: don't attempt to close already closed wallet

---

pages/Receive.qml

I think QML doesn’t short circuit.

Receive: fix warning

---

main.qml
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h

Fixes annoying GUI freeze appearing before `Starting local node in N seconds` dialog.

daemon: async daemon status check, don't freeze on wallet startup

---

pages/History.qml

Fixes https://github.com/monero-project/monero-gui/issues/2267

history: fix start/end of the day calculation, apply local timezone

---

images/settings_local.svg
images/settings_remote.svg
pages/settings/SettingsNode.qml
qml.qrc

Replacing the current icons with these: https://github.com/monero-project/monero-gui/issues/2318#issuecomment-515025152, as the current icons were never intended to be used on this page.

SettingsNode: change icons

---

main.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h
wizard/WizardController.qml

Ledger: improve hw wallet splash screen

---

pages/settings/SettingsNode.qml

SettingsNode: make input read only

---

wizard/WizardLang.qml

Workaround for default window size until we have scrolling on this page.

WizardLang: reduce top margin

---

LeftPanel.qml
components/Style.qml
components/TitleBar.qml
fonts/FontAwesome/FontAwesome.qml
images/sidebar.svg
images/themes/white/expand.svg
main.qml
qml.qrc

To be used in combination with: #2383

TitleBar: add close wallet button

---

get_libwallet_api.sh
monero-wallet-gui.pro

Requires https://github.com/tevador/RandomX/pull/131 and https://github.com/monero-project/monero/pull/5939

build: build, install and link against randomx library

---

components/NetworkStatusItem.qml

Requires https://github.com/monero-project/monero-gui/pull/2398 https://github.com/monero-project/monero-gui/pull/2400

SimpleMode: implement "switch to another public node" button

---

pages/Transfer.qml

fix fee labels in transfer

---

components/CheckBox.qml
pages/settings/SettingsLayout.qml

Settings: fix 'Light theme' checkbox

---

monero-wallet-gui.pro

build: embed version metadata into binary

---

installers/windows/Monero.iss
installers/windows/ReadMe.htm

Requires https://github.com/monero-project/monero-gui/pull/2437

installer: automatically set app version information

---

LeftPanel.qml
components/LineEdit.qml
main.qml
pages/Transfer.qml

Transfer: convert and display entered amount in fiat currency

---

README.md

https://www.reddit.com/r/Monero/comments/dxfhqv/need_help_installing_gui_wallet/

readme: add 'zeromq-devel' to Fedora deps

---

components/ContextMenu.qml
components/ContextMenuItem.qml
qml.qrc

ContextMenu: styling, implement ContextMenuItem component

---

main.qml

AppWindow: append wallet name to window title

---

main.qml
pages/settings/SettingsNode.qml

Closes https://github.com/monero-project/monero-gui/issues/2455

main: ask whether to stop local node upon switching to remote node

---

pages/Transfer.qml

FIxes #2461
Once #2466 is implemented this can also display the converted all amount.

Transfer: fix NaN fiat conversion

---

components/Input.qml
components/InputMulti.qml

Closes https://github.com/monero-project/monero-gui/issues/2473

Input: fix cursor shape, should be 'Qt.IBeamCursor'

---

installers/windows/Monero.iss

Fixes https://github.com/monero-project/monero-gui/issues/2501

Installer: fix 'GUI Wallet Guide' shortcut target filename

---

main.qml

Fixes https://github.com/monero-project/monero-gui/issues/2478

main: omit onWalletRefresh call with uninitialized currentWallet

---

pages/AddressBook.qml
pages/settings/SettingsNode.qml
wizard/WizardCreateDevice1.qml
wizard/WizardDaemonSettings.qml
wizard/WizardHeader.qml
wizard/WizardLang.qml
wizard/WizardLanguage.qml
wizard/WizardOpenWallet1.qml

Closes https://github.com/monero-project/monero-gui/issues/2497

Wizard, AddressBook, SettingsNode: prevent undesired text selection

---

pages/settings/SettingsLayout.qml

SettingsLayout: pointing mouse cursor and selecting text

---

components/WarningBox.qml

WarningBox: hover cursor and disable selecting text

---

wizard/WizardHome.qml
wizard/WizardModeSelection.qml

wizard: Language button on home and add back button

---

pages/Transfer.qml

Transfer: add parenthesis to links

---

MiddlePanel.qml

https://github.com/monero-project/monero-gui/issues/2471#issuecomment-557847059 (Problem 2)

MiddlePanel: remove margin bottom

---

components/Label.qml

Label: change cursor on link hover

---

components/DatePicker.qml
pages/History.qml

Closes https://github.com/monero-project/monero-gui/issues/2514

DatePicker: don't propagate mouse events to underlying controls

---

components/StandardDropdown.qml

Closes https://github.com/monero-project/monero-gui/issues/2460

StandardDropdown: implement automatic closing

---

LeftPanel.qml
main.qml
pages/Account.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Closes https://github.com/monero-project/monero-gui/issues/2476
Fixes https://github.com/monero-project/monero-gui/issues/2550

Wallet: persistent subaddress account selection

---

pages/History.qml
pages/merchant/Merchant.qml

Fixes #2533
Partly addresses #2535

Translation: fix untranslated strings

---

pages/History.qml

Closes https://github.com/monero-project/monero-gui/issues/2552

History: add date, amount, integrated addr (incoming) to tx details

---

wizard/WizardAskPassword.qml

WizardAskPassword: fix lock icon

---

wizard/WizardRestoreWallet1.qml

WizardRestoreWallet1: fix placeholder text visibility

---

wizard/WizardLang.qml

WizardLang: fix display text

---

pages/Transfer.qml

Resolves https://github.com/monero-project/monero-gui/issues/2481

Transfer: improve amount sanitization

---

components/InputDialog.qml
pages/Account.qml
pages/History.qml
pages/Receive.qml
pages/settings/SettingsInfo.qml

InputDialog: pre-populate input text

---

components/InlineButton.qml
components/InputDialog.qml
components/PasswordDialog.qml
components/StandardButton.qml

components: handle enter and return

---

pages/settings/SettingsInfo.qml
src/main/oshelper.cpp
src/main/oshelper.h
src/qt/macoshelper.h
src/qt/macoshelper.mm

Partially addresses https://github.com/monero-project/monero-gui/issues/2474

SettingsInfo: open containing folder on wallet log path click

---

src/libwalletqt/TransactionInfo.cpp
src/libwalletqt/TransactionInfo.h

Related to https://github.com/monero-project/monero-gui/issues/2483

TransactionInfo: parse Wallet API provided data on initialization

---

main.qml
wizard/WizardController.qml

Fixes https://github.com/monero-project/monero-gui/issues/2585

WizardController: always close and re-open newly created wallet

---

src/libwalletqt/TransactionHistory.cpp
src/libwalletqt/TransactionHistory.h
src/libwalletqt/TransactionInfo.h
src/model/TransactionHistoryModel.cpp
src/model/TransactionHistoryModel.h

Related to https://github.com/monero-project/monero-gui/issues/2483

TransactionHistory: fix use-after-free bugs

---

main.qml
pages/Mining.qml
pages/Transfer.qml

do not ask to start daemon if in remote node mode

---

src/libwalletqt/SubaddressAccount.cpp
src/libwalletqt/SubaddressAccount.h
src/libwalletqt/Wallet.cpp
src/model/SubaddressAccountModel.cpp

Related to https://github.com/monero-project/monero-gui/issues/2483

SubaddressAccount: fix use-after-free bug

---

main.qml
pages/Transfer.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

Improve transfer warning flow

---

src/libwalletqt/Subaddress.cpp
src/libwalletqt/Subaddress.h
src/model/SubaddressModel.cpp

Subaddress: fix use-after-free on accessing stale Wallet API data

---

pages/Transfer.qml

Transfer: cleanup payment id code

---

components/DaemonConsole.qml
components/InputDialog.qml
components/PasswordDialog.qml
main.qml

Closes https://github.com/monero-project/monero-gui/issues/2586 #2564

main: blur on PasswordDialog, InputDialog or ProcessingSplash

---

pages/settings/Settings.qml
pages/settings/SettingsInfo.qml
pages/settings/SettingsLayout.qml
pages/settings/SettingsLog.qml
pages/settings/SettingsNode.qml
pages/settings/SettingsWallet.qml

closes #2471
No more unnecessary scrolling on the settings page.

Settings: fix page height

---

main.qml
pages/settings/SettingsWallet.qml

Fixes https://github.com/monero-project/monero-gui/issues/2611

SettingsWallet: cleanup on wallet close

---

.gitignore

QtCreator creates these for unsaved files. Anything else that can be added?

gitignore: Add *.autosave

---

LeftPanel.qml
components/MenuButton.qml

remove colored dots

---

main.qml

main: fix wallet lock is unlocked without password

---

main.qml

Otherwise the initial screen is never shown.

main: show wizard init screen when no wallet is found

---

main.qml

Set minimum window size

---

Makefile
get_libwallet_api.sh

Fixes https://github.com/monero-project/monero-gui/issues/2677

build: autodetect MSYS install path, support non-standard location

---

wizard/WizardCreateDevice1.qml

Being more specific about the supported models to avoid issues like #2685 in the future.

Add hardware wallet device supported models

---

.github/workflows/build.yml

Homebrew fails at installing `graphviz`.

workflows: fix macOS build

---

.github/workflows/build.yml

workflows: add windows support

---

main.qml

@xiphon Was this left out intentionally?

main: add blur to wizard password dialog

---

get_libwallet_api.sh

Fixes https://github.com/monero-project/monero-gui/issues/2609

build: support ARCH override for libwallet_merged

---

components/CheckBox.qml

CheckBox: fix word wrap on windows (Qt 5.13.2)

---

components/StandardDropdown.qml

StandardDropdown: remove dots from upper corners

---

pages/Account.qml

Account: update label after rename

---

.github/workflows/build.yml

Windows build is still failing but I’m looking into it.

workflows: fix ubuntu build and update checkout

---

LeftPanel.qml
components/NetworkStatusItem.qml
main.qml
pages/Transfer.qml
pages/merchant/Merchant.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Closes https://github.com/monero-project/monero/issues/6308

Wallet: implement 'Connecting' status, add 'disconnected' property

---

main.qml

```
2019-12-14 02:32:45.887 W qrc:/main.qml:683: TypeError: Cannot read property 'connected' of undefined 
```
Not sure if fix is 100% correct.

main: fix warning

---

LeftPanel.qml

LeftPanel: NetworkStatusItem fixed at bottom left corner

---

wizard/WizardHome.qml
wizard/WizardModeSelection.qml

Remove unnecessary period at Menu titles

---

wizard/WizardCreateWallet4.qml

Rename "Open wallet" button to "Create wallet"

---

pages/Transfer.qml

Transfer: import key images button always visible

---

pages/Keys.qml

Keys: add primary address to seed & keys page

---

installers/windows/Monero.iss

ping @rbrunner7, is this going to work when upgrading the next time? What will happen to the old shortcut?
Fixes #2583

installer: change blockchain folder string

---

main.qml
pages/AddressBook.qml
pages/Transfer.qml
pages/merchant/Merchant.qml
pages/settings/SettingsInfo.qml
pages/settings/SettingsNode.qml
wizard/WizardAskPassword.qml

misc: strip html out of translatable strings

---

monero-wallet-gui.pro
share/Info.plist

Ref: https://stackoverflow.com/a/19981753
Fixes #2334
Fixes #1578

macOS: add version to info.plist

---

share/Info.plist

macOS: add copyright notice

---

wizard/WizardController.qml

Closes https://github.com/monero-project/monero-gui/issues/2782

WizardController: invoke restart() after persistentSettings update

---

components/PasswordDialog.qml

PasswordDialog: don't skip equality check

---

pages/settings/SettingsNode.qml

Closes https://github.com/monero-project/monero-gui/issues/2790

SettingsNode: blockchain location 'Reset' button

---

components/MenuButton.qml

MenuButton: add hover effect

---

js/Utils.js
pages/Transfer.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Transfer: display estimated transaction fee, requires #6302

---

src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h
wizard/WizardController.qml
wizard/WizardRestoreWallet1.qml

Requires https://github.com/monero-project/monero/pull/6334

WalletManager: wallet recovery - seed offset passphrase support

---

components/StandardButton.qml
components/Style.qml
components/UpdateDialog.qml
main.qml
monero-wallet-gui.pro
qml.qrc
src/main/main.cpp
src/main/oshelper.cpp
src/main/oshelper.h
src/qt/downloader.cpp
src/qt/downloader.h
src/qt/network.cpp
src/qt/network.h

Will implement and commit signature and hash sum verification in a separate PR.

UpdateDialog: implement update download functionality

---

components/SettingsListItem.qml
pages/settings/SettingsWallet.qml

Only UI changes from https://github.com/monero-project/monero-gui/pull/2655

Settings: rework wallet page

---

LeftPanel.qml
fonts/FontAwesome/FontAwesome.qml
main.qml
pages/settings/SettingsWallet.qml

Settings: move Merchant menu entry

---

components/QRCodeScanner.qml

QRCodeScanner: don't load webcam on startup

---

main.qml
pages/settings/SettingsLayout.qml

Settings: add checkbox 'ask for password before sending a transaction'

---

pages/Transfer.qml

Moving address field to the top because estimated fee is only calculated after address and amount fields are filled. Also, most cryptocurrency wallets display address field before amount field.

Transfer: move address field to the top

---

pages/settings/SettingsLog.qml

Resolves #2593, speeds up startup.

SettingsLog: don't assign color to font family

---

pages/settings/SettingsInfo.qml

SettingsInfo: fix number string formatting

---

components/StandardDialog.qml
main.qml
pages/settings/SettingsInfo.qml

StandardDialog: reset button text on close

---

pages/merchant/Merchant.qml
pages/merchant/MerchantTrackingList.qml

- Confirmations would not show with untrusted remote nodes
- tx_pool check was buggy
- payment URL did not display
- Point out when amount is unconfirmed

Merchant: various bug fixes / small improvements

---

components/LineEdit.qml
components/PasswordDialog.qml
pages/settings/SettingsNode.qml
wizard/WizardRestoreWallet1.qml

Related: https://github.com/monero-project/monero-gui/issues/2700

LineEdit: password mode, linking. PasswordDialog: use LineEdit

---

components/Slider.qml
main.qml
pages/settings/SettingsLayout.qml
qml.qrc

SettingsLayout: implement autosave, enabled by default (10 minutes)

---

main.qml

Closes https://github.com/monero-project/monero-gui/issues/2888

SimpleMode: use connection timer 'running' prop, fix daemon restart

---

main.qml

Main: clear spendable funds msg when closing wallet

---

pages/merchant/Merchant.qml

Merchant: display size warning when window height < minHeight

---

src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

We already have `isLedger()` and `isHwBacked()` boolean functions.

Wallet: add isTrezor() function

---

main.qml

main: update balance only when wallet is synced

---

LeftPanel.qml

Didn’t know about `Binding on value` when writing this code.
Edit: I guess this could have been done with a simple if too but this might be a bit more clear.

LeftPanel: simpifly color binding

---

pages/settings/SettingsLayout.qml

https://www.reddit.com/r/Monero/comments/h9dhcy/maam_monero_ask_anything_monday_june_15_2020/fuxaej6/

SettingsLayout: ask password for password relevant setting

---

src/openpgp/hash.h
src/openpgp/openpgp.cpp

Resolves https://github.com/monero-project/monero-gui/issues/2907

openpgp: fix gcc 5.4.0 compilation

---

src/main/main.cpp
src/qt/NetworkAccessBlockingFactory.h

QML: disable networking

---

README.md

Ref: monero-project/monero-site#1010

README: update donation fund address

---

main.qml

This reverts commit 333c9ee311308df9086bd5200f692fefcebdfd47.

Revert "main: update balance only when wallet is synced"

---

DEPLOY.md
README.md

We can add Windows / Linux tutorials later once it is easier (docker, ...)

docs: add deploy readme

---

components/PasswordDialog.qml
main.qml

PasswordDialog already defines z as parent.z + 2

PasswordDialog: remove already defined z value

---

components/RemoteNodeEdit.qml
pages/settings/SettingsNode.qml
wizard/WizardDaemonSettings.qml

RemoteNodeEdit: initialAddress, add square brackets on ipv6 input

---

components/PasswordDialog.qml

Prevent textbox from turning active when window is not active.

---

pages/Mining.qml

Mining: Indicate probability of finding a block in one day

---

js/Utils.js

Test commit to see how this looks in weblate.

Utils: simplify for translations

---

pages/Transfer.qml

Support comma seperator for amount field, dynamically change to dot. 

---

pages/settings/SettingsInfo.qml

Fixes #2441 
Donate to Monero devfund.

Donate to Monero feature

---

CMakeLists.txt

cmake: set current monero-gui version

---

src/main/main.cpp
src/qt/KeysFiles.cpp
src/qt/KeysFiles.h
wizard/WizardOpenWallet1.qml

Requires https://github.com/monero-project/monero-gui/pull/3006

KeysFiles: fix WalletKeysFilesModel, should be instantiable QML type

---

CMakeLists.txt

Fixes https://github.com/monero-project/monero-gui/issues/3011

cmake: fix static libraries linking

---

components/QRCodeScanner.qml
src/QR-Code-scanner/QrCodeScanner.cpp
src/QR-Code-scanner/QrCodeScanner.h

Requires https://github.com/monero-project/monero-gui/pull/3017

QrCodeScanner: use parse_uri_to_object to parse scanned codes

---

main.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h
src/main/main.cpp

Requires https://github.com/monero-project/monero-gui/pull/3018

WalletManager: instantiable QML type

---

monero-wallet-gui.pro
windeploy_helper.sh

this is a workaround on QT 5.14+ windeploy on mingw 
fixes issue https://github.com/monero-project/monero-gui/issues/3041

fix windows deploy with QT 5.14+

---

src/qt/downloader.cpp
src/qt/downloader.h

Requires https://github.com/monero-project/monero/pull/6716 and https://github.com/monero-project/monero-gui/pull/3054

Downloader: introduce proxyAddress property

---

main.qml
src/main/main.cpp
src/qt/network.cpp
src/qt/network.h

Requires monero-project/monero#6716 and https://github.com/monero-project/monero-gui/pull/3054

Network: instantiable QML type, introduce proxyAddress property

---

get_libwallet_api.sh

Requires https://github.com/monero-project/monero/pull/6789

monero: update submodule to master branch HEAD

---

pages/settings/SettingsInfo.qml

Settings -> Info -> Copy to clipboard

---

pages/merchant/MerchantTrackingList.qml

MerchantTrackingList: fix Qt warning

---

wizard/WizardRestoreWallet1.qml

WizardRestoreWallet1: reset radio buttons when loading

---

cmake/Deploy.cmake
src/CMakeLists.txt

cmake: add deploy target (mac / windows)

---

components/PasswordDialog.qml
components/StandardButton.qml
main.qml

Related: https://github.com/monero-project/monero-gui/pull/2895

PasswordDialog: configurable Ok btn text/icon, non-primary Cancel

---

.github/workflows/build.yml

Requires https://github.com/monero-project/monero-gui/pull/3112

workflows: cache docker build environment images

---

js/Wizard.js
main.qml
pages/History.qml
pages/Transfer.qml
pages/settings/SettingsInfo.qml
wizard/WizardController.qml
wizard/WizardOpenWallet1.qml
wizard/WizardWalletInput.qml

Requires https://github.com/monero-project/monero-gui/pull/3023

main: accountsDir runtime configuration support

---

LeftPanel.qml

LeftPanel: add missing emptyString

---

CMakeLists.txt

bundle version still gets taken from here

cmake: update version

---

README.md

- Forked.net does not support https
- remove www -> none redirect Symas

README: minor sponsorships fixes

---

pages/Transfer.qml

Transfer: fix help text (white theme)

---

components/NetworkStatusItem.qml
main.qml

Closes https://github.com/monero-project/monero-gui/issues/2394

NetworkStatusItem: 'starting/stopping the node' status (no splash)

---

src/libwalletqt/Wallet.cpp

Requires https://github.com/monero-project/monero/pull/6902

Wallet: interrupt refresh thread on wallet close

---

src/libwalletqt/Wallet.cpp

Co-authored-by: Bertrand Jacquin <bertrand@jacquin.bzh>

Wallet: fix different signedness comparison (-Werror=sign-compare)

---

CMakeLists.txt
src/CMakeLists.txt

Requires https://github.com/monero-project/monero-gui/pull/3185

cmake: Android cross compilation support

---

src/qt/FutureScheduler.cpp

Closes https://github.com/monero-project/monero-gui/issues/3196

QThreadPool: adjust max threads count (4)

---

components/LanguageButton.qml
qml.qrc
wizard/WizardHome.qml
wizard/WizardLanguage.qml

Co-authored-by: @rating89us (https://github.com/monero-project/monero-gui/pull/3178)

WizardLanguage: WizardHome: introduce LanguageButton component

---

CMakeLists.txt
Dockerfile.linux
src/main/main.cpp

Requires https://github.com/monero-project/monero-gui/pull/3224

docker: Linux - use Qt 5.15.2

---

wizard/WizardRestoreWallet1.qml

Closes https://github.com/monero-project/monero-gui/issues/2852

WizardRestoreWallet1: fix mnemonic seed placeholder

---

installers/windows/Monero.iss

Qt 5.15 supports high DPI natively

installer: remove high dpi shortcut

---

pages/Receive.qml

Receive: remove copy qr uri to clipboard button

---

pages/Transfer.qml
src/QR-Code-scanner/Decoder.cpp
src/QR-Code-scanner/Decoder.h
src/main/oshelper.cpp
src/main/oshelper.h
src/qt/macoshelper.h
src/qt/macoshelper.mm

Transfer: implement 'Grab QR code from screen' functionality

---

.github/workflows/build.yml
README.md

Fixed https://github.com/monero-project/monero-gui/issues/3234

README: MacOS - add libsodium monero dependency

---

main.qml
pages/settings/SettingsLayout.qml

Closes https://github.com/monero-project/monero-gui/issues/3300

SettingsLayout: 'Display wallet name in title bar' option

---

pages/settings/Navbar.qml
pages/settings/Settings.qml

Didn't touch the indentation, i will be doing further refactoring once this one gets merged.

Navbar: cleanup layout

---

README.md

This is my first PR here, so please let me know if I'm missing anything :)

README: Update the homebrew install instructions

---

src/main/oshelper.cpp

Fixes https://github.com/monero-project/monero-gui/issues/3324

OSHelper: Linux - fix isCapsLock memory leak

---

MiddlePanel.qml
components/TxConfirmationDialog.qml
main.qml
pages/Transfer.qml
src/libwalletqt/WalletManager.cpp
src/libwalletqt/WalletManager.h

Only the second commit is a subject for review.

Tx confirmation multiple addresses support

---

.github/workflows/build.yml
README.md
fonts/FontAwesome/FontAwesome.qml
pages/Transfer.qml

Design is inspired by https://github.com/monero-project/monero-gui/issues/740 discussion. Thanks to all the participants.
Closes https://github.com/monero-project/monero-gui/issues/740.
Requires https://github.com/monero-project/monero-gui/pull/3325.
Only the last commit is a subject for review.

Transfer: implement sending to multiple recipients 

---

LeftPanel.qml
MiddlePanel.qml
main.qml
pages/Advanced.qml
pages/Mining.qml
pages/SharedRingDB.qml
pages/Sign.qml
pages/TxKey.qml
qml.qrc

LeftPanel: drop Advanced submenu items, use NavBar instead

---

main.qml
src/daemon/DaemonManager.cpp
src/daemon/DaemonManager.h
wizard/WizardDaemonSettings.qml
wizard/WizardModeSelection.qml

Addresses #2087
Wallets set up in simple mode will use a pruned node by default going forward. Pruning is optional and turned off by default in advanced mode.

Blockchain pruning support for new databases

---

components/Dialog.qml
components/RemoteNodeDialog.qml
main.qml
pages/settings/SettingsNode.qml
qml.qrc
wizard/WizardDaemonSettings.qml
wizard/WizardSummary.qml

Closes https://github.com/monero-project/monero-gui/issues/1008

SettingsNode: implement multiple remote nodes support

---

pages/settings/SettingsNode.qml

The edit icon was significantly larger.

SettingsNode: fix icon size

---

src/CMakeLists.txt

cmake: remove typo

---

components/InlineButton.qml
pages/Transfer.qml

Transfer: fix desktop icon style

---

components/AdvancedOptionsItem.qml
components/Label.qml
components/TextPlain.qml
components/Tooltip.qml
pages/Transfer.qml
qml.qrc

Fixes https://github.com/monero-project/monero-gui/issues/3398

TextPlain, Label: implement tooltips. Transfer: advanced - use tooltips

---

components/Navbar.qml

Navbar: fix width being slightly off

---

components/RemoteNodeList.qml
pages/settings/SettingsNode.qml
qml.qrc
wizard/WizardDaemonSettings.qml

Also fixes remote node duplication bug reported by @selsta  via IRC.

WizardDaemonSettings: implement full remote node configuration support

---

pages/Account.qml
pages/Receive.qml

Account, Receive: add missing fallback icons

---

pages/merchant/Merchant.qml

Merchant: display selected subaddress

---

components/Navbar.qml

Navbar: fix layout bug on resize

---

Dockerfile.android
Dockerfile.linux

Resolves #3389
Bintray is shutting down.

docker: fix boost bintray links

---

pages/Transfer.qml

Fixes https://github.com/monero-project/monero-gui/issues/3399
Requires https://github.com/monero-project/monero-gui/pull/3462

Transfer: highlight invalid address

---

js/Wizard.js

https://github.com/monero-project/monero/pull/7682

js: fix getApproximateBlockchainHeight (testnet)

---

pages/Receive.qml

The "search transactions" button will open Transactions page and search all sent/received transactions of an address.

Receive: add search transactions button

---

main.qml

main: hide/show popups before/after inactivity screen lock

---

pages/History.qml

History: clean search bar inline button

---

components/DatePicker.qml

Low graphics mode Font Awesome fallback icons for left/right arrows (previous/next month) and down/up arrows (open/close calendar)

DatePicker: FontAwesome fallback icons

---

README.md

https://github.com/monero-project/meta/issues/575

README: freenode -> libera

---

main.qml

main: fix bug not accepting new restore height

---

src/libwalletqt/TransactionHistory.cpp

TransactionHistory: use displayAmount for amount

---

components/StandardDropdown.qml

These dots should also have been removed in #2717.

StandardDropdown: remove dots from corners

---

components/Label.qml
components/RemoteNodeList.qml
fonts/FontAwesome/FontAwesome.qml

RemoteNodeList: display shield icon if trusted daemon

---

main.qml
pages/Account.qml

Changes:
- remove "Balance:" label
- account balances always visible, even with small window width
- add XMR to balances
- align balances

Account: remove "Balance:" label; add XMR; align balances

---

main.qml

Should make it simpler to add more currencies later.

main: simplify fiat ticker code

---

components/QRCodeScanner.qml
pages/Transfer.qml

qr: scan valid addresses that miss an uri prefix

---

pages/Transfer.qml

ping @rating89us please review

Transfer: fix fee label alignment

---

external/CMakeLists.txt

cmake: enable position independent code for quirc

---

wizard/WizardCreateDevice1.qml

WizardCreateDevice1: move "choose your device" dropdown to the top

---

pages/settings/SettingsInfo.qml

closes #3612
Also fixes displaying of Tails persistence.

SettingsInfo: fix displaying of Graphics mode on clipboard output

---

components/Tooltip.qml

This fixes a binding loop for me. I did not find any issues with removing this.
ping @xiphon

Tooltip: fix binding loop

---

components/Tooltip.qml

Tooltip: fix tooltip width

---

components/NetworkStatusItem.qml

Changes
- add tooltip to switch node button
- adjust colors of lightning icon (when disconnected), switch node button and network status

NetworkStatusItem: add tooltip to switch node button; adjust colors

---

pages/Transfer.qml
src/libwalletqt/Wallet.cpp
src/libwalletqt/Wallet.h

Resolves #3246
Depends on monero-project/monero#7185

Transfer: export all key images by default

---

CMakeLists.txt
src/CMakeLists.txt

Requires https://github.com/monero-project/monero/pull/7693

cmake: cleanup boost

---

.github/workflows/build.yml

https://github.community/t/expression-syntax-for-not-startswith/17040/3

workflows: don't use cache on release tag

---

src/libwalletqt/TransactionHistory.cpp
src/libwalletqt/TransactionInfo.cpp
src/libwalletqt/TransactionInfo.h

Closes #3567 
Requires a submodule update before merging.

TransactionHistory: add description to csv export

---

CMakeLists.txt
src/CMakeLists.txt

Requires https://github.com/monero-project/monero/pull/7712

cmake: cleanup openssl

---

README.md

adding the 3rd party flatpak to the available packages. thought about explicitly stating that its 3rd party but the others arent denoted 🤷‍♂️

README: add flatpak to available packages

---

pages/Receive.qml

https://github.com/monero-project/monero/issues/8012

Receive: set maximum length for qr string

---

README.md

PR part of my CCS: https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/260#note_12546

Remove reference from mattermost and add Matrix room link

---

components/ContextMenu.qml
components/ContextMenuItem.qml
components/Input.qml
components/InputMulti.qml

Main changes:
- add Cut, Copy, Delete, and Select All
- remove icon
- increase width and left margin

ContextMenu: add Cut, Copy, Delete and Select All

---

src/zxcvbn-c/zxcvbn.c

https://github.com/tsyrogit/zxcvbn-c/pull/11

zxcvbn: fix buffer overflow

---

pages/AddressBook.qml

This button can also be used to edit/delete an address.

AddressBook: fix edit address button tooltip

---

pages/Account.qml

To be consistent with Receive page, use StandardButton in same position and size in Account Page:

Account: use StandardButton for "Create new account"

---

pages/AddressBook.qml

This PR improves buttons on Address Book

AddressBook: use small StandardButton; adjust buttons alignment/order; remove paste button

---

components/StandardDropdown.qml

StandardDropdown: remove bold text of dropdown items

---

LeftPanel.qml

LeftPanel: display full keyboard shortcuts for Windows, Mac, and Linux

---

wizard/WizardAskPassword.qml
wizard/WizardCreateWallet2.qml
wizard/WizardRestoreWallet2.qml

Password fields are now cleaned when the user clicks on the back buttons until reaching main menu.

WizardAskPassword: clean password fields when clicking on Back button

---

components/Navbar.qml
pages/Advanced.qml
pages/settings/Settings.qml

Settings, Advanced: mirror stack transition when clicking on a button on the left

---

wizard/WizardAskPassword.qml
wizard/WizardCreateWallet1.qml
wizard/WizardCreateWallet2.qml
wizard/WizardCreateWallet4.qml
wizard/WizardRestoreWallet1.qml
wizard/WizardRestoreWallet2.qml
wizard/WizardRestoreWallet4.qml

wizard: clear password field after wallet creation

---

DEPLOY.md

DEPLOY: use correct ARCH

---

README.md

README: add more missing macOS dependencies

---

translations/monero-core_af.ts
translations/monero-core_de.ts
translations/monero-core_he.ts
translations/monero-core_hu.ts
translations/monero-core_ja.ts
translations/monero-core_nl.ts
translations/monero-core_pl.ts
translations/monero-core_ro.ts
translations/monero-core_zh-cn.ts

- Romanian
- Dutch
- Japanese
- Hungarian
- Hebrew
- Dutch
- Polish
- Chinese (Simplified)
- German

Adding translations from Weblate

---

Makefile

Makefile: fix release-linux-armv8

---

CMakeLists.txt
main.qml
src/main/main.cpp

main: add compile time option to disable desktop entry dialog

---

src/libwalletqt/Wallet.cpp

libwalletqt: fix typo in type

---

Dockerfile.android

Docker: Update zlib for android

---

.github/workflows/build.yml

workflows: action-docker-layer-caching v0.0.11

---

CMakeLists.txt

build: prepare v0.17.3.2

---

main.qml

The bug doesn't exist anymore.

main: remove outdated code

---

js/Windows.js

js: minimize frameless window when clicking on taskbar icon

---

CMakeLists.txt
src/main/main.cpp

ping @BigmenPixel0 and @kpcyrd this should also be helpful for package manager

main: add compile time option to disable updates

---

src/qt/KeysFiles.cpp
src/qt/ipc.cpp

`QTextCodec` is removed in Qt6

qt: remove QTextCodec

---

installers/windows/Monero.iss
src/p2pool/P2PoolManager.cpp
src/p2pool/P2PoolManager.h

And set the correct file permissions on it so it can be run without administrator privileges.

Use `p2pool` folder for p2pool on Windows

---

pages/Mining.qml

Mining: add info to start gui as admin for p2pool installation

---

pages/Transfer.qml

ping @reemuru you have used offline transaction signing before, could you review this?

Transfer: don't create offline tx before wallet is synced

---

components/DaemonManagerDialog.qml

This can be triggered when having a restricted local node running.

DaemonManagerDialog: close dialog when GUI is connected

---

src/p2pool/P2PoolManager.cpp

p2pool v2.2 has full support for the coming Monero network upgrade

Updated to p2pool v2.2

---

src/p2pool/P2PoolManager.cpp

Previous version had a few bugs which were fixed in v2.2.1: https://github.com/SChernykh/p2pool/releases/tag/v2.2.1

Updated to p2pool v2.2.1

---

.github/workflows/build.yml
Dockerfile.android

jftr, latest stable libgpg-error is 1.42 (not 1.41 in this PR) but it fails to build.

Docker android: upgrade build tools and dependencies

---

main.qml

```
W qrc:/main.qml:697: TypeError: Cannot read property 'refreshHeightAsync' of undefined
```
Reported by @plowsof

main: fix a potential warning

---

Dockerfile.android

docker: update zlib on android

---

pages/Transfer.qml

Transfer: update mixin, silence warning

---

pages/History.qml

History: add open folder button after CSV export

---

main.qml
pages/Advanced.qml
pages/Sign.qml

closes #4073 
selsta gave a helping hand after i tortured myself for more than a day, thanks!

Sign/Verify: clear text fields on wallet close

---

README.md

README: add unbound for Windows

---

main.qml

main: skip proxy when setting localhost remote node

---

README.md

README: remove unmaintained debian repo

---

js/TxUtils.js
pages/AddressBook.qml
pages/Transfer.qml

Simplifies code and removes code duplication.

TxUtils: add handleOpenAliasResolution func, simplify code

---

installers/windows/ReadMe.htm

The blockchain size mentioned in installers/windows/Readme.htm was 3 years out of date.    
I also added information regarding blockchain pruning

 installers/windows/Readme.htm Updated blockchain size and added pruning description

---

README.md

https://github.com/monero-project/monero-gui/issues/3855#issuecomment-1510436318

README: add mingw-w64-x86_64-pcre for msys2 instructions

---

.github/workflows/flatpak.yml

workflows: run flatpak only in main repo

---

js/TxUtils.js

https://github.com/monero-project/monero/issues/9066

TxUtils: use regex to check for valid domain

---

src/qt/utils.cpp

utils: add quotes to desktop entry path

---

js/TxUtils.js

This does not allow `test.address@domain.org`, any opinions on if I should change that?

TxUtils: allow @ in OpenAlias domain

---

README.md

https://github.com/monero-project/monero/pull/9324

README.md: sponsors;remove forked networking/globee

---

README.md

README: clarify docker build process

---

js/TxUtils.js
pages/History.qml
wizard/WizardAskPassword.qml
wizard/WizardRestoreWallet1.qml

Remove unused JS variables that are never used and most likely will never be used to improve code readability
Changes are cherry picked from results of static analasys using https://github.com/justxd22/qml-linter-xd

Remove unused JS variables

---

components/PasswordDialog.qml

I am not sure how this was overlooked, but this PR fixes it.

CAPSLOCKS => CAPSLOCK.

---

src/p2pool/P2PoolManager.cpp

p2pool: update to v4.9.1
